### ISSUE TITLE
Questie dosent work for my main charachter

### ISSUE THREAD

**Issue by xzxdiablo** [AeroScripts/QuestieDev#417] opened 2017-03-16 23:45 UTC
@so questie works perfectly fine whit all my characther exepct my main after doing a quest in azshara (i dont remember the name) and now only if i start it(example slain X 0/10 i kill 1X it start to show on map etc) but only whit him please help,i dont know how to enlarge the chat so i had to do this this is whit my main charachter:
![screen 4 1 hiki](https://cloud.githubusercontent.com/assets/26471025/24023164/bf1246b8-0aaa-11e7-9860-cbf7cb961401.png)
(url)
![screen2 hiki](https://cloud.githubusercontent.com/assets/26471025/24023179/dc63a8ce-0aaa-11e7-9d92-ef9c753747af.png)
this whit the others 
![Uploading  @screen1.png…]()

**Comment by xzxdiablo** [comment] 2017-03-16 23:46
dosent shown the others characther but works just fine for the others

**Comment by ZoeyZolotova** [comment] 2017-03-17 09:33
What quest do you have to start for it show on the map? Does toggling questie off and on make the icons appear?

**Comment by xzxdiablo** [comment] 2017-03-17 16:04
I also had arathi basin and i tried to delete it and everything works just fine IF i abbando and reaccept all the quest afterwards it seems ill do more testing today whit more quest but i think that was the problem

**Comment by ZoeyZolotova** [comment] 2017-03-18 11:22
What version of Questie are you running? Do you feel this issue is the same as #413 ?

**Comment by xzxdiablo** [comment] 2017-03-18 14:26
Im running the 3.69

Il 18/Mar/2017 12:22, "ZoeyZolotova" <notifications@github.com> ha scritto:

**Comment by ZoeyZolotova** [comment] 2017-03-18 14:52
Ok well it seems this is a duplicate of #413 so I'm marking it as such. If you have information that suggests otherwise, let us know.

**Closed** 2017-04-10 18:39 UTC
Labels: duplicate, fix will be in next release
