### ISSUE TITLE
Feature Suggestion: (D)ungeon, (E)elite, and (R)raid character suffixes for map quest node tooltips.

### ISSUE THREAD

**Issue by Ghamarro** [AeroScripts/QuestieDev#1272] opened 2019-10-11 09:51 UTC
## Description

For example, the Quester addon adds the appropriate letter next to the quest level in your quest log to notify you which type of quest it is. It would be madly useful for the map tooltips for Questie to do this also, as all of us have not yet memorized every single vanilla quest =), and only like to pick up soloable quests on their first run-through of a quest hub to save space in our quest logs, and then come back later for the group, dungeon and raid ones. At the curent state, you can only see the quest level and name in the tooltip when you hover over a quest node on your map, so you basically have to accept the quest and look it up from your log to see which type it is, and then abandon it it, if it is the wrong kind. This is totally a chore and a total bummer. Also mad proprs for bringing the best addon in classic!

**Comment by BreakBB** [comment] 2019-10-16 12:14
Duplicate of #1055

**Closed by BreakBB** 2019-10-16 12:14 UTC
Labels: feature request
