### ISSUE TITLE
Questie showing quest log as empty upon log in

### ISSUE THREAD

**Issue by Rhakfrost** [AeroScripts/QuestieDev#1832] opened 2020-03-19 14:18 UTC
Logging in after a period of time causes all quests to act 'abandoned'. Uninstalling questie, logging in, logging out, and reinstalling questie fixes the issue, but occurs the next day. /reload does NOT work for me, as seen in other report from HQOFIQ #1823 

Up to date on 5.10

Let me know if I can provide further info...has been happening for approx 4 days to myself, have seen people ask in General chat about it.

**Comment by BreakBB** [comment] 2020-03-19 14:27
@Rhakfrost You are on v5.10.0 and restarted the game after the update?

**Comment by Rhakfrost** [comment] 2020-03-19 14:28
@BreakBB Yes, fully exited and started back up after install

**Comment by BreakBB** [comment] 2020-03-19 14:29
@Rhakfrost Could you delete your "cache" folder and start the game? This bug should be fixed since v5.9.0.

**Comment by Rhakfrost** [comment] 2020-03-19 14:31
Deleted, and restarted 
![image](https://user-images.githubusercontent.com/62389051/77078325-6bb8c880-69c4-11ea-998d-2a18b08dd9da.png)

**Comment by BreakBB** [comment] 2020-03-19 14:38
Could you try to disable all addons except Questie and try again? I can't reproduce this.

**Comment by Rhakfrost** [comment] 2020-03-19 15:18
Cleared everything, cache, uninstalled, reinstalled, seems fine now

**Comment by BreakBB** [comment] 2020-03-19 15:29
Strange though... But you can't reproduce it anymore?

**Comment by Rhakfrost** [comment] 2020-03-19 15:39
So far its good, strange is right

**Comment by BreakBB** [comment] 2020-03-19 15:48
I will close this issue then for now. Please contact us again whenever something comes up :+1:

**Closed** 2020-03-19 15:48 UTC
Labels: bug
