### ISSUE TITLE
Quest Available Icons showing on UI

### ISSUE THREAD

**Issue by Mnudge** [AeroScripts/QuestieDev#1306] opened 2019-10-13 15:03 UTC
![WoWScrnShot_101319_095146](https://user-images.githubusercontent.com/56511999/66717597-68c80500-eda0-11e9-95dc-1a28cefeb7c4.jpg)
![WoWScrnShot_101319_095150](https://user-images.githubusercontent.com/56511999/66717602-6ebde600-eda0-11e9-8afa-023d46ca87db.jpg)

The quests tied to the icons is actually a questgiver in Dustwallow Marsh
https://classic.wowhead.com/quest=7070/shadowshard-fragments
https://classic.wowhead.com/npc=4967/archmage-tervosh

This is a new bug, just evident today after I updated Questie.  Reloads won't affect it.  Options in the add-one won't affect it.   

I flew out of Ironforge and when I changed zones the icons disappeared

**Comment by drkingkong** [comment] 2019-10-13 15:49
Same problem. 
I think it needs hot-fix

**Comment by njbaker7** [comment] 2019-10-13 15:52
Same here.

**Comment by drejjmit** [comment] 2019-10-13 15:52
Integration of the DBM HUD (this shows quests and their objectives directly on screen (requires the DBM addon)) Disable by going into options!

**Comment by Muehe** [comment] 2019-10-13 15:54
Like Dreijmit said, you can disable it in the settings.

Closed as duplicate of #1296

**Closed by Muehe** 2019-10-13 15:54 UTC
Labels: bug
