### ISSUE TITLE
Intermittent bug on turning in quests

### ISSUE THREAD

**Issue by Nerillida** [AeroScripts/QuestieDev#2003] opened 2020-06-07 10:33 UTC
Specifically The People's Militia quest=12
Date: 2020-06-07 11:28:34
ID: 1
Error occured in: Global
Count: 1
Message: ...terface\AddOns\Questie\Modules\QuestieReputation.lua line 26:
   attempt to perform arithmetic on a string value
Debug:
   ...terface\AddOns\Questie\Modules\QuestieReputation.lua:26: Update()
   ...rface\AddOns\Questie\Modules\QuestieEventHandler.lua:310:
      ...rface\AddOns\Questie\Modules\QuestieEventHandler.lua:308
   [C]: ?
   ...ibDataBroker\CallbackHandler\CallbackHandler-1.0.lua:29:
      ...ibDataBroker\CallbackHandler\CallbackHandler-1.0.lua:25
   ...ibDataBroker\CallbackHandler\CallbackHandler-1.0.lua:64: Fire()
   ...ddOns\EMA-Classic\Libs\AceEvent-3.0\AceEvent-3.0.lua:120:
      ...ddOns\EMA-Classic\Libs\AceEvent-3.0\AceEvent-3.0.lua:119
Locals:
None
AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  AdvancedInterfaceOptions, v1.3.3
  AucAdvanced, v8.2.6471 (SwimmingSeadragon)
  auccheapsearcher, v20190917r3
  AucFilterBasic, v8.2.6497 (SwimmingSeadragon)
  AucScanData, v8.2.6498 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6499 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6503 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6500 (SwimmingSeadragon)
  AucStatSimple, v8.2.6501 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6502 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6504 (SwimmingSeadragon)
  BadBoy, vv1-classic
  BadBoyCCleaner, vv8.2.0
  BadBoyGuilded, vv8.2.0
  BasicChatMods, vv4-classic
  BeanCounter, v8.2.6505 (SwimmingSeadragon)
  BetterVendorPrice, vv1.12.00
  ClassicCastbars, vv1.2.11
  ClassicCastbarsOptions, v
  ClassicSpellActivations, v
  ClassTrainerPlus, v0.7-beta
  CTBarMod, v8.3.0.8
  CTBuffMod, v8.3.0.8
  CTCore, v8.3.0.8
  CTLibrary, v8.3.0.8
  CTMailMod, v8.3.0.7
  CTMapMod, v8.3.0.8
  CTPartyBuffs, v8.2.5.6
  CTUnitFrames, v8.3.0.7
  DidIDoIt, v1.2.0
  EMAClassic, vv1.13.4-Release-v0.7(121025)
  Enchantrix, v8.2.6506 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6507 (SwimmingSeadragon)
  ExtVendorUIClassic, v1.0.4
  FloAspectBar, v
  FloTotemBar, v
  GatherMate2, v1.45.4
  Grail, v109
  GrailNPCsclassic, v27178
  GrailNPCsclassicenUS, v33302
  GrailQuestsclassic, v27178
  GrailQuestsclassicenUS, v33302
  GrailReputationsclassic, v007
  GrailWhen, v002
  GSE, v2.5.5
  GSEGUI, v2.5.5
  GSELDB, v2.5.5
  Informant, v8.2.6508 (SwimmingSeadragon)
  ISBoxer, v1.0
  LetMeCast, v1.3
  MageButtons, v1.0
  Mapster, v1.8.5
  Misspelled, v1.7.7
  MonkeyBuddy, v
  MonkeyLibrary, v
  MonkeyQuest, v
  MonkeyQuestLog, v
  OmniCC, v8.2.4
  QuestFrameFixer, v1.1.1
  QuestIconDesaturation, v3.1
  Questie, v5.10.3
  QuestLogEx, v1.2
  SlideBar, v8.2.6509 (SwimmingSeadragon)
  SpamThrottleClassic, vv4.0c
  Stubby, v8.2.6510 (SwimmingSeadragon)
  TFTB, v1.10
  TitanClassic, v1.2.1.11304
  TitanClassicAmmo, v1.2.1.11304
  TitanClassicBag, v1.2.1.11304
  TitanClassicClock, v1.2.1.11304
  TitanClassicGold, v1.2.1.11304
  TitanClassicLocation, v1.2.1.11304
  TitanClassicLootType, v1.2.1.11304
  TitanClassicPerformance, v1.2.1.11304
  TitanClassicRegen, v1.2.1.11304
  TitanClassicRepair, v1.2.1.11304
  TitanClassicVolume, v1.2.1.11304
  TitanClassicXP, v1.2.1.11304
  WhatsTraining, v1.8.7
  Wholly, v078
  BlizRuntimeLib_enUS v1.13.4.11304 <none>
  (ck=971)

**Comment by drejjmit** [comment] 2020-06-07 10:55
This is fixed with https://github.com/AeroScripts/QuestieDev/commit/b45c0236792c46d703e7eab9ca4f673312511333 and will be included in next release. Thanks for the report.

**Comment by BreakBB** [comment] 2020-06-08 10:27
Duplicate of #1965 and already fixed.

**Closed** 2020-06-08 10:28 UTC
Labels: bug
