### ISSUE TITLE
Lua error (unsure what caused it)

### ISSUE THREAD

**Issue by Treeston** [AeroScripts/QuestieDev#1881] opened 2020-04-20 03:10 UTC
## Bug description
Lua error landed in my BugSack. No idea what caused it.

```
1x ...ceQuestie\Modules\Tracker\QuestieTracker.lua:791: 'for' limit must be a number
...ceQuestie\Modules\Tracker\QuestieTracker.lua:791: in function <...ceQuestie\Modules\Tracker\QuestieTracker.lua:783>
SharedXML\C_TimerAugment.lua:16: in function <SharedXML\C_TimerAugment.lua:14>

Locals:
(for index) = 1
(for limit) = nil
(for step) = 1
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "'for' limit must be a number"
_QuestieTracker = <table> {
 ItemButtons = <table> {
 }
 StartFadeTicker = <function> defined @Questie\Modules\Tracker\QuestieTracker.lua:781
 baseFrame = <unnamed> {
 }
 CreateActiveQuestsFrame = <function> defined @Questie\Modules\Tracker\QuestieTracker.lua:416
 expandButton = <unnamed> {
 }
 GetNextItemButton = <function> defined @Questie\Modules\Tracker\QuestieTracker.lua:776
 PrintProgressColor = <function> defined @Questie\Modules\Tracker\QuestieTracker.lua:1040
 GetNextLine = <function> defined @Questie\Modules\Tracker\QuestieTracker.lua:769
 FadeTickerDirection = true
 menuFrame = QuestieTrackerMenuFrame {
 }
 OnDragStop = <function> defined @Questie\Modules\Tracker\QuestieTrackerPrivates.lua:38
 LineFrames = <table> {
 }
 FadeTicker = <table> {
 }
 SetSafePoint = <function> defined @Questie\Modules\Tracker\QuestieTracker.lua:308
 activeQuestsFrame = <unnamed> {
 }
 IsFirstRun = true
 OnDragStart = <function> defined @Questie\Modules\Tracker\QuestieTrackerPrivates.lua:14
 FadeTickerValue = 0.060000
}
```

## Questie version
`## Version: 5.10.1`

**Comment by BreakBB** [comment] 2020-04-26 12:25
Duplicate of #1868

**Closed by BreakBB** 2020-04-26 12:25 UTC
Labels: bug
