### ISSUE TITLE
Questie 3.7 Tooltip issue with ModUI

### ISSUE THREAD

**Issue by RtooDtu** [AeroScripts/QuestieDev#508] opened 2018-06-23 14:02 UTC
Questie isn't showing quest mobs or quest progress in Tooltip. Not sure if it is an issue with Questie or ModUI but unfortunately ModUI is no longer supported. The issue goes away when I turn off Tooltips in ModUI elements.

edit: I managed to find an older version of Questie (it was not easy, pretty sure I am using v3.1) and I'm having no tooltip issues with ModUI

**Comment by Muehe** [comment] 2018-08-07 20:19
Closed as duplicate of #501 

Thanks for the info though! If you find out anything more, please let us know in the other issue.

**Closed by Muehe** 2018-08-07 20:19 UTC
