### ISSUE TITLE
"The Cliffspring River" objective location is missing

### ISSUE THREAD

**Issue by Jezz1e** [AeroScripts/QuestieDev#723] opened 2019-09-01 05:57 UTC
This quest is from Darkshore. After receiving the quest you are suppose to go to 50.85 25.65 to fill up the sampling tube.

Yes I tried /reload twice and it's still missing

**Comment by AeroScripts** [comment] 2019-09-01 06:08
This is a duplicate of #673 actually. We're going to be going through the database related issues on github very soon, been busy with some critical bugs moreso than we expected

**Closed by AeroScripts** 2019-09-01 06:08 UTC
