### ISSUE TITLE
Syndicate Emblems / Rep Level increase doesn't update questie

### ISSUE THREAD

**Issue by Djfe** [AeroScripts/QuestieDev#1939] opened 2020-05-13 12:11 UTC
## Description

Turning in Quests like this one should trigger a rep update for questie, so you don't have to /reload to update the available quests for higher rep levels.

## Wowhead link

https://classic.wowhead.com/quest=6701/syndicate-emblems#english-comments

## Questie version

5.10.2

**Comment by BreakBB** [comment] 2020-05-13 18:55
@Djfe Questie actually listens to reputation updates and should re calculate the available quests when you reach a new faction level like friendly, honored, etc. Could you explain in detail what happened to you?

**Comment by Djfe** [comment] 2020-05-13 21:49
interesting, I used the turn in add-on so I was able to turn in the quests really fast, maybe that caused this?
once I got friendly the blue quest icons where still visible on the map and minimap
/reload and they were gone

**Comment by RealBorlak** [comment] 2020-05-27 21:16
Are you showing LUA errors?
I noticed that Questie (5.10.3) throws a LUA error message when completing a reputation rank.
Maybe the update does not happen as it encounters the issue but you don't see the message and after a /reload everything is loaded correctly.

Interface\AddOns\Questie\Modules\Libs\QuestieSerializer.lua:26
attempt to perform arithmetic on a string value

Line 26 uses + to combine the strings in the debug output instead of ..

**Comment by BreakBB** [comment] 2020-05-29 20:19
@RealBorlak Yeah that was a stupid issue we added, but it is already fixed on the master branch and will be included in the upcoming release.

I guess @Djfe is showing Lua errors because he reported such in the past. Also I think the problem is included only in v5.10.3

**Comment by BreakBB** [comment] 2020-07-01 18:57
This should be fixed and should also work more reliable with the upcoming release of v6.0.0. Feel free to open up a new issue if something like this comes up again 🙏

**Closed by BreakBB** 2020-07-01 18:57 UTC
Labels: need more info, quest issue
