### ISSUE TITLE
QuestTracker window is stuck in top left corner and can't be moved

### ISSUE THREAD

**Issue by Muellerbones** [AeroScripts/QuestieDev#194] opened 2016-03-23 08:10 UTC
Hi, I'm having an issue with 2.62 where the quest tracker window is stuck covering up the character and target panels in the top left of the screen.  It doesn't allow me to drag and drop it.  When I try toggle the tracker off, it just automatically reappears after completing a quest objective.  Is there a command option to make the quest tracker window moveable?

**Comment by Muehe** [comment] 2016-03-23 12:17
Use Ctrl+Shift+Click.

**Comment by vendethiel** [comment] 2016-03-23 17:27
Another option is to reset config...

**Comment by MarkusNemesis** [comment] 2016-03-24 22:13
I am also having the same issue. I'm aware of the Ctrl Shift Click requirement (because I suggested it). Resetting config didn't work.

When I mouse over the tracker, it doesn't highlight itself with the dark border, and clicking on quests doesn't bring up the tracker arrow either. It's as if the tracker is behind something else, but I've no other mods running.

**Comment by Dyaxler** [comment] 2016-03-24 22:39
The "Dark Border" no longer exists. The frame was causing some lag so I removed it. The buttons (individual quest entries) are set to 250 pixels wide... more than wide enough to detect the frame that the OnDrag code needs to move the frame. I've tested this extensively. There has to be something wrong with your config.

Are you running WoW installed outside "C:\Program Files" or "C:\Program Files (x86)"? There is a known issue with the Vanilla WoW client that I can't code around.

**Comment by vendethiel** [comment] 2016-03-24 22:49
I, myself, are indeed running from outside that dir. What's the issue?

**Comment by MarkusNemesis** [comment] 2016-03-24 22:53
Running from C:\

**Comment by Dyaxler** [comment] 2016-03-25 00:04
I did "sort of" reproduce the issue you're experiencing...

When I first login a character for the first time after an upgrade I can't click on the tracker or make the arrow appear IF... I immediately try to use the feature after logging in. I had to click on the tracker a couple of times to get an arrow to appear. THEN I was able to use it normally. Even after a reload or relog. It's only initially. I think the frame data just needed to be updated and saved in the characters saved variables file. One of the many quirks with LUA...

**Comment by Heishe** [comment] 2016-03-25 12:12
Having the same problem! Running from c:/program files (or x86) doesn't do anything. Also, for me it's stuck in the bottom left corner!

**Comment by raichuuuu** [comment] 2016-03-25 14:48
I had this problem with 2.63 as well. Tried all of the suggestions, left it running to see if it figured itself out. My tracker loaded right over the chat - I had to adjust the top/bottom style settings of the tracker. This moved it to the middle of the screen, but it will not move. Will not activate arrow. Will not change quests being tracked. I simply rolled back to the previous version and It works fine.

**Comment by Dyaxler** [comment] 2016-03-25 15:48
Found the bug! So sorry guys. In the "boldColors" code on the side of "false" I forgot to apply the new button widths and each button width was being set to (1) when it should have been set to (250) pixels. Yikes!

I've committed the fix to GitHub and updated the Hotfix release notes and the v2.63 zip file.

Should work now.

**Comment by vendethiel** [comment] 2016-03-25 15:53
thanks :D!

**Comment by Heishe** [comment] 2016-03-25 16:21
Ty for fast fix

**Comment by raichuuuu** [comment] 2016-03-25 16:56
<3!

**Comment by Dyaxler** [comment] 2016-03-25 19:00
You're welcome. Thank you for confirming. :)

**Closed by Dyaxler** 2016-03-25 19:00 UTC
Labels: bug, question
