### ISSUE TITLE
Error when trying reset questie

### ISSUE THREAD

**Issue by SegoItCh** [AeroScripts/QuestieDev#2144] opened 2020-07-05 21:30 UTC
Date: 2020-07-06 00:28:47
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Questie\Database\QuestieDB.lua line 337:
   attempt to index field 'hidden' (a nil value)
Debug:
   Questie\Database\QuestieDB.lua:337: IsDoable()
   ...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:1355:
      ...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:1336
   ..\SharedXML\C_TimerAugment.lua:16:
      ..\SharedXML\C_TimerAugment.lua:14
Locals:
self = <table> {
 questCompilerOrder = <table> {
 }
 FactionGroup = "Alliance"
 questDataOverrides = <table> {
 }
 itemDataOverrides = <table> {
 }
 IsPreQuestGroupFulfilled = <function> defined @Interface\AddOns\Questie\Database\QuestieDB.lua:279
 questKeys = <table> {
 }
 QueryQuest = <function> defined @Interface\AddOns\Questie\Database\compiler.lua:885
 QueryQuestSingle = <function> defined @Interface\AddOns\Questie\Database\compiler.lua:859
 QueryItem = <function> defined @Interface\AddOns\Questie\Database\compiler.lua:885
 QuestPointers = <table> {
 }
 IsRepeatable = <function> defined @Interface\AddOns\Questie\Database\QuestieDB.lua:231
 IsExclusiveQuestInQuestLogOrComplete = <function> defined @Interface\AddOns\Questie\Database\QuestieDB.lua:240
 objectDataOverrides = <table> {
 }
 _npcAdapterQueryOrder = <table> {
 }
 QueryItemSingle = <function> defined @Interface\AddOns\Questie\Database\compiler.lua:859
 NPCPointers = <table> {
 }
 QueryObjectSingle = <function> defined @Interface\AddOns\Questie\Database\compiler.lua:859
 IsActiveEventQuest = <function> defined @Interface\AddOns\Questie\Database\QuestieDB.lua:236
 IsDungeonQuest = <function> defined @Interface\AddOns\Questie\Database\QuestieDB.lua:185
 ObjectPointers = <table> {
 }
 IsComplete = <function> defined @Interface\AddOns\Questie\Database\QuestieDB.lua:215
 QueryObject = <function> defined @Interface\AddOns\Questie\Database\compiler.lua:885
 ItemPointers = <table> {
 }
 npcCompilerTypes = <table> {
 }
 Initialize = <function> defined @Interface\AddOns\Questie\Database\QuestieDB.lua:65
 IsParentQuestActive = <function> defined @Interface\AddOns\Questie\Database\QuestieDB.lua:269
 itemCompilerOrder = <table> {
 }
 objectKeys = <table> {
 }
 questCompilerTypes = <table> {
 }
 itemCompilerTypes = <table> {
 }
 npcKeys = <table> {
 }
 IsLevelRequirementsFulfilled = <function> defined @Interface\AddOns\Questie\Database\QuestieDB.lua:249
 npcCompilerOrder = <table> {
 }
 IsPvPQuest = <function> defined @Interface\AddOns\Questie\Database\QuestieDB.lua:195
 QueryNPC = <function> defined @Interface\AddOns\Questie\Database\compiler.lua:885
 IsPreQuestSingleFulfilled = <function> defined @Interface\AddOns\Questie\Database\QuestieDB.lua:306
 private = <table> {
 }
 GetCreatureLevels = <function> defined @Interface\AddOns\Questie\Database\QuestieDB.lua:785
 GetQuestsByZoneId = <function> defined @Interface\AddOns\Questie\Database\QuestieDB.lua:879
 itemKeys = <table> {
 }
 IsDoable = <function> defined @Interface\AddOns\Questie\Database\QuestieDB.lua:330
 _objectAdapterQueryOrder = <table> {
 }
 GetQuestTagInfo = <function> defined @Interface\AddOns\Questie\Database\QuestieDB.lua:202
 objectCompilerOrder = <table> {
 }
 objectCompilerTypes = <table> {
 }
 GetNPC = <function> defined @Interface\AddOns\Questie\Database\QuestieDB.lua:821
 npcDataOverrides = <table> {
 }
 _questAdapterQueryOrder = <table> {
 }
 GetObject = <function> defined @Interface\AddOns\Questie\Database\QuestieDB.lua:96
 QueryNPCSingle = <function> defined @Interface\AddOns\Questie\Database\compiler.lua:859
 GetColoredQuestName = <function> defined @Interface\AddOns\Questie\Database\QuestieDB.lua:174
 _itemAdapterQueryOrder = <table> {
 }
 IsRaidQuest = <function> defined @Interface\AddOns\Questie\Database\QuestieDB.lua:190
 GetItem = <function> defined @Interface\AddOns\Questie\Database\QuestieDB.lua:123
 GetQuest = <function> defined @Interface\AddOns\Questie\Database\QuestieDB.lua:426
}
questId = 2
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'hidden' (a nil value)"
QuestieCorrections = <table> {
 private = <table> {
 }
 questItemBlacklist = <table> {
 }
 hiddenQuests = <table> {
 }
 Initialize = <function> defined @Interface\AddOns\Questie\Database\Corrections\QuestieCorrections.lua:37
}
QuestieDB 
AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  ACP, v3.5.7 
  AllyRoute, v1.1
  AnnoyingPopupRemover, vv9.0-release
  AtlasLootClassic, vv1.5.1
  AtlasLootClassicData, vv1.5.1
  AtlasLootClassicDungeonsAndRaids, vv1.5.1
  AucAdvanced, v8.2.6471 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6497 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6499 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6503 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6500 (SwimmingSeadragon)
  AucStatSimple, v8.2.6501 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6502 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6504 (SwimmingSeadragon)
  AuctionDB, vv1.02.01
  BagBrother, v
  Bagnon, v8.3.5
  BeanCounter, v8.2.6505 (SwimmingSeadragon)
  BetterVendorPrice, vv1.13.04
  BuffOwner, v1.1
  CharacterStatsClassic, v3.5.4
  Chinchilla, vv2.10.1
  ClassicAuraDurations, v1.13.58
  Dejunk, v8.3.4
  DungeonMaps, v0.1c
  eAlignClassic, vClassic
  Enchantrix, v8.2.6506 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6507 (SwimmingSeadragon)
  FarmHud, v8.3-6-classic-release
  FishingBuddy, v0.7.3 Beta 5
  FiveSecondRule, v1.21
  Fizzle, v80300-1
  GatherMate2, v1.45.5
  GigaAutoResourcesTracker, v1.1.0
  Gnosis, vr215
  Grail, v110
  GrailNPCsclassic, v27178
  GrailNPCsclassicenUS, v33302
  GrailQuestsclassic, v27178
  GrailQuestsclassicenUS, v33302
  GrailReputationsclassic, v007
  HandyNotes, vv1.5.10
  HandyNotesNPCsClassic, v1.23
  HandyNotesWitheredChests, v1.2
  Immersion, v1.2.3
  InFlight, v1.13.005
  InFlightLoad, v1.13.005
  Informant, v8.2.6508 (SwimmingSeadragon)
  InstanceCounter, v1.14.2.1
  KuiMedia, v
  KuiNameplates, v
  KuiNameplatesCore, v
  LeatrixMaps, v1.13.68
  LeatrixPlus, v1.13.68
  LetMeCast, v1.3
  MobInfo2Classic, v11302.04
  Molinari, v80300.66-Release
  MonkeySpeed, vv3.4.0
  Myslot, vv5.3.4-classic
  NauticusClassic, v1.3.1
  NovaWorldBuffs, v1.66
  OmniCC, v8.3.5
  OPie, vAncient Walnut 6
  Parrot, vv2.1-classic3
  Pawn, v2.3.28
  PLG, v1.3
  Prat30, v3.8.25
  Prat30Libraries, v
  Questie, v6.0.0
  RangeColors, v2.5
  ReagentRecipeClassic, v1.6.5
  Restocker, v6.2
  ShadowedUnitFrames, vv4.2.3-Classic
  SlideBar, v8.2.6509 (SwimmingSeadragon)
  SLoTe, v
  SpeedyAutoLoot, v2.0.27
  statweightsclassic, v
  Stubby, v8.2.6510 (SwimmingSeadragon)
  TellMeWhen, v8.7.5
  TomTom, vv11304-1.1.2
  VendorPrice, v1.3.5
  WeakAuras, v2.17.8
  WhatsTraining, v1.8.7
  Wholly, v079
  WideQuestLog, v
  BlizRuntimeLib_enUS v1.13.4.11304 <none>
  (ck=985)

Date: 2020-07-06 00:28:47
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Questie\Database\QuestieDB.lua line 337:
   attempt to index field 'hidden' (a nil value)
Debug:
   Questie\Database\QuestieDB.lua:337: IsDoable()
   ...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:1355:
      ...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:1336
   ..\SharedXML\C_TimerAugment.lua:16:
      ..\SharedXML\C_TimerAugment.lua:14
Locals:
self = <table> {
 questCompilerOrder = <table> {
 }
 FactionGroup = "Alliance"
 questDataOverrides = <table> {
 }
 itemDataOverrides = <table> {
 }
 IsPreQuestGroupFulfilled = <function> defined @Interface\AddOns\Questie\Database\QuestieDB.lua:279
 questKeys = <table> {
 }
 QueryQuest = <function> defined @Interface\AddOns\Questie\Database\compiler.lua:885
 QueryQuestSingle = <function> defined @Interface\AddOns\Questie\Database\compiler.lua:859
 QueryItem = <function> defined @Interface\AddOns\Questie\Database\compiler.lua:885
 QuestPointers = <table> {
 }
 IsRepeatable = <function> defined @Interface\AddOns\Questie\Database\QuestieDB.lua:231
 IsExclusiveQuestInQuestLogOrComplete = <function> defined @Interface\AddOns\Questie\Database\QuestieDB.lua:240
 objectDataOverrides = <table> {
 }
 _npcAdapterQueryOrder = <table> {
 }
 QueryItemSingle = <function> defined @Interface\AddOns\Questie\Database\compiler.lua:859
 NPCPointers = <table> {
 }
 QueryObjectSingle = <function> defined @Interface\AddOns\Questie\Database\compiler.lua:859
 IsActiveEventQuest = <function> defined @Interface\AddOns\Questie\Database\QuestieDB.lua:236
 IsDungeonQuest = <function> defined @Interface\AddOns\Questie\Database\QuestieDB.lua:185
 ObjectPointers = <table> {
 }
 IsComplete = <function> defined @Interface\AddOns\Questie\Database\QuestieDB.lua:215
 QueryObject = <function> defined @Interface\AddOns\Questie\Database\compiler.lua:885
 ItemPointers = <table> {
 }
 npcCompilerTypes = <table> {
 }
 Initialize = <function> defined @Interface\AddOns\Questie\Database\QuestieDB.lua:65
 IsParentQuestActive = <function> defined @Interface\AddOns\Questie\Database\QuestieDB.lua:269
 itemCompilerOrder = <table> {
 }
 objectKeys = <table> {
 }
 questCompilerTypes = <table> {
 }
 itemCompilerTypes = <table> {
 }
 npcKeys = <table> {
 }
 IsLevelRequirementsFulfilled = <function> defined @Interface\AddOns\Questie\Database\QuestieDB.lua:249
 npcCompilerOrder = <table> {
 }
 IsPvPQuest = <function> defined @Interface\AddOns\Questie\Database\QuestieDB.lua:195
 QueryNPC = <function> defined @Interface\AddOns\Questie\Database\compiler.lua:885
 IsPreQuestSingleFulfilled = <function> defined @Interface\AddOns\Questie\Database\QuestieDB.lua:306
 private = <table> {
 }
 GetCreatureLevels = <function> defined @Interface\AddOns\Questie\Database\QuestieDB.lua:785
 GetQuestsByZoneId = <function> defined @Interface\AddOns\Questie\Database\QuestieDB.lua:879
 itemKeys = <table> {
 }
 IsDoable = <function> defined @Interface\AddOns\Questie\Database\QuestieDB.lua:330
 _objectAdapterQueryOrder = <table> {
 }
 GetQuestTagInfo = <function> defined @Interface\AddOns\Questie\Database\QuestieDB.lua:202
 objectCompilerOrder = <table> {
 }
 objectCompilerTypes = <table> {
 }
 GetNPC = <function> defined @Interface\AddOns\Questie\Database\QuestieDB.lua:821
 npcDataOverrides = <table> {
 }
 _questAdapterQueryOrder = <table> {
 }
 GetObject = <function> defined @Interface\AddOns\Questie\Database\QuestieDB.lua:96
 QueryNPCSingle = <function> defined @Interface\AddOns\Questie\Database\compiler.lua:859
 GetColoredQuestName = <function> defined @Interface\AddOns\Questie\Database\QuestieDB.lua:174
 _itemAdapterQueryOrder = <table> {
 }
 IsRaidQuest = <function> defined @Interface\AddOns\Questie\Database\QuestieDB.lua:190
 GetItem = <function> defined @Interface\AddOns\Questie\Database\QuestieDB.lua:123
 GetQuest = <function> defined @Interface\AddOns\Questie\Database\QuestieDB.lua:426
}
questId = 2
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'hidden' (a nil value)"
QuestieCorrections = <table> {
 private = <table> {
 }
 questItemBlacklist = <table> {
 }
 hiddenQuests = <table> {
 }
 Initialize = <function> defined @Interface\AddOns\Questie\Database\Corrections\QuestieCorrections.lua:37
}
QuestieDB 
AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  ACP, v3.5.7 
  AllyRoute, v1.1
  AnnoyingPopupRemover, vv9.0-release
  AtlasLootClassic, vv1.5.1
  AtlasLootClassicData, vv1.5.1
  AtlasLootClassicDungeonsAndRaids, vv1.5.1
  AucAdvanced, v8.2.6471 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6497 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6499 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6503 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6500 (SwimmingSeadragon)
  AucStatSimple, v8.2.6501 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6502 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6504 (SwimmingSeadragon)
  AuctionDB, vv1.02.01
  BagBrother, v
  Bagnon, v8.3.5
  BeanCounter, v8.2.6505 (SwimmingSeadragon)
  BetterVendorPrice, vv1.13.04
  BuffOwner, v1.1
  CharacterStatsClassic, v3.5.4
  Chinchilla, vv2.10.1
  ClassicAuraDurations, v1.13.58
  Dejunk, v8.3.4
  DungeonMaps, v0.1c
  eAlignClassic, vClassic
  Enchantrix, v8.2.6506 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6507 (SwimmingSeadragon)
  FarmHud, v8.3-6-classic-release
  FishingBuddy, v0.7.3 Beta 5
  FiveSecondRule, v1.21
  Fizzle, v80300-1
  GatherMate2, v1.45.5
  GigaAutoResourcesTracker, v1.1.0
  Gnosis, vr215
  Grail, v110
  GrailNPCsclassic, v27178
  GrailNPCsclassicenUS, v33302
  GrailQuestsclassic, v27178
  GrailQuestsclassicenUS, v33302
  GrailReputationsclassic, v007
  HandyNotes, vv1.5.10
  HandyNotesNPCsClassic, v1.23
  HandyNotesWitheredChests, v1.2
  Immersion, v1.2.3
  InFlight, v1.13.005
  InFlightLoad, v1.13.005
  Informant, v8.2.6508 (SwimmingSeadragon)
  InstanceCounter, v1.14.2.1
  KuiMedia, v
  KuiNameplates, v
  KuiNameplatesCore, v
  LeatrixMaps, v1.13.68
  LeatrixPlus, v1.13.68
  LetMeCast, v1.3
  MobInfo2Classic, v11302.04
  Molinari, v80300.66-Release
  MonkeySpeed, vv3.4.0
  Myslot, vv5.3.4-classic
  NauticusClassic, v1.3.1
  NovaWorldBuffs, v1.66
  OmniCC, v8.3.5
  OPie, vAncient Walnut 6
  Parrot, vv2.1-classic3
  Pawn, v2.3.28
  PLG, v1.3
  Prat30, v3.8.25
  Prat30Libraries, v
  Questie, v6.0.0
  RangeColors, v2.5
  ReagentRecipeClassic, v1.6.5
  Restocker, v6.2
  ShadowedUnitFrames, vv4.2.3-Classic
  SlideBar, v8.2.6509 (SwimmingSeadragon)
  SLoTe, v
  SpeedyAutoLoot, v2.0.27
  statweightsclassic, v
  Stubby, v8.2.6510 (SwimmingSeadragon)
  TellMeWhen, v8.7.5
  TomTom, vv11304-1.1.2
  VendorPrice, v1.3.5
  WeakAuras, v2.17.8
  WhatsTraining, v1.8.7
  Wholly, v079
  WideQuestLog, v
  BlizRuntimeLib_enUS v1.13.4.11304 <none>
  (ck=985)

**Comment by drejjmit** [comment] 2020-07-07 08:38
Try ``/run Questie.db.char.hidden = {}`` 
then ``/reload``

**Comment by Dyaxler** [comment] 2020-07-12 17:19
@SegoItCh Is this still an issue in the latest release? If not then please close this issue.

**Comment by BreakBB** [comment] 2020-07-24 19:19
@SegoItCh Any news on this?

**Comment by AeroScripts** [comment] 2020-08-19 23:33
As mentioned above https://github.com/AeroScripts/QuestieDev/issues/2144#issuecomment-654693570 this is fixed if you run these chat commands. It's a rare issue caused by he config migration that was added in 6.0, theres not much we can do

**Closed by AeroScripts** 2020-08-19 23:33 UTC
Labels: bug, need more info
