### ISSUE TITLE
Lag spikes on version 5.1.0

### ISSUE THREAD

**Issue by m33ts4k0z** [AeroScripts/QuestieDev#1493] opened 2019-11-06 01:07 UTC
Hello and thanks for this great addon.

Version 5.1.0 of classic is introducing some periodic lagspikes (every 5-6 seconds) that cause the game to freeze for some milliseconds. The game is working fine with version 5.0.1

**Comment by BreakBB** [comment] 2019-11-06 08:29
@m33ts4k0z Can you try to disable all other addons and see if the issue still exists?

**Comment by m33ts4k0z** [comment] 2019-11-06 12:33
Yes disabling all other addons and leaving only questie, still shows this issue on version 5.1.0.
5.0.1 works fine with or without other addons.

**Comment by Maczuga** [comment] 2019-11-07 12:03
I can confirm that. 

"Enable Minimap Icons" sometimes helps, but also does not always work - and when it does not work - lag spikes appears.

For me also since the 5.1.0 release - minimap icons does not work well with MBB (MinimapButtonBag) addon, whick worked fine before (see screen below).

![image](https://user-images.githubusercontent.com/544349/68387592-f1974e00-015e-11ea-8947-eee60c41b912.png)

**Comment by BreakBB** [comment] 2019-11-10 22:11
@Maczuga I can see in your screenshot you're using the MinimapButtonBag addon. That caused problems in the latest version but has been fixed with v5.2.0. Please update and check again.

@m33ts4k0z Same for your update and report if this issue is resolved.

**Comment by Maczuga** [comment] 2019-11-11 17:07
@BreakBB long spikes are gone, MBB is fixed too, but...

Now there are small, but noticeable 0.2sec spikes for me every 3-4 seconds. Tested in Tarren Mill.
List of active quests (screenshot + Steelsnap):
![image](https://user-images.githubusercontent.com/544349/68606093-f71dcc80-04ad-11ea-9b25-e463135fb78c.png)

Reverting again to 5.0.1 for now :)

**Comment by BreakBB** [comment] 2019-11-11 17:22
Hmmm... @Maczuga And you've tested it with every other addons disabled as well? And your hardware (especially CPU) isn't some old stuff?

**Comment by BreakBB** [comment] 2019-11-11 17:25
Oh and you could try to increase the cluster size:

![image](https://user-images.githubusercontent.com/33514570/68607316-a8bdfd00-04b0-11ea-8a55-6b44c60ab327.png)

**Comment by Maczuga** [comment] 2019-11-11 17:41
> Hmmm... @Maczuga And you've tested it with every other addons disabled as well? And your hardware (especially CPU) isn't some old stuff?

i7-6700K, not that old stuff :) Tried with addons off, tried with addons on and Questie off - same result. Will check the cluster size tommorow and let you know.

**Comment by BreakBB** [comment] 2019-11-11 17:42
You tested this with Questie off and still got the lag spikes? 🤔

**Comment by Maczuga** [comment] 2019-11-11 17:51
Nah, all addons off = addons on + questie off - which works fine.

**Comment by Gregz3** [comment] 2019-11-12 11:26
Still seeing performance issues with Questie 5.2.0

Lag spikes and frame judder are noticeable and constant. It's been presumed by some users that Questie is polling the surrounding area and creating frame delays in the process.

Disabling Questie creates an immediate performance improvement. Frames are smooth and no judder. This is especially apparent if you use max zoom and are moving on a fast mount. You'll notice mouse lag and frame judder in the millisecond range. Disabling Questie fixes it.

Please prioritize this bug. It has been a consistent problem throughout all previous versions.

**Comment by BreakBB** [comment] 2019-11-12 11:38
@Gregz3 It isn't easy for us to reproduce this issue. I myself don't experience any lags and neither do I gain performance improvements with Questie disabled.

We're not polling the surrounding area, but updating the minimap icons whenever a relevant event (like player level up) happens we re calculate the available quests. Moreover we hide/unhide minimap icons when you change the zone so you only see the ones for the current zone.
Obviously whenever a quest is accepted we add the objective markers to the map/minimap.

I have to ask you as well: Do you experience these issues with just Questie enabled as well? 

If yes, you could try two things:

1. Increase the icon cluster amount (which reduces the amount of individual icons drawn by proximity to each other)
![image](https://user-images.githubusercontent.com/33514570/68668536-b1621200-0548-11ea-9c3b-4d863733ab6f.png)

2. Set an icon limit in the Advanced tab:
![image](https://user-images.githubusercontent.com/33514570/68668514-a27b5f80-0548-11ea-95c5-c1d6708f83db.png)

**Comment by BreakBB** [comment] 2019-11-12 12:06
Another question is: Do you experience these issues just when you're moving or if you're standing still as well?

**Comment by Maczuga** [comment] 2019-11-12 13:00
@BreakBB just checked on another character (without changing any settings, but have different quests). No spikes here with Questie 5.2, so this is most likely related to one of the quests I listed previously. 

This is my quest list on another character without spikes:
![image](https://user-images.githubusercontent.com/544349/68673540-43bbe300-0554-11ea-88e2-b4be934f832c.png)

Might be also due to lower amount of quests than here: 
https://github.com/AeroScripts/QuestieDev/issues/1493#issuecomment-552529540

Changing any value from here does not change anything: https://github.com/AeroScripts/QuestieDev/issues/1493#issuecomment-552857560

**Comment by BreakBB** [comment] 2019-11-12 13:02
@Maczuga I will soon reach Un'Goro which should be the best location to test this issue. In the meantime I will continue to refactor parts of Questie and see if I can find anything which could possibly cause such performance problems.

**Comment by BreakBB** [comment] 2019-11-13 12:30
@m33ts4k0z @Maczuga @Gregz3 We've investigated this a bit more since some of us were able to "reproduce" it (having like ~10 FPS drops).

It would be great if you could test some WIP changes and report if your issue is becoming better:

1. Update to Questie v5.2.1 and then
2. Replace the `QuestieMap.lua` file with the one from the ZIP:

[QuestieMap.zip](https://github.com/AeroScripts/QuestieDev/files/3841076/QuestieMap.zip)

It goes into `Questie/Modules/Map` replacing the existing one.

**Comment by Muehe** [comment] 2019-11-13 18:25
The change by BreakBB has now been committed plus a few additional mitigations too, please use the following pre-release for testing:


[Questie-v5.2.1_22-f46c487.zip](https://github.com/AeroScripts/QuestieDev/files/3842802/Questie-v5.2.1_22-f46c487.zip)

**Comment by Muehe** [comment] 2019-11-14 00:24
Small update, we identified the offending commit as 28fbd4c3052ffaed80f9553dad9a2ea62d7cf0dc

Performance with that commit:
![ss1](https://cdn.discordapp.com/attachments/263040777658171392/644318842419675167/unknown.png)

Performance before that commit:
![ss2](https://cdn.discordapp.com/attachments/263040777658171392/644319575810506792/unknown.png)

Unfortunately the fix is not as easy as reverting that commit, we will look into this further.

**Comment by m33ts4k0z** [comment] 2019-11-17 00:27
Guys I just came back to report that the issue for me was the minimap button frame addon. I disabled it and no more minispikes.

**Comment by AeroScripts** [comment] 2019-11-19 10:14
give the latest release a try https://github.com/AeroScripts/QuestieDev/releases it has @Logonz 's fix

**Comment by solariz** [comment] 2019-11-21 19:23
Hey, have the same issue - defenitly questie related. When I disable Questie the game runs in 144 FPS continuous. With Questie enabled every 3s the Framerate drops to 70-100 FPS, this is so annoying had to turn it off.

Tried the v5.2.3 same. 

Changing Clusteramount and Icon Amount just reduce the amount of FPS drop but not fix the problem. If I set to cluster 300 and max 10 icons I still have about 10-20 FPS drop every 3 sec.

**Comment by BreakBB** [comment] 2019-11-21 19:32
@solariz You tried it with every other addon disabled and just Questie active (not the other way around)?

**Comment by solariz** [comment] 2019-11-21 19:41
So, I went through it again. On a new Lvl 1 char:
 

- only questie enabled: no FPS drops
- addons enabled: FPS drops
- addons enabled but questie disabled: no drops

So I went through all of them and found two which causing the issue when run together with questie.

- Gatherer Light
- wow-pro guide

as soon as one of those is active beside questie I have the drop, no matter which one of those both.

So must be something in relation to the minimap because all of them drawing Icons.

**Comment by BreakBB** [comment] 2019-11-22 09:40
@solariz Thanks for taking your time and investigate this! Yeah minimap is the most likely the source for FPS problems since the icons on it have to be updated all the time.
With the last two updates we were able to improve our performance on those by **A LOT**. Meaning on a full Un'Goro map (every quest you can grab in there once you arrived) on my setup the FPS went from ~80 to ~110 in a first step. Then with the second update to ~135.

I currently don't have the time to investigate deeply into those two addons and their code, but you should contact their developers as well. Maybe they're using the minimap API wrong (like we did before).

**Comment by BreakBB** [comment] 2020-03-18 12:21
Closing this issue because our time is limited and the performance has already been improved in the latest releases.

If something severe comes up again feel free to open up a new issue.

**Closed by BreakBB** 2020-03-18 12:21 UTC
Labels: bug, map
