### ISSUE TITLE
Corpse Arrow in Battlegrounds is Broken

### ISSUE THREAD

**Issue by ThiconZ** [AeroScripts/QuestieDev#360] opened 2017-01-20 00:11 UTC
When dead in a Battleground, the Corpse arrow will spam flash and always say "19 yards" and 6 seconds away from the corpse. The arrow should just be disabled in Battlegrounds as you really never go to your corpse to revive anyways.

**Comment by Dyaxler** [comment] 2017-01-20 00:35
Ahhh interesting. I never thought about that. Battlegrounds is the only "instance" based zone where you aren't ejected from it when you die. If you're running a dungeon and you die and release you're ejected to the nearest grave yard outside the instance. Your "corpse marker" is the dungeon entrance. So yeah, I'll have to add a special check for Battlegrounds to keep that arrow off.

**Comment by Dyaxler** [comment] 2017-01-20 01:25
I haven't had time to login to test it. Maybe someone can test it for me. I have to go to one of my kids concerts right now. Change the attachment from *.txt to *.lua and drop it in your ../!Questie/Modules directory.

[QuestieArrow.txt](https://github.com/AeroScripts/QuestieDev/files/718207/QuestieArrow.txt)

**Comment by Dyaxler** [comment] 2017-01-20 06:12
My previous code fix had some bugs in it pertaining to certain scenarios. Correctly tested code is in and it should detect if a player is in a BG. It's a widely used block of code in vanilla for determining the status of a player inside, outside(queued), which BG etc. I only key'd in on "status = active" which means a player is physically in a BG and not simply queued up and doing some quests outside. So... as long as the BGACTIVE flag returns false (outside) then the arrow will show. I've tested everything outside a BG but haven't checked to see if it will work in a BG. No reason why it shouldn't. It's not throwing any errors outside.

https://github.com/AeroScripts/QuestieDev/commit/b408bacb2a78e5f0f3a6479588f0d8d5ddc2ea1e

**Comment by Dyaxler** [comment] 2017-01-20 21:38
New release with fix:
https://github.com/AeroScripts/QuestieDev/releases/latest

**Comment by ThiconZ** [comment] 2017-01-20 22:52
Retested with version 3.67, corpse arrow no longer displays while dead in battlegrounds regardless of enabled/disabled setting for it.

**Comment by Dyaxler** [comment] 2017-01-20 22:55
Thank you for the confirmation! :)

**Comment by ThiconZ** [comment] 2017-01-20 23:08
@Dyaxler it seems I have spoken too soon. After multiple deaths some form of corruption appears and the text "My Dead Corpse" shows up while dead and in place of the arrow is an image that looks like a tiny white box tiled across the area that should contain the arrow. There did not appear to be a distance of estimated time section displayed.

I attempted to screenshot the issue but the screenshot was unable to capture the corrupted image for some reason. If I do manage to get a screenshot with it, I'll reply here with it.

**Comment by Dyaxler** [comment] 2017-01-20 23:11
Hmmm... that was happening with me too when I disabled the CorpseArrow while dead outside an instance/BG but I inserted some redundant checks elsewhere in another OnUpdate function to make sure it stays off. I'll have to go back over my Logic and check the code again.

**Comment by Dyaxler** [comment] 2017-01-20 23:17
I should also say that this might also be related to your issues with dying in Stockades and your arrow not indicting distance. I'd be willing to bet they are related to another AddOn you're running. Any chance I can see a dump of your:

> ..\WTF\Account\%ACCOUNTNAME%\%SERVER%\%CHARACTER%\AddOns.txt

**Comment by ThiconZ** [comment] 2017-01-20 23:49
It could possibly have something to do with having your Insignia taken from you in a Battleground once killed. It doesn't seem like many people do it which would explain why it doesn't happen often.

AddOns.txt does not appear to be listing all the addons it should but:
QuestHelper: disabled
EQCompare: disabled
FlightTime: enabled
!Questie: enabled
Auctioneer: enabled
AuctionFilterPlus: enabled
Atlas: enabled
AtlasLoot: enabled
AtlasQuest: enabled

**Comment by Dyaxler** [comment] 2017-01-21 00:00
WEIRD. Might be some kind of timing issue where one function is firing much quicker than another compared to my computer. I think maybe your computer is faster than mine. :D

**Comment by ThiconZ** [comment] 2017-01-21 00:03
Always possible, I capped the game to 60FPS and allotted 500mb to scripts if that's of any help.

**Comment by ThiconZ** [comment] 2017-01-21 00:22
Found an easy way to force reproduce this. Once dead in a battleground, just open and close the map. It'll create the corrupted arrow image.

![image](https://cloud.githubusercontent.com/assets/6924950/22169831/4d1986b0-df45-11e6-86a5-013670fb1b7f.png)

**Comment by Dyaxler** [comment] 2017-01-21 00:26
Worldmap ?!?!?

Bah! OK, that gives me an idea of what is firing that might be causing this. You aren't using Metamap or Cartographer. I'm using Cartographer so I'll disable mine and run over my functions again.

Is your Worldmap full screen when you open it?

**Comment by ThiconZ** [comment] 2017-01-21 00:35
@Dyaxler like I said about the AddOns.txt file, it isn't listing all my Addons. I am using Cartographer.
Here is a more complete addons list:
![image](https://cloud.githubusercontent.com/assets/6924950/22170070/965aa488-df47-11e6-8614-26ba69bf784f.png)

**Comment by ThiconZ** [comment] 2017-01-21 01:18
Looked through the QuestieArrow file a bit and it seems bgactive will never be true due to bgstatus == active instead of bgstatus == "active" and since you loop through all queues, 3, if any were to be false which if the user is in a bg 1 will be true and 2 will be false, it'll result in it being false again. The following code block should make it be true whenever the player is in a bg:

```lua
    local bgactive = false
    for i=1, MAX_BATTLEFIELD_QUEUES do
        bgstatus = GetBattlefieldStatus(i);
        if (bgstatus == "active") then
            bgactive = true
        end
    end
```

**Comment by Dyaxler** [comment] 2017-01-21 01:24
Should? Did you test it? :D Otherwise, nice catch! Small typo as I was in a hurry to finish writing the function. That is supposed to be a string value surrounded by quotes. Doh!

Actually it would be better to do it like this to avoid any nil errors.

```
    local bgactive = false
    for i=1, MAX_BATTLEFIELD_QUEUES do
        bgstatus = GetBattlefieldStatus(i);
        if (bgstatus and bgstatus == "active") then
            bgactive = true
        end
    end
```

**Comment by Dyaxler** [comment] 2017-01-21 01:26
Oh and don't forget to change the "backup function" in Questie.lua too... line 488'ish or there about.

**Comment by ThiconZ** [comment] 2017-01-21 01:51
I ran the follow questie command in a bg while dead with the following screenshot output (top was cutoff due to amount of lines) to make sure it worked correctly:
```lua
["bgs"] = function()
        local bgactive = false;

        DEFAULT_CHAT_FRAME:AddMessage("BGS:"..MAX_BATTLEFIELD_QUEUES, 1, 1, 1);

        for i=1, MAX_BATTLEFIELD_QUEUES do
            bgstatus = GetBattlefieldStatus(i);

            DEFAULT_CHAT_FRAME:AddMessage(bgstatus, 1, 1, 1);

            if (bgstatus and bgstatus == "active") then
                bgactive = true;
                DEFAULT_CHAT_FRAME:AddMessage("active", 0, 1, 0);
            else
                DEFAULT_CHAT_FRAME:AddMessage("inactive", 1, 0, 0);
            end
        end

        DEFAULT_CHAT_FRAME:AddMessage(tostring(bgactive), 1, 1, 1);

        if UnitIsDeadOrGhost("player") and (bgactive == true) then
            DEFAULT_CHAT_FRAME:AddMessage("DO NOT SHOW ARROW", 1, 1, 1);
        end
    end,
```
![image](https://cloud.githubusercontent.com/assets/6924950/22170904/387b8d0e-df52-11e6-93b8-46e430deb9f4.png)

**Comment by Dyaxler** [comment] 2017-01-21 01:54
NICE. Thank you for testing that. Personally... I hate BG's. Shhhh... don't tell anyone.

**Comment by ThiconZ** [comment] 2017-01-21 02:02
Tested it with one (two if counting the backup function) changes to ensure the arrow is hidden and it works perfect it seems.

```lua
    if UnitIsDeadOrGhost("player") and (bgactive == false) then
        if (QuestieConfig.corpseArrow == true) and (QuestieConfig.arrowEnabled == true) then
            local deadmyx, deadmyy = GetCorpseMapPosition();
            if deadmyx and deadmyy and deadmyx ~= 0 and deadmyy ~= 0 then
                local mycon, myzone, x, y = Astrolabe:GetCurrentPlayerPosition()
                local ddist, xDelta, yDelta = Astrolabe:ComputeDistance(mycont, myzone, X, Y, continent, zone, xNote, yNote)
                local dtitle = "My Dead Corpse"
                local dpoint = {c = mycon, z = myzone, x = deadmyx, y = deadmyy}
                SetCrazyArrow(dpoint, ddist, dtitle);
            end
        end
        if (QuestieConfig.corpseArrow == true) and (QuestieConfig.arrowEnabled == false) then
            local deadmyx, deadmyy = GetCorpseMapPosition();
            if deadmyx and deadmyy and deadmyx ~= 0 and deadmyy ~= 0 then
                local mycon, myzone, x, y = Astrolabe:GetCurrentPlayerPosition()
                local ddist, xDelta, yDelta = Astrolabe:ComputeDistance(mycont, myzone, X, Y, continent, zone, xNote, yNote)
                local dtitle = "My Dead Corpse"
                local dpoint = {c = mycon, z = myzone, x = deadmyx, y = deadmyy}
                SetCrazyArrow(dpoint, ddist, dtitle);
            end
        end
        if (QuestieConfig.arrowEnabled == false) and (QuestieConfig.corpseArrow == false) then
            TomTomCrazyArrow:Hide()
        end
    elseif UnitIsDeadOrGhost("player") and (bgactive == true) then
        TomTomCrazyArrow:Hide()
    end
```

The above is the new code block for dealing with showing the arrow. Only added the last elseif to it.

![image](https://cloud.githubusercontent.com/assets/6924950/22170991/7573281a-df53-11e6-835a-fe1e948d85fe.png)


Since I had hit level 30 people hate me when I join BGs to test this, I get tons of hate whispers telling me to leave and how I bring down the team - even though I still do better in them than most of the team, makes me almost want to hate BG's as well.

**Comment by Muehe** [comment] 2017-01-21 16:11
Is this hotfixed in the current 3.67 release? Because I can not reproduce the error with it.

**Comment by Muehe** [comment] 2017-01-21 16:55
[By the way:](http://wowwiki.wikia.com/wiki/API_GetCorpseMapPosition)

> If both posX and posY are 0, then the player is not dead, the corpse position is unknown, or not valid for the current map.

They are indeed 0 while dead in a BG. I checked.

**Comment by Dyaxler** [comment] 2017-01-21 19:12
This isn't in yet. However the test build I created for ThiconZ attached in the other thread does have the above fixes.

**Comment by Muehe** [comment] 2017-01-21 20:33
That might indicate that this is a server specific issue. I used 3.67 for the battleground tests.

**Comment by Dyaxler** [comment] 2017-01-22 07:27
This has been fixed in the latest release:
https://github.com/AeroScripts/QuestieDev/releases/latest

**Closed by Dyaxler** 2017-01-22 07:27 UTC
Labels: hotfix, test again
