### ISSUE TITLE
"the cliffspring river" missing turnin location

### ISSUE THREAD

**Issue by ssateneth** [AeroScripts/QuestieDev#678] opened 2019-08-29 05:46 UTC
"the cliffspring river" is missing turnin location. quest ID 4762, turns in at Thundris Windweaver (npc id 3649) in auburdine

**Comment by AeroScripts** [comment] 2019-09-01 06:07
This is a duplicate of #673 actually

**Closed by AeroScripts** 2019-09-01 06:07 UTC
Labels: database
