### ISSUE TITLE
Dungeon/Elite labels on quest level/name of available quests on map, like [24D] and [24E].

### ISSUE THREAD

**Issue by mikkelmk** [AeroScripts/QuestieDev#1319] opened 2019-10-14 00:47 UTC
This would be very helpful for judging whether or not a given questgiver is worth walking to :)

![Example](https://user-images.githubusercontent.com/22171260/66724950-7c20b200-ee2c-11e9-8622-a986cea720d8.png)

**Comment by Aloki** [comment] 2019-10-14 00:53
Duplicate of #1272.

**Closed** 2019-10-16 09:30 UTC
Labels: feature request
