### ISSUE TITLE
the treasure of the shen'dralar

### ISSUE THREAD

**Issue by Tehenke** [AeroScripts/QuestieDev#1583] opened 2019-11-23 08:44 UTC
I completed the the treasure of the shen'dralar quest and Questie still show it to pick up and complete it

https://classic.wowhead.com/quest=7877/the-treasure-of-the-shendralar

![1](https://user-images.githubusercontent.com/58104090/69476101-b7bc7d80-0dd5-11ea-8ea5-f43955fe5959.jpg)

v5.2.3

**Comment by drejjmit** [comment] 2019-11-23 09:58
https://classic.wowhead.com/quest=7462/the-treasure-of-the-shendralar
is a dupe of 
https://classic.wowhead.com/quest=7877/the-treasure-of-the-shendralar
I think we should hide 7462. I did this quest and could only complete 7877

**Closed** 2019-11-27 23:06 UTC
Labels: quest issue
