### ISSUE TITLE
lua errors since WoW update - attempt to index field (nil value)

### ISSUE THREAD

**Issue by Djfe** [AeroScripts/QuestieDev#1402] opened 2019-10-23 01:17 UTC
## Bug description
Questie shows 4 lua errors upon starting WoW in Chat since the update from today (patch 1.13.2.32089
so there is something they changed.
I provided screenshots with the code lines

## Screenshots
![](https://i.imgur.com/iIgaK4h.jpg)
![](https://i.imgur.com/uItMEbp.jpg)

## Questie version
5.0.0

**Comment by rbpaiett** [comment] 2019-10-23 03:36
I'm getting the same thing in English for the quest [The Power of Pine].  Apparently Questie isn't set up for any Hallow's End quests.

**Comment by SpareSimian** [comment] 2019-10-23 03:42
Duplicate of issue #1399

**Closed** 2019-10-23 06:20 UTC
Labels: bug
