### ISSUE TITLE
The Blackwood Corrupted

### ISSUE THREAD

**Issue by Morcius08** [AeroScripts/QuestieDev#798] opened 2019-09-04 10:20 UTC
The quest requires the Empty Cleansing Bowl to be filled at the moonwell before leaving Auberdine and heading north to the camps.

**Comment by BreakBB** [comment] 2019-09-04 10:54
Could you explain what is not working? Is the point missing where to fill the bowl?

Moreover what Questie version are you using?

**Comment by BreakBB** [comment] 2019-09-04 16:12
Duplicate of #550

**Closed** 2019-09-06 00:02 UTC
Labels: quest issue
