### ISSUE TITLE
LUA error

### ISSUE THREAD

**Issue by Velinestra** [AeroScripts/QuestieDev#1889] opened 2020-04-23 03:24 UTC
Questie v5.10.1

I was switching between characters on the same server and this LUA error popped up:

Message: ...ce\AddOns\Questie\Modules\Tracker\QuestieTracker.lua:791: 'for' limit must be a number
Time: Wed Apr 22 23:14:22 2020
Count: 1
Stack: ...ce\AddOns\Questie\Modules\Tracker\QuestieTracker.lua:791: 'for' limit must be a number
...ce\AddOns\Questie\Modules\Tracker\QuestieTracker.lua:791: in function <...ce\AddOns\Questie\Modules\Tracker\QuestieTracker.lua:783>
Interface\SharedXML\C_TimerAugment.lua:16: in function <Interface\SharedXML\C_TimerAugment.lua:14>

Locals: (for index) = 1
(for limit) = nil
(for step) = 1
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "'for' limit must be a number"
_QuestieTracker = <table> {
 ItemButtons = <table> {
 }
 StartFadeTicker = <function> defined @Interface\AddOns\Questie\Modules\Tracker\QuestieTracker.lua:781
 baseFrame = <unnamed> {
 }
 CreateActiveQuestsFrame = <function> defined @Interface\AddOns\Questie\Modules\Tracker\QuestieTracker.lua:416
 expandButton = <unnamed> {
 }
 GetNextItemButton = <function> defined @Interface\AddOns\Questie\Modules\Tracker\QuestieTracker.lua:776
 PrintProgressColor = <function> defined @Interface\AddOns\Questie\Modules\Tracker\QuestieTracker.lua:1040
 GetNextLine = <function> defined @Interface\AddOns\Questie\Modules\Tracker\QuestieTracker.lua:769
 FadeTickerDirection = true
 menuFrame = QuestieTrackerMenuFrame {
 }
 OnDragStop = <function> defined @Interface\AddOns\Questie\Modules\Tracker\QuestieTrackerPrivates.lua:38
 LineFrames = <table> {
 }
 FadeTicker = <table> {
 }
 SetSafePoint = <function> defined @Interface\AddOns\Questie\Modules\Tracker\QuestieTracker.lua:308
 activeQuestsFrame = <unnamed> {
 }
 IsFirstRun = true
 OnDragStart = <function> defined @Interface\AddOns\Questie\Modules\Tracker\QuestieTrackerPrivates.lua:14
 FadeTickerValue = 0.060000
}

**Comment by BreakBB** [comment] 2020-04-26 12:48
Duplicate of #1868

**Closed by BreakBB** 2020-04-26 12:48 UTC
Labels: bug
