### ISSUE TITLE
Questie causing game to freeze

### ISSUE THREAD

**Issue by GreenDreams94** [AeroScripts/QuestieDev#1634] opened 2019-12-14 21:12 UTC
I have uninstalled all other mods to make sure that it is Questie making my game freeze. I load into classic then after a few seconds into connecting my game will freeze. Only allowing me to Alt Tab which unfreezes it for a short time and then its back to being frozen. I'm on Questie version v5.3.1

**Comment by Gogo1951** [comment] 2019-12-15 15:44
Hey @GreenDreams94 ,

Can you run the update, then disable all other mods, and see if Questie still causes the problem?

Having trouble reproducing this one, works fine for me. I've got about 50 other mods running along side it. No issues.

If we can narrow it down, we can start looking at what other mods you have running that could be causing a conflict.

Cheers!

**Comment by GreenDreams94** [comment] 2019-12-16 09:23
Hey @Gogo1951 ,
I have no other mods installed, i install questie and it freezes. I disable/uninstall questie and everything works fine.

**Comment by Gogo1951** [comment] 2019-12-17 10:02
Hey @GreenDreams94 ,

I can't reproduce this. I've been using Questie fine, and even when I run it alone without any other addons everything is still fine.

How are you installing Questie? Through Twitch or manual?

**Comment by BreakBB** [comment] 2019-12-17 22:53
@GreenDreams94 Do you have an old/bad computer? Or maybe a full questlog?

**Comment by Gogo1951** [comment] 2019-12-30 15:55
Hey @GreenDreams94 ,

I have tried on 3 machines to reproduce this. If you're still having issues please reach out.

**Comment by Gogo1951** [comment] 2019-12-30 16:36
Hey @GreenDreams94 ,

If it's still freezing, can you turn Questie off, and post a picture of your current quest log so we can check against specific quests?

**Comment by BreakBB** [comment] 2020-01-04 13:11
Closing this because of the lack of information and we can't reproduce this.

**Closed by BreakBB** 2020-01-04 13:11 UTC
Labels: bug, need more info, non-reproducable
