### ISSUE TITLE
Error when entering Deeprun Tram instance from SW

### ISSUE THREAD

**Issue by ClownCake** [AeroScripts/QuestieDev#93] opened 2015-05-12 15:55 UTC
![questiedev](https://cloud.githubusercontent.com/assets/12272011/7591749/dd4ee53a-f8cf-11e4-8e36-5ec8e8b052e0.jpg)

Error: attemt to compare two nil values
AddOn: questietracker.lua
Line:365
Count: Infinite

**Comment by nycter79** [comment] 2015-05-12 16:37
Also pops the same error when entering RFD.. Maybe other instances too.
Error wont dissapear co i have to disable the addon.

(Line 365) Attempt to compare 2 nil values

**Comment by nycter79** [comment] 2015-05-12 17:07
![image](https://cloud.githubusercontent.com/assets/10027713/7593392/13e04b7a-f8da-11e4-9807-56899c72b4e8.png)

Also this when i acquired q from npc.

**Comment by AeroScripts** [comment] 2015-05-13 15:29
Fixed in v2.0.6, sorry about that

**Comment by nycter79** [comment] 2015-05-13 15:32
So can we just start using questie again? Its kinda tough without it :D

**Comment by AeroScripts** [comment] 2015-05-13 15:33
Just noticed the other issuer reported in here, gonna make a quick fix for that too. Post back shortly

**Comment by nycter79** [comment] 2015-05-13 15:37
Awesome :) seems to broke with every q that has no tracking objectives and questie starts to track all qs when acquired after this errors it stops working entirely. Not sure if its just line 107 error.

**Comment by AeroScripts** [comment] 2015-05-13 15:38
Well, give v2.0.7 a try and let me know how it works for you, If  it still has issues with quests that have no objectives let me know, I -thought- that was working.

**Comment by nycter79** [comment] 2015-05-13 15:42
Sure ill Download and test right when i get home.

**Comment by nycter79** [comment] 2015-05-13 18:43
2.0.7 works fine in this case, afaik :)

**Closed** 2015-05-13 21:38 UTC
Labels: bug, Master, Release

**Comment by ClownCake** [comment] 2015-05-13 23:25
Not fixed.

**Comment by ClownCake** [comment] 2015-05-14 11:09
![questie error](https://cloud.githubusercontent.com/assets/12272011/7630807/7df85190-fa3a-11e4-8d0c-11641e9513d1.jpg)

**Comment by ClownCake** [comment] 2015-05-14 11:11
![questie error](https://cloud.githubusercontent.com/assets/12272011/7630826/c25218d0-fa3a-11e4-8af7-fe324193a75b.jpg)

**Comment by nycter79** [comment] 2015-05-15 12:15
I dont know if anyone noticed your last posted error since the issue is marked as closed. Maybe you should create a new issue for that.

**Comment by AeroScripts** [comment] 2015-05-17 05:05
Even though this is closed I'll take a look at that arrow issue. Haven't seen that one before.

**Comment by Schaka** [comment] 2015-05-17 08:01
I fixed that, so this can stay closed
