### ISSUE TITLE
LUA error when reputation changes

### ISSUE THREAD

**Issue by teelolws** [AeroScripts/QuestieDev#2033] opened 2020-06-15 11:57 UTC
...terface\AddOns\Questie\Modules\QuestieReputation.lua:26: attempt to perform arithmetic on a string value

**Comment by teelolws** [comment] 2020-06-15 11:59
Might be something to do with me changing game text language occasionally (to test localization changes on other addons).

**Comment by BreakBB** [comment] 2020-06-15 16:36
Duplicate of #1965 and already fixed :) Will be included in the v6.0.0 update

**Closed by BreakBB** 2020-06-15 16:36 UTC
Labels: bug
