### ISSUE TITLE
active quest tracker

### ISSUE THREAD

**Issue by kageAkudo** [AeroScripts/QuestieDev#1668] opened 2019-12-29 23:57 UTC
## Bug description
when i get a quest with a long text it moves the active quest tracker out of place towards middle of screen. when i remove the quest it does not move back unless i restart the game or turn Questie off and on

## Screenshots
![Screenshot (16)](https://user-images.githubusercontent.com/59347064/71564317-ca218980-2aee-11ea-8d54-e2a646c2c706.png)
![Screenshot (19)](https://user-images.githubusercontent.com/59347064/71564318-cf7ed400-2aee-11ea-8d37-e0f09e6da0d3.png)

## Questie version v5.4.1
<!--

**Comment by Gogo1951** [comment] 2019-12-30 17:44
Seems like a dupe of https://github.com/AeroScripts/QuestieDev/issues/1612

**Comment by BreakBB** [comment] 2020-01-04 14:48
Duplicate of #1612

**Closed by BreakBB** 2020-01-04 14:48 UTC
Labels: bug
