### ISSUE TITLE
Party member list not stored correctly

### ISSUE THREAD

**Issue by silverhawke249** [AeroScripts/QuestieDev#1481] opened 2019-11-02 12:02 UTC
## Bug description
I just found out about the My Journey feature, which lists the members of the party when I completed a particular quest. However, instead of listing all the members, it lists the last member in the party multiple times.

## Screenshots
![image](https://user-images.githubusercontent.com/50395934/68070621-d23da100-fdab-11e9-8d21-bb369af5bb73.png)

## Questie version
Version: 5.0.1 2 e2e80b7

**Comment by BreakBB** [comment] 2019-11-03 09:47
Duplicate of #946

**Closed by BreakBB** 2019-11-03 09:47 UTC
Labels: bug
