### ISSUE TITLE
'for' limit must be a number

### ISSUE THREAD

**Issue by Predatorie** [AeroScripts/QuestieDev#1927] opened 2020-05-06 17:04 UTC
## Bug description
Logged into the game, hovered over the Active Quests list and the error was thrown as shown below. Reloading UI does not stop the error.

I have 20 quests in my active list.

Let me know what other additional information you might need.

## Stack Trace
Message: ...ce\AddOns\Questie\Modules\Tracker\QuestieTracker.lua:791: 'for' limit must be a number
Time: Wed May  6 12:59:50 2020
Count: 1
Stack: ...ce\AddOns\Questie\Modules\Tracker\QuestieTracker.lua:791: 'for' limit must be a number
...ce\AddOns\Questie\Modules\Tracker\QuestieTracker.lua:791: in function <...ce\AddOns\Questie\Modules\Tracker\QuestieTracker.lua:783>
Interface\SharedXML\C_TimerAugment.lua:16: in function <Interface\SharedXML\C_TimerAugment.lua:14>

Locals: (for index) = 1
(for limit) = nil
(for step) = 1
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "'for' limit must be a number"
_QuestieTracker = <table> {
 ItemButtons = <table> {
 }
 StartFadeTicker = <function> defined @Interface\AddOns\Questie\Modules\Tracker\QuestieTracker.lua:781
 baseFrame = <unnamed> {
 }
 CreateActiveQuestsFrame = <function> defined @Interface\AddOns\Questie\Modules\Tracker\QuestieTracker.lua:416
 expandButton = <unnamed> {
 }
 GetNextItemButton = <function> defined @Interface\AddOns\Questie\Modules\Tracker\QuestieTracker.lua:776
 PrintProgressColor = <function> defined @Interface\AddOns\Questie\Modules\Tracker\QuestieTracker.lua:1040
 GetNextLine = <function> defined @Interface\AddOns\Questie\Modules\Tracker\QuestieTracker.lua:769
 FadeTickerDirection = true
 menuFrame = QuestieTrackerMenuFrame {
 }
 OnDragStop = <function> defined @Interface\AddOns\Questie\Modules\Tracker\QuestieTrackerPrivates.lua:38
 LineFrames = <table> {
 }
 FadeTicker = <table> {
 }
 SetSafePoint = <function> defined @Interface\AddOns\Questie\Modules\Tracker\QuestieTracker.lua:308
 activeQuestsFrame = <unnamed> {
 }
 IsFirstRun = true
 OnDragStart = <function> defined @Interface\AddOns\Questie\Modules\Tracker\QuestieTrackerPrivates.lua:14
 FadeTickerValue = 0.060000
}

## Questie version
v5.10.2

**Comment by RealBorlak** [comment] 2020-05-09 21:09
I experience this bug constantly when logging in.
I added a quick check for for a nil value and a notice when it happens.
Just now it popped up 10 times upon logging in with 8 quests active and zero tracked in the UI.

It's the same in line 791 and 807.

**Comment by BreakBB** [comment] 2020-05-10 08:46
Duplicate of #1868

We're targeting this issue for the next release. Unfortunately it is just not that easy to debug.

**Closed by BreakBB** 2020-05-10 08:46 UTC
Labels: bug
