### ISSUE TITLE
2 errors after latest update

### ISSUE THREAD

**Issue by fireboy92k** [AeroScripts/QuestieDev#2406] opened 2020-10-20 00:02 UTC
...rface\AddOns\Questie\Modules\QuestieEventHandler.lua line 116:
Usage: RegisterEvent("eventname", "methodname"): 'methodname' - method 'CHAT_MSG_LOOT' not found on self.
Debug:
[C]: ?
...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:112: RegisterEvent()
...rface\AddOns\Questie\Modules\QuestieEventHandler.lua:116: RegisterAllEvents()
Questie\Questie.lua:157:
Questie\Questie.lua:141
[C]: ?
...ce\AddOns\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:70:
...ce\AddOns\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:65
...ce\AddOns\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:498: InitializeAddon()
...ce\AddOns\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:623:
...ce\AddOns\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:615
Locals:
None
AddOns:
Swatter, v8.2.6377 (SwimmingSeadragon)
ACP, v3.5.7
AdiBags, vv1.9.20-classic
Altoholic, vClassic-v1.13.5-049
AngryAssignments, vv1.13.2c
AskMrRobotClassic, v2
Atlas, vv1.47.04
AtlasClassicWoW, vv1.47.02.11304.00
AtlasLootClassic, vv1.5.6
AtlasLootClassicData, vv1.5.6
AtlasLootClassicDungeonsAndRaids, vv1.5.6
AucAdvanced, v8.2.6430 (SwimmingSeadragon)
AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
AucStatSimple, v8.2.6399 (SwimmingSeadragon)
AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
Auctionator, v8.1.0
BeanCounter, v8.2.6434 (SwimmingSeadragon)
CharacterStatsClassic, v3.6.5
DataStore, vv1.13.013
DataStoreAgenda, vr31
DataStoreAuctions, vv1.13-013
DataStoreCharacters, vv1.13-013
DataStoreContainers, vv1.13-013
DataStoreCrafts, vv1.13-013
DataStoreInventory, vv1.13-013
DataStoreMails, vv1.13-013
DataStoreQuests, vv1.13-013
DataStoreReputations, vv1.13-013
DataStoreTalents, vr62
DBMCore, v1.13.61-2-gfb7404c
DBMDefaultSkin, v
DBMStatusBarTimers, v
Details, v
DetailsStreamer, v
DetailsTinyThreat, v
Enchantrix, v8.2.6428 (SwimmingSeadragon)
EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
GatherMate2, v1.45.5
GoldLCPrio, v1.13.5.16
ItemRack, v
ItemTooltipProfessionIcons, v1.1.6
KeepTheHerbs, v1.2.r12
KillTrack, vv1.13.0
LeatrixMaps, v1.13.81
LeatrixPlus, v1.13.81
MikScrollingBattleText, v5.7.151
MobInfo2Classic, v11302.04
NeatPlates, v1.13.5.15
NeatPlatesAlvara, v5a
NeatPlatesBlizzardPlates, v2.0
NeatPlatesClassicPlates, v
NeatPlatesGraphite, v
NeatPlatesGrey, v
NeatPlatesNeon, v
NeatPlatesQuatre, v
NeatPlatesRenaitre, vv7.0.3
NeatPlatesRoth, v
NeatPlatesSimple, v7.3.0
NeatPlatesSlimHorizontal, v2.2
NeatPlatesSlimVertical, v2.2
NeatPlatesHub, v
NeatPlatesWidgets, v
NovaWorldBuffs, v1.82
OmniCC, v9.0.0
Questie, v6.0.5
SlideBar, v8.2.6375 (SwimmingSeadragon)
Stubby, v8.2.6376 (SwimmingSeadragon)
BlizRuntimeLib_enUS v1.13.5.11305 <none>
(ck=88e)

 

Error 2:

Date: 2020-10-19 19:08:59
ID: 2
Error occured in: Global
Count: 1
Message: ...\Questie\Database\Corrections\QuestieCorrections.lua line 81:
attempt to call method 'Load' (a nil value)
Debug:
...\Questie\Database\Corrections\QuestieCorrections.lua:81: MinimalInit()
...\Questie\Database\Corrections\QuestieCorrections.lua:139: Initialize()
...rface\AddOns\Questie\Modules\QuestieEventHandler.lua:203:
...rface\AddOns\Questie\Modules\QuestieEventHandler.lua:138
[C]: ?
...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:29:
...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25
...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: Fire()
...\AddOns\DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua:120:
...\AddOns\DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua:119
Locals:
None
AddOns:
Swatter, v8.2.6377 (SwimmingSeadragon)
ACP, v3.5.7
AdiBags, vv1.9.20-classic
Altoholic, vClassic-v1.13.5-049
AngryAssignments, vv1.13.2c
AskMrRobotClassic, v2
Atlas, vv1.47.04
AtlasClassicWoW, vv1.47.02.11304.00
AtlasLootClassic, vv1.5.6
AtlasLootClassicData, vv1.5.6
AtlasLootClassicDungeonsAndRaids, vv1.5.6
AucAdvanced, v8.2.6430 (SwimmingSeadragon)
AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
AucStatSimple, v8.2.6399 (SwimmingSeadragon)
AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
Auctionator, v8.1.0
BeanCounter, v8.2.6434 (SwimmingSeadragon)
CharacterStatsClassic, v3.6.5
DataStore, vv1.13.013
DataStoreAgenda, vr31
DataStoreAuctions, vv1.13-013
DataStoreCharacters, vv1.13-013
DataStoreContainers, vv1.13-013
DataStoreCrafts, vv1.13-013
DataStoreInventory, vv1.13-013
DataStoreMails, vv1.13-013
DataStoreQuests, vv1.13-013
DataStoreReputations, vv1.13-013
DataStoreTalents, vr62
DBMCore, v1.13.61-2-gfb7404c
DBMDefaultSkin, v
DBMStatusBarTimers, v
Details, v
DetailsStreamer, v
DetailsTinyThreat, v
Enchantrix, v8.2.6428 (SwimmingSeadragon)
EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
GatherMate2, v1.45.5
GoldLCPrio, v1.13.5.16
Informant, v8.2.6374 (SwimmingSeadragon)
ItemRack, v
ItemTooltipProfessionIcons, v1.1.6
KeepTheHerbs, v1.2.r12
KillTrack, vv1.13.0
LeatrixMaps, v1.13.81
LeatrixPlus, v1.13.81
MikScrollingBattleText, v5.7.151
MobInfo2Classic, v11302.04
NeatPlates, v1.13.5.15
NeatPlatesAlvara, v5a
NeatPlatesBlizzardPlates, v2.0
NeatPlatesClassicPlates, v
NeatPlatesGraphite, v
NeatPlatesGrey, v
NeatPlatesNeon, v
NeatPlatesQuatre, v
NeatPlatesRenaitre, vv7.0.3
NeatPlatesRoth, v
NeatPlatesSimple, v7.3.0
NeatPlatesSlimHorizontal, v2.2
NeatPlatesSlimVertical, v2.2
NeatPlatesHub, v
NeatPlatesWidgets, v
NovaWorldBuffs, v1.82
OmniCC, v9.0.0
Questie, v6.0.5
RepHelperClassic, v1.13.5.1-release
RingMenu, v2.2.1
SaladCthun, v1.01
SlideBar, v8.2.6375 (SwimmingSeadragon)
Stubby, v8.2.6376 (SwimmingSeadragon)
ThreatClassic2, v2.24
TinyTooltip, v8.2.1
TitanClassic, v1.2.4.11305
TitanClassicAmmo, v1.2.4.11305
TitanClassicBag, v1.2.4.11305
TitanClassicClock, v1.2.4.11305
TitanClassicGold, v1.2.4.11305
TitanClassicLocation, v1.2.4.11305
TitanClassicLootType, v1.2.4.11305
TitanClassicPerformance, v1.2.4.11305
TitanClassicRegen, v1.2.4.11305
TitanClassicRepair, v1.2.4.11305
TitanClassicVolume, v1.2.4.11305
TitanClassicXP, v1.2.4.11305
WeakAuras, v3.0.1
WideQuestLog, v
ZPerl, v5.9.9
ZPerlArcaneBar, v
ZPerlParty, v
ZPerlPartyPet, v
ZPerlPlayer, v
ZPerlPlayerBuffs, v
ZPerlPlayerPet, v
ZPerlRaidAdmin, v
ZPerlRaidFrames, v
ZPerlRaidHelper, v
ZPerlRaidPets, v
ZPerlTarget, v
ZPerlTargetTarget, v
BlizRuntimeLib_enUS v1.13.5.11305 <none>
(ck=bef)

**Comment by BreakBB** [comment] 2020-10-20 05:32
Hey @fireboy92k did you restart WoW after updating Questie? Those errors look like Questie can't initalize correctly.

**Comment by fireboy92k** [comment] 2020-10-20 13:30
@BreakBB I swear I did, but this morning after restart not seeing them.  Thanks!

**Comment by BreakBB** [comment] 2020-10-20 13:41
If the issue is resolved and you can't reproduce it, feel free to close the issue @fireboy92k Thanks for the response :+1:

**Closed** 2020-10-20 15:26 UTC
Labels: Type - Defect
