### ISSUE TITLE
Crashes when hovering over quest objectives

### ISSUE THREAD

**Issue by wodim** [AeroScripts/QuestieDev#1729] opened 2020-01-22 21:39 UTC
```
Message: ...ddOns\Questie\Modules\FramePool\QuestieFramePool.lua:548: attempt to index field 'data' (a nil value)
Time: Wed Jan 22 22:36:41 2020
Count: 6
Stack: ...ddOns\Questie\Modules\FramePool\QuestieFramePool.lua:548: attempt to index field 'data' (a nil value)
...ddOns\Questie\Modules\FramePool\QuestieFramePool.lua:548: in function <...ddOns\Questie\Modules\FramePool\QuestieFramePool.lua:516>

Locals: self = QuestieFrame253 {
 0 = <userdata>
 glow = QuestieFrame253Glow {
 }
 BaseOnUpdate = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFrame.lua:196
 FakeUnhide = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFrame.lua:361
 FakeHide = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFrame.lua:345
 texture = <unnamed> {
 }
 BaseOnShow = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFrame.lua:202
 glowLogicTimer = <table> {
 }
 BaseOnHide = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFrame.lua:226
 FadeOut = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFrame.lua:317
 UpdateTexture = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFrame.lua:230
 glowTexture = <unnamed> {
 }
 Unload = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFrame.lua:265
 GlowUpdate = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFrame.lua:178
 FadeIn = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFrame.lua:331
 frameId = 253
}
r = 0.999998
g = 0.999998
b = 0.999998
a = 0.999998
Tooltip = GameTooltip {
 0 = <userdata>
 numMoneyFrames = 1
 SetInboxItem = <function> defined =[C]:-1
 npcOrder = <table> {
 }
 shoppingTooltips = <table> {
 }
 SetMerchantItem = <function> defined =[C]:-1
 SetHyperlink = <function> defined =[C]:-1
 SetTradeSkillItem = <function> defined =[C]:-1
 _owner = QuestieFrame253 {
 }
 hasMoney = 1
 SetCraftSpell = <function> defined =[C]:-1
 manualOrder = <table> {
 }
 questOrder = <table> {
 }
 SetCraftItem = <function> defined =[C]:-1
 updateTooltip = 0.200000
 SetInventoryItem = <function> defined =[C]:-1
 SetQuestLogItem = <function> defined =[C]:-1
 comparing = false
 BottomOverlay = <unnamed> {
 }
 canAddRestStateLine = 1
 TopOverlay = <unnamed> {
 }
 SetAuctionSellItem = <function> defined =[C]:-1
 SetBagItem = <function> defined =[C]:-1
 needsReset = true
 miniMapIcon = false
 SetLootItem = <function> defined =[C]:-1
 SetQuestItem = <function> defined =[C]:-1
 SetAuctionItem = <function> defined =[C]:-1
}
maxDistCluster = 1
mid = 1436
(*temporary) = <function> defined =[C]:-1
(*temporary) = nil
(*temporary) = <userdata>
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'data' (a nil value)"
_QuestieFramePool = <table> {
 1 = "Questie"
 2 = <table> {
 }
 numberOfFrames = 297
 wayPointColorHover = <table> {
 }
 AddTooltipsForQuest = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFramePool.lua:495
 QuestieCreateFrame = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFramePool.lua:220
 QuestieTooltip = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFramePool.lua:516
 unusedFrames = <table> {
 }
 allFrames = <table> {
 }
 _lastMiniInsideCheck = 177686.500000
 _lastMiniInside = false
 lastTooltipShowHack = 179461.495000
 wayPointColor = <table> {
 }
 GetEventObjectiveTooltip = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFramePool.lua:417
 GetAvailableOrCompleteTooltip = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFramePool.lua:393
 IsMinimapInside = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFramePool.lua:230
 GetObjectiveTooltip = <function> defined @Interface\AddOns\Questie\Modules\FramePool\Questi
```

```
Message: ...ce\AddOns\Questie\Modules\FramePool\QuestieFrame.lua:127: attempt to index field 'data' (a nil value)
Time: Wed Jan 22 22:37:40 2020
Count: 7
Stack: ...ce\AddOns\Questie\Modules\FramePool\QuestieFrame.lua:127: attempt to index field 'data' (a nil value)
...ce\AddOns\Questie\Modules\FramePool\QuestieFrame.lua:127: in function <...ce\AddOns\Questie\Modules\FramePool\QuestieFrame.lua:116>

Locals: self = QuestieFrame225 {
 0 = <userdata>
 glow = QuestieFrame225Glow {
 }
 BaseOnUpdate = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFrame.lua:196
 FakeUnhide = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFrame.lua:361
 FakeHide = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFrame.lua:345
 texture = <unnamed> {
 }
 BaseOnShow = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFrame.lua:202
 glowLogicTimer = <table> {
 }
 BaseOnHide = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFrame.lua:226
 FadeOut = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFrame.lua:317
 UpdateTexture = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFrame.lua:230
 glowTexture = <unnamed> {
 }
 Unload = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFrame.lua:265
 GlowUpdate = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFrame.lua:178
 FadeIn = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFrame.lua:331
 frameId = 225
}
(*temporary) = nil
(*temporary) = GameTooltip {
 0 = <userdata>
 numMoneyFrames = 1
 canAddRestStateLine = 1
 SetInboxItem = <function> defined =[C]:-1
 shoppingTooltips = <table> {
 }
 SetMerchantItem = <function> defined =[C]:-1
 SetQuestLogItem = <function> defined =[C]:-1
 SetTradeSkillItem = <function> defined =[C]:-1
 BottomOverlay = <unnamed> {
 }
 npcOrder = <table> {
 }
 SetCraftSpell = <function> defined =[C]:-1
 manualOrder = <table> {
 }
 questOrder = <table> {
 }
 SetCraftItem = <function> defined =[C]:-1
 updateTooltip = 0.075000
 SetInventoryItem = <function> defined =[C]:-1
 SetHyperlink = <function> defined =[C]:-1
 comparing = false
 _owner = QuestieFrame225 {
 }
 hasMoney = 1
 TopOverlay = <unnamed> {
 }
 SetAuctionSellItem = <function> defined =[C]:-1
 SetBagItem = <function> defined =[C]:-1
 needsReset = true
 miniMapIcon = false
 SetLootItem = <function> defined =[C]:-1
 SetQuestItem = <function> defined =[C]:-1
 SetAuctionItem = <function> defined =[C]:-1
}
(*temporary) = <userdata>
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'data' (a nil value)"
```

```
Message: ...ddOns\Questie\Modules\FramePool\QuestieFramePool.lua:577: attempt to index local 'iconData' (a nil value)
Time: Wed Jan 22 22:36:34 2020
Count: 5
Stack: ...ddOns\Questie\Modules\FramePool\QuestieFramePool.lua:577: attempt to index local 'iconData' (a nil value)
...ddOns\Questie\Modules\FramePool\QuestieFramePool.lua:577: in function `handleMapIcon'
...ddOns\Questie\Modules\FramePool\QuestieFramePool.lua:648: in function <...ddOns\Questie\Modules\FramePool\QuestieFramePool.lua:516>

Locals: icon = QuestieFrame227 {
 0 = <userdata>
 glow = QuestieFrame227Glow {
 }
 BaseOnUpdate = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFrame.lua:196
 FakeUnhide = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFrame.lua:361
 FakeHide = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFrame.lua:345
 texture = <unnamed> {
 }
 BaseOnShow = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFrame.lua:202
 glowLogicTimer = <table> {
 }
 BaseOnHide = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFrame.lua:226
 FadeOut = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFrame.lua:317
 UpdateTexture = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFrame.lua:230
 glowTexture = <unnamed> {
 }
 Unload = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFrame.lua:265
 GlowUpdate = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFrame.lua:178
 FadeIn = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFrame.lua:331
 frameId = 227
}
iconData = nil
(*temporary) = 117
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'iconData' (a nil value)"
self = QuestieFrame139 {
 0 = <userdata>
 glow = QuestieFrame139Glow {
 }
 BaseOnUpdate = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFrame.lua:196
 loaded = true
 FakeUnhide = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFrame.lua:361
 data = <table> {
 }
 FakeHide = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFrame.lua:345
 AreaID = 40
 texture = <unnamed> {
 }
 BaseOnShow = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFrame.lua:202
 glowLogicTimer = <table> {
 }
 BaseOnHide = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFrame.lua:226
 FadeOut = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFrame.lua:317
 UpdateTexture = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFrame.lua:230
 y = 80.250000
 x = 44.620000
 glowTexture = <unnamed> {
 }
 Unload = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFrame.lua:265
 miniMapIcon = false
 GlowUpdate = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFrame.lua:178
 FadeIn = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFrame.lua:331
 frameId = 139
}
tinsert = <function> defined =[C]:-1
QuestieLib = <table> {
 PrintDifficultyColor = <function> defined @Interface\AddOns\Questie\Modules\Libs\QuestieLib.lua:27
 ProfileFunction = <function> defined @Interface\AddOns\Questie\Modules\Libs\QuestieLib.lua:273
 Levenshtein = <function> defined @Interface\AddOns\Questie\Modules\Libs\QuestieLib.lua:419
 CacheItemNames = <function> defined @Interface\AddOns\Questie\Modules\Libs\QuestieLib.lua:298
 GetQuestObjectives = <function> defined @Interface\AddOns\Questie\Modules\Libs\QuestieLib.lua:137
 MathRandom = <function> defined @Interface\AddOns\Questie\Modules\Libs\QuestieLib.lua:461
 GetRGBForObjective = <function> defined @Interface\AddOns\Questie\Modules\L
```

v5.5.1

**Comment by BreakBB** [comment] 2020-01-27 13:59
Duplicate of #1584

**Closed by BreakBB** 2020-01-27 13:59 UTC
Labels: bug
