### ISSUE TITLE
Quest Log doesn't close when pressing the escape key

### ISSUE THREAD

**Issue by DookieSkid** [AeroScripts/QuestieDev#1033] opened 2019-09-18 03:59 UTC
## Bug description

Opening the quest log with the tracker shortcut works, but it doesn't close when pressing the escape key. Also other panels such as the character info sheet and talents page when opened cover the quest log.

## Screenshots

![WoWScrnShot_091719_214221](https://user-images.githubusercontent.com/905921/65110201-efeaae80-d995-11e9-9bb9-afa2fc57b9d0.jpg)
![WoWScrnShot_091719_214336](https://user-images.githubusercontent.com/905921/65110211-f1b47200-d995-11e9-96be-86b7e6ba1ae6.jpg)

## Questie version

4.1.1

**Comment by drejjmit** [comment] 2019-09-18 04:28
I don't have this bug on 4.1.1. Did you do a full client restart after updating?

**Comment by DookieSkid** [comment] 2019-09-18 05:00
Yes. It only happens when I shift + left click the tracker to open the quest log. Otherwise opening the quest log normally with a keyboard shortcut or the micro menu doesn't cause the problem at all.
I've also tried disabling all other addons but Questie, and the issue still occurs.

**Comment by drejjmit** [comment] 2019-09-18 05:14
Tested shift clicking the tracker and still can't reproduce this bug. Maybe there's an addon compability issue. Can you try with just Questie activated? If it works, try enabling a few addons and see if you can find what addon cause problems.

**Comment by DookieSkid** [comment] 2019-09-18 06:29
Odd. I've tried with only Questie enabled and got the same issues. I tried with a fresh install of Classic, only enabling Questie and I still got the same problems.

**Comment by BreakBB** [comment] 2019-09-19 18:15
Yes this is an issue. After using either the "Show in questlog" option or "Show on map" the escape button does not work anymore. Moreover the questlog can overlap with other frames like stated above.

We're investigating this.

**Comment by BreakBB** [comment] 2019-09-30 19:36
Fixed in the release of v4.1.2 https://github.com/AeroScripts/QuestieDev/releases/tag/v4.1.2

**Closed by BreakBB** 2019-09-30 19:36 UTC
Labels: bug
