### ISSUE TITLE
LUA errors when mouse over objective marks on map or minimap

### ISSUE THREAD

**Issue by GregoryGH** [AeroScripts/QuestieDev#1604] opened 2019-11-30 16:53 UTC
## Bug description

LUA errors when mouse over objective marks on map or minimap

## Screenshots
27x ...ceQuestie\Modules\FramePool\QuestieFrame.lua:127: attempt to index field 'data' (a nil value)
...ceQuestie\Modules\FramePool\QuestieFrame.lua:127: in function <...ceQuestie\Modules\FramePool\QuestieFrame.lua:116>

Locals:
self = QuestieFrame579 {
 0 = <userdata>
 glow = QuestieFrame579Glow {
 }
 BaseOnUpdate = <function> defined @Questie\Modules\FramePool\QuestieFrame.lua:188
 FakeUnhide = <function> defined @Questie\Modules\FramePool\QuestieFrame.lua:350
 FakeHide = <function> defined @Questie\Modules\FramePool\QuestieFrame.lua:334
 texture = <unnamed> {
 }
 BaseOnShow = <function> defined @Questie\Modules\FramePool\QuestieFrame.lua:194
 glowLogicTimer = <table> {
 }
 BaseOnHide = <function> defined @Questie\Modules\FramePool\QuestieFrame.lua:218
 FadeOut = <function> defined @Questie\Modules\FramePool\QuestieFrame.lua:306
 UpdateTexture = <function> defined @Questie\Modules\FramePool\QuestieFrame.lua:222
 glowTexture = <unnamed> {
 }
 Unload = <function> defined @Questie\Modules\FramePool\QuestieFrame.lua:257
 GlowUpdate = <function> defined @Questie\Modules\FramePool\QuestieFrame.lua:170
 FadeIn = <function> defined @Questie\Modules\FramePool\QuestieFrame.lua:320
 frameId = 579
}
(*temporary) = nil
(*temporary) = GameTooltip {
 0 = <userdata>
 SetSpellBookItem = <function> defined =[C]:-1
 SetHyperlink = <function> defined =[C]:-1
 SetTradeSkillItem = <function> defined =[C]:-1
 _owner = QuestieFrame579 {
 }
 manualOrder = <table> {

27x ...ddOns\Questie\Modules\FramePool\QuestieFramePool.lua:557: attempt to index field 'data' (a nil value)
...ddOns\Questie\Modules\FramePool\QuestieFramePool.lua:557: in function <...ddOns\Questie\Modules\FramePool\QuestieFramePool.lua:527>

Locals:
self = QuestieFrame579 {
 0 = <userdata>
 glow = QuestieFrame579Glow {
 }
 BaseOnUpdate = <function> defined @Questie\Modules\FramePool\QuestieFrame.lua:188
 FakeUnhide = <function> defined @Questie\Modules\FramePool\QuestieFrame.lua:350
 FakeHide = <function> defined @Questie\Modules\FramePool\QuestieFrame.lua:334
 texture = <unnamed> {
 }
 BaseOnShow = <function> defined @Questie\Modules\FramePool\QuestieFrame.lua:194
 glowLogicTimer = <table> {
 }
 BaseOnHide = <function> defined @Questie\Modules\FramePool\QuestieFrame.lua:218
 FadeOut = <function> defined @Questie\Modules\FramePool\QuestieFrame.lua:306
 UpdateTexture = <function> defined @Questie\Modules

## Questie version
5.2.3

**Comment by BreakBB** [comment] 2019-12-17 18:22
Duplicate of #1584

**Closed by BreakBB** 2019-12-17 18:22 UTC
Labels: bug, map
