### ISSUE TITLE
Chen's Empty Keg repeatable quest unavailable in EU servers

### ISSUE THREAD

**Issue by Cerby3BR** [AeroScripts/QuestieDev#997] opened 2019-09-16 16:33 UTC
Just what it says in the title, the final quest in the Chen's Empty Keg line is showing up as available even though it was removed from EU servers for legal reason.

https://classic.wowhead.com/quest=822/chens-empty-keg#comments

Version 4.1.0

**Comment by BreakBB** [comment] 2019-09-16 16:35
Duplicate of #682 

Would be great if you could provide some proof about the "legal reason" comment.

**Closed by BreakBB** 2019-09-16 16:35 UTC
Labels: quest issue
