### ISSUE TITLE
Quest tracker dungeon and raid notation issues

### ISSUE THREAD

**Issue by eshukina** [AeroScripts/QuestieDev#1529] opened 2019-11-12 03:46 UTC
Since v5.0.1, the Korean version of quest tracker now displays dungeons and raid quests as '?'.

ex) [18D]-> [18?]
[+ 60R]-> [+60?]

It's probably a problem with non-English national locales.

(I am using the latest version of v5.2.0 and have not modified it.)

Quest List
: https://classic.wowhead.com/quest=5725/the-power-to-destroy
: https://classic.wowhead.com/quest=959/trouble-at-the-docks
: https://classic.wowhead.com/quest=5721/the-battle-of-darrowshire

![image](https://user-images.githubusercontent.com/57651492/68640101-081c1b80-054a-11ea-8caf-51b8cde38550.png)

**Comment by BreakBB** [comment] 2019-11-12 08:03
Duplicate of #1358 

Please check the latest comments there and report if it is fixed with the file listed there :+1:

**Closed by BreakBB** 2019-11-12 08:03 UTC
Labels: bug
