### ISSUE TITLE
Can't track quests/quest icons don't show up on map

### ISSUE THREAD

**Issue by yxion** [AeroScripts/QuestieDev#413] opened 2017-03-07 02:50 UTC
So out of nowhere Questie doesn't work anymore on my character. I've tried it on other characters and it seems fine, but after I got to Hillsbrad Foothills, the addon stopped worked as intended.

It was working fine at the start of the zone, but then suddenly it stopped. I disabled all addons I have, because no errors were showing up, and I got this one on the screenshot. I already deleted my WDB folder, disabled addons, deleted Questie from my WTF folder, reset the settings but nothing worked. I also searched for answers for this error but found none. 

Here's the screenshot:
![wowscrnshot_030617_233945](https://cloud.githubusercontent.com/assets/26239116/23639636/892901d0-02c7-11e7-85b4-2e57501ff908.jpg)

**Comment by Dyaxler** [comment] 2017-03-13 20:59
Hmmm... that error is in the Clustering code. @ZoeyZolotova any ideas on this one?

The arathi basin pvp quests being in there perhaps?

**Comment by ZoeyZolotova** [comment] 2017-03-13 21:15
Hmm I think I know what the problem is but it should already be fixed in 3.7

**Comment by staplerx300** [comment] 2017-03-14 23:31
happened to me too

**Comment by xzxdiablo** [comment] 2017-03-17 01:39
happened the same exact thign whit my charachter after i went to azshara but wahts strange is that whit the others character works fine

**Comment by yxion** [comment] 2017-03-17 01:46
It fixed itself after I abandoned all the Arathi PvP Quests

**Comment by ZoeyZolotova** [comment] 2017-03-17 09:38
Interesting, "Arathi Basin Mark of Honor!" doesn't exist in Questie. It also doesn't appear on [db.vanillagaming.org](http://db.vanillagaming.org/?quests=6.3358). Thanks for submitting this bug. Will need to make sure non-existent quests don't break anything.

**Comment by ZoeyZolotova** [comment] 2017-03-18 09:15
![image](https://cloud.githubusercontent.com/assets/22694317/24070764/a382285a-0c17-11e7-82d5-b2f810104bb2.png)

Fixed for next version.

**Comment by Muehe** [comment] 2017-09-27 21:56
New beta release is out. It can be downloaded [here](https://github.com/AeroScripts/QuestieDev/releases/tag/v3.7.0-beta).

**Closed by Muehe** 2017-09-27 21:56 UTC
Labels: bug, fix will be in next release, resolved
