### ISSUE TITLE
The Mystery of Morrowgrain (no quest available)

### ISSUE THREAD

**Issue by Painstormx** [AeroScripts/QuestieDev#1143] opened 2019-09-25 20:52 UTC
Shown on map, but npc doesn't have a quest available.
https://classic.wowhead.com/quest=3791/the-mystery-of-morrowgrain
The wowhead comments suggests that you can only get this if you have accepted Morrowgrain Research quest from Staghelm in Darnassus.

Questie v4.1.1
Hunter level 47.

**Comment by BreakBB** [comment] 2019-09-26 06:46
Duplicate of #885 , but thanks for your report! :)

**Closed by BreakBB** 2019-09-26 06:46 UTC
Labels: quest issue
