### ISSUE TITLE
Not adding quest objectives to minimap

### ISSUE THREAD

**Issue by alfredSss** [AeroScripts/QuestieDev#261] opened 2016-07-02 10:42 UTC
hi, after I accept a quest it doesn't add the little bag/sword etc icon to the minimap until I abandon the quest and accept it again also it doesnt auto track quests when I collect the first objective. 

I am on vanilla server Magicwow (http://www.magicwow.co.uk/), running addons: eql 3.6.1, mobinfo2, OmniCC, OneBag -Ace2-, Questie v3.1. 

I had some graphic issues and had to reinstall the game and was previously running some different addons which I lost so I had to get new ones, I believe I was running an earlier version of Questie and no eql, omnicc and maybe a different bag mod.

Thanks for any help

**Comment by Muehe** [comment] 2016-07-02 18:36
Could you please post a screenshot of the `/questie settings` output [like this](https://github.com/AeroScripts/QuestieDev/issues/249#issuecomment-222032215)? I think you might have `alwaysShowQuests = false`. 

Also, have you tried opening and closing the normal map? Might help resetting the minimap zone.

**Comment by alfredSss** [comment] 2016-07-02 21:16
![screen shot 2016-07-03 at 6 31 24 am](https://cloud.githubusercontent.com/assets/20254923/16542357/e52329b8-40e7-11e6-89d8-54aabab09b66.png)

Thanks for the reply. Here is the screenshot. I tried opening/closing the normal map and it doesn't add the objective. 

By the way sometimes it does work but mostly I have to abandon and reaccept the quest for them to show, and I always have to manually track the quest from the quest log for it to show in the on screen tracker.

**Comment by Muehe** [comment] 2016-07-02 22:08
I am guessing you had a previous version of Questie installed? Try `/questie clearconfig`, it gets rid of older SavedVariables that might cause this. Typing just `/questie` will show a list of commands to readjust your settings.

**Comment by alfredSss** [comment] 2016-07-04 07:40
Yeah I tried the clearconfig, didn't work either. They seem to show after I track the quest.

**Comment by Muehe** [comment] 2016-07-04 11:32
Well that's weird. As long as the `/questie showquests` option is enabled it should show untracked quests as well. Maybe a Questie developer could help but haven't seen any of them here in weeks...

Could you try disabling your other addons and see if the problem persists? I have a hunch that it is caused by EQL3.

**Comment by alfredSss** [comment] 2016-07-05 08:54
I will try that. I thought you were the dev! ahah thanks for taking the time to help me out, really appreciate it (even if we haven't got anywhere)

**Comment by Muehe** [comment] 2016-07-05 12:16
Just keeping the lights on :wink:

**Closed** 2017-01-15 19:12 UTC
