### ISSUE TITLE
Missing Available Quests

### ISSUE THREAD

**Issue by bobbyj9** [AeroScripts/QuestieDev#1275] opened 2019-10-11 18:03 UTC
Available quests for every zone says 0.

v4.1.2

**Comment by TexFromHell** [comment] 2019-10-11 19:34
I have the same issue, also does not show which quests are completed but lists them all from the zones as complete.

**Comment by drejjmit** [comment] 2019-10-11 19:45
This is fixed in the upcoming version :)

**Comment by dknight** [comment] 2019-10-12 01:39
Same issue, they just dissappered

**Comment by BreakBB** [comment] 2019-10-12 18:37
Duplicate of #1239

**Closed by BreakBB** 2019-10-12 18:37 UTC
Labels: bug
