### ISSUE TITLE
Suggest Tracker be re-sizable and lockable

### ISSUE THREAD

**Issue by MiscaiSG** [AeroScripts/QuestieDev#1054] opened 2019-09-18 22:55 UTC
I would be nice if we could resize the width of the Quest Tracker. When resizing long quest objectives should word wrap into multiple lines. Right now, not only can you not change the width but it becomes SUPER wide since it insists on showing everything in a single line. The width of the window should determine how long the line of text is and wrap accordingly rather the line of text determining how wide the window is.

Also it would be really great if we could lock it in place - I keep accidentally dragging it all over my screen. 
**_EDIT - I found the lock button hehe_**
Thanks :)

**Comment by BreakBB** [comment] 2019-09-22 18:31
You currently can only resize it by changing the font size. It will decrease the size in general as well. And yes, we're aware of the issue of wrapping questnames/texts

**Comment by rbpaiett** [comment] 2019-10-23 14:51
I second that request for word wrap.
![Questie_Word_Wrap_Request](https://user-images.githubusercontent.com/1621701/67405649-e8588f80-f569-11e9-9674-1c06ed0e0b81.jpg)

**Comment by Gogo1951** [comment] 2019-12-11 16:33
Hey @MiscaiSG ,

This seems like a dupe of https://github.com/AeroScripts/QuestieDev/issues/1004 -- can we close it?

**Comment by BreakBB** [comment] 2020-01-04 12:30
With the change of the font size you are able to resize the tracker just fine. And it has been lockable since its introduction. Closing it for now. Feel free to comment if you have more specific ideas.

**Closed by BreakBB** 2020-01-04 12:30 UTC
Labels: feature request, tracker
