### ISSUE TITLE
Mobs showing what quest item they drop doesn't work.

### ISSUE THREAD

**Issue by Korach** [AeroScripts/QuestieDev#471] opened 2017-12-05 22:22 UTC
Hello there. I have been having this problem where the part that shows quest drops wont show up for more than 1 second. When I mouse over a mob, it will stay for 1 second then disappear for another 30+ seconds to even minutes. Is there a way to fix this? I copied the image of the section I ment. That won't stay up for long.
![687474703a2f2f692e696d6775722e636f6d2f69596e613737382e706e67](https://user-images.githubusercontent.com/34204486/33634023-99e3a868-d9c7-11e7-80ed-08ed3f942be4.png)

**Comment by Muehe** [comment] 2017-12-05 22:35
I tried to reproduce this with Questie v3.7 right now and everything seems to work fine. Which version of Questie and which other addons are you using?

**Comment by Korach** [comment] 2017-12-05 23:01
v3.7? The beta? And I'm using v3.1 Questie, FastQuests, the X-Pearls, WIM, Wardrobe, URL copy, TheoryCraft, SuperMacro, Stubby, SnagaLoatheb, QuickHeal,  Postal, PallyPower, OneView, OneBank, MobInfo-2, KLHThreatMeter, GMail, Extended QuestLog, EquipCompare, EnhTooltip, Decursive, Cartaographer, BonusScanner, Bongos ActionBar, BlockSalvation, BigWigs, BearCastBar, and LazyPig

**Comment by Muehe** [comment] 2017-12-05 23:39
Looking at your list this could easily be a interoperability problem with one of your other addons, obvious candidates being MobInfo and EnhTooltip. I would have to test further to be sure.

However, if you are really using Questie 3.1, I'd recommend you upgrade to at least 3.69, the latest stable release. The bug might have been fixed over the last year. Note that fixes will only be made based on v3.7 beta though, but it is at 27k downloads right now so it seems to be pretty stable judging from the issue tracker.

**Comment by Dyaxler** [comment] 2017-12-07 02:22
I vaguely remember the huge fix for tool tips in v3.1...

> * All "double" tooltip issues have been fixed. :) Unless you have EQL3's
> "Show Relevant Quest in Item Tooltip" and "Show Relevant Quest in Mob
> Tooltip" options enabled. I've added code in Questie to disable these
> options automatically but I'm willing to bet someone's mod setup will
> cause it to not work so please check those options before reporting
> issues.

I'm a heavy user of EnhTooltip and MobInfo so that would have been part of my test runs. All of Korach's addons are well used except for FastQuests. Not sure what that is exactly but judging by the name it sounds like a quest helper type addon. Might be messing with the tooltip... over writing Questies maybe?

Muehe is right. Since v3.1 we've had some pretty amazing people working with us and Zoey has practically rewrote all the tooltip code. Use the beta version. :)

**Comment by Muehe** [comment] 2017-12-12 01:19
Closing this issue because it seems to be caused by usage of an outdated Questie version.

@Korach If you continue having problems after an update to 3.7, please re-open the issue or create a new one.

**Closed by Muehe** 2017-12-12 01:19 UTC
Labels: bug, investigating, need more info
