### ISSUE TITLE
The Hermit (Duskwood) 

### ISSUE THREAD

**Issue by tonyxc600** [AeroScripts/QuestieDev#1199] opened 2019-10-01 08:49 UTC
## Description
'The Hermit' is not available in game, but shown as available in Questie. Likely already completed, as I have accepted the next quest in the chain already. Have tried running /run Questie.db.char.complete = {} to no avail.

## Wowhead link
https://classic.wowhead.com/quest=165/the-hermit

## Screenshots
![WoWScrnShot_100119_184021](https://user-images.githubusercontent.com/56020611/65947658-1cb1c200-e47c-11e9-882a-8dd7d33f55df.jpg)

## Questie version
Version: 4.1.2 BETA 121 dff5a12

**Comment by tonyxc600** [comment] 2019-10-01 08:50
Possibly linked to #1197

**Comment by BreakBB** [comment] 2019-10-13 18:03
Duplicate of #1173

**Closed by BreakBB** 2019-10-13 18:03 UTC
Labels: quest issue
