### ISSUE TITLE
Compatibility with TinyTip

### ISSUE THREAD

**Issue by xShirokuma** [AeroScripts/QuestieDev#281] opened 2016-11-09 01:41 UTC
If using offset values with TinyTip, mousing over the minimap quest icons will break the offset until the UI is reloaded.

**Comment by laytya** [comment] 2016-11-11 04:40
i have tinytip, and cant reproduce this bug. Can you provide more information.

**Comment by xShirokuma** [comment] 2016-11-12 02:39
Step 1: Set TinyTip Anchor to 'Cursor'
![questiebug1](https://cloud.githubusercontent.com/assets/23349204/20235067/b22fb20c-a856-11e6-9fa9-a91301b423f2.png)

Step 2: Set TinyTip Offset (X or Y) to a value (50-100 is enough to notice)
![questiebug2](https://cloud.githubusercontent.com/assets/23349204/20235065/a4ee4cd4-a856-11e6-8b8f-e1593d4c4a07.png)

Step 3: Mouse over a mob or player to show successful TinyTip function
![questiebug3](https://cloud.githubusercontent.com/assets/23349204/20235071/bd7330e4-a856-11e6-9cf1-f58c0b857edf.png)

Step 4: Mouse over Questie marker on the MiniMap (TinyTip offset is now broken)
![questiebug4](https://cloud.githubusercontent.com/assets/23349204/20235073/c243f7a2-a856-11e6-8ca8-e76b9463b87f.png)

Step 5: Mouse over a mob or player to show broken TinyTip function
![questiebug5](https://cloud.githubusercontent.com/assets/23349204/20235077/d17c5ce6-a856-11e6-8bc3-7d5d3b3d50f3.png)

**Comment by Dyaxler** [comment] 2016-12-27 07:48
This should be fixed in v3.5
https://github.com/AeroScripts/QuestieDev/releases/latest

**Comment by xShirokuma** [comment] 2016-12-31 06:43
You sure this is resolved? Updated Questie and still having the same issue. Disabled minimap tooltips for the time being to temp fix.

**Comment by Dyaxler** [comment] 2016-12-31 17:15
Could be a bug in TinyTip. I use offsets myself and don't experience the same issues you do. I've been using TinyTip for quite some time and have never experienced any conflicts with Questie.

**Comment by Dyaxler** [comment] 2017-01-06 23:08
Might be related to this but I've noticed that with TinyTip if you flip back and forth between items in your bag and a different Tooltip type, I.E. Item or Monster, the tooltip gets anchored to the WoW clients tooltip anchor and not TinyTip's anchor. Hovering over another object type seems to clear it up and it goes back to putting the tooltip on the right anchor. This is not related to Questie in anyway. Might be the reason your offsets are buggered. Mine were only reset when the tooltip was displaying at the game clients default anchor. Once it returned to TinyTip's anchor the offsets were restored.

Yes, I've tried this with all mods disabled with only TinyTip enabled and the issue is still present.

**Closed** 2017-01-15 19:11 UTC
Labels: bug, resolved, test again
