### ISSUE TITLE
Including [Elite] into the questname 

### ISSUE THREAD

**Issue by LasterOfDesaster** [AeroScripts/QuestieDev#1281] opened 2019-10-11 23:41 UTC
## Description

Looking on the map and seeing a quest where I know if it is a elite one only AFTER accepting it and looking in the quest log is kinda annoying. It would be greate if quest had this function as well, since `GetQuestLogTitle(QuestLogID)` returns as second value a tag if the quest is Elite, Dungeon, Group, ...

**Comment by Painstormx** [comment] 2019-10-16 11:35
I strong support this for map tooltips and quest tracker, it could be like this:
[38] = Normal quest
[38+] = Elite quest
[38D] = Dungeon quest

**Comment by BreakBB** [comment] 2019-10-16 12:13
Duplicate of #1055

**Closed by BreakBB** 2019-10-16 12:13 UTC
Labels: feature request
