### ISSUE TITLE
Battlegrounds quests not translated into Russian

### ISSUE THREAD

**Issue by aanger1122** [AeroScripts/QuestieDev#1623] opened 2019-12-11 12:49 UTC
Battlegrounds quests not translated in Russian client
the name of the quest, as well as its description

**Comment by BreakBB** [comment] 2019-12-11 12:52
@aanger1122 Can you share a screenshot? Maybe we're simply missing the translations for them. Make sure to use the Wowhead client to upload the data to Wowhead. We rely on that data.

**Comment by f1est0** [comment] 2019-12-11 14:27
[https://imgur.com/e5q6FHo](url)
Bug ? or featch?

**Comment by BreakBB** [comment] 2019-12-11 14:30
@f1est0 Your screenshot is totally different thing! And also a duplicate of #1621

**Comment by aanger1122** [comment] 2019-12-11 15:42
> @aanger1122 Can you share a screenshot? Maybe we're simply missing the translations for them. Make sure to use the Wowhead client to upload the data to Wowhead. We rely on that data.

https://drive.google.com/file/d/1YrCuT8xKZocMWLrmi-K-tcOyWQykugTp/view?usp=sharing
https://drive.google.com/file/d/1NEwD46UkzsCdj9l0G34-eN4C6LBMCshD/view?usp=sharing

**Comment by aanger1122** [comment] 2019-12-11 15:42
almost all quests related to the Battlegrounds are not translated

**Comment by BreakBB** [comment] 2019-12-11 20:23
@aanger1122 I just checked and we do have the translations for those quests 🤔 You restarted WoW, yes? And Questie is set to Russian as well I guess.

**Comment by aanger1122** [comment] 2019-12-11 22:59
I restarted the client and also reinstalled the addon, the quests are still without translation

**Comment by aanger1122** [comment] 2019-12-18 18:43
localization of quest the Battlegrounds is still missing
https://imgur.com/a/7OclWSi

**Comment by AeroScripts** [comment] 2020-08-19 23:03
@aanger1122 hey can you test the latest release? Russian translations have updated and this may be solved.

**Comment by drejjmit** [comment] 2020-08-20 01:34
Looks good to me on latest:

![image](https://user-images.githubusercontent.com/15526476/90706511-8fdf4500-e295-11ea-8c70-f0286cd3e934.png)

![image](https://user-images.githubusercontent.com/15526476/90706669-f82e2680-e295-11ea-9154-dc531e1e5ab3.png)

**Closed** 2020-08-20 11:24 UTC
Labels: Questie - Localization, Sticky - BLOCKED, Type - Defect
