### ISSUE TITLE
QuestieQuest.lua error

### ISSUE THREAD

**Issue by TheRealKraggy** [AeroScripts/QuestieDev#1020] opened 2019-09-17 09:09 UTC
## Bug description
Every time Questie loads I get the error:

"There was an error populating objectives for Gadgetzan Water Survey 992 1
QuestieQuest.lua:724: attempt to index local 'spawn' (a number value)"

I obtained this quest yesterday and didn't get the error, though I cannot swear that Questie ever reloaded after I got it.

## Questie version
Version 4.1.0,

**Comment by BreakBB** [comment] 2019-09-17 09:12
Duplicate of #1013 I will look into this later this day. Sorry for the issue

**Closed by BreakBB** 2019-09-17 09:12 UTC
Labels: bug
