### ISSUE TITLE
Quest Log Not Updating

### ISSUE THREAD

**Issue by Erasurehead87** [AeroScripts/QuestieDev#1775] opened 2020-02-19 23:05 UTC
## Bug description
Every time I accept or finish a quest the log doesn't update and either says that I am still on the quest I completed or doesn't update for the next quest in my quest log.
![WoWScrnShot_022020_134229](https://user-images.githubusercontent.com/61255212/74972398-3cc02e80-53e7-11ea-9f87-4a296058710e.jpg)

## Questie version
v5.7.1

**Comment by BreakBB** [comment] 2020-02-20 06:10
@Erasurehead87 What do you mean by "the log"? Do you mean the tracker on the right? Could you share a screenshot?

**Comment by Orome123** [comment] 2020-02-20 06:41
@BreakBB  he definitely refers to this same issue https://github.com/AeroScripts/QuestieDev/issues/1762

**Comment by Erasurehead87** [comment] 2020-02-20 19:46
@BreakBB The Quest Log in the upper right and the tracker in the upper left. They seem to not be updating active quests, meaning that when I kill something it wont count it on the tracker. It also doesn't seem to be updating when I accept a quest in the actual log.

**Comment by BreakBB** [comment] 2020-02-24 13:32
@Erasurehead87 If you want to track quests in the Tracker (the right one) you have to `shift + leftclick` those quests in the quest log (the left one). That will add a quest to the Tracker and should update there as well. You can also active "Automatically Track All Quests" which will add all quests from your quest log to the Tracker:

![image](https://user-images.githubusercontent.com/33514570/75156447-74461800-5712-11ea-8cbf-afdc2e8787e2.png)

Nobody has reported yet that the Tracker isn't working anymore and I did some quests today without any problem.

Maybe I don't understand your problem, so feel free to explain in detail and maybe share your Questie settings.

**Comment by Scifibookguy** [comment] 2020-02-28 21:03
I can confirm that quests aren't getting updated in the Quest Log when you turn them in, and any follow-up quests aren't showing. For example, I had a character turn in the pre-quest to "In the Name of the Light" in Southshore and my Quest Log still showed the pre-quest and not the new quest until I logged out and back in. This has happened with any quest where there is a follow-up quest.

**Comment by BreakBB** [comment] 2020-02-28 21:06
@Scifibookguy Could you share your settings?

**Comment by Scifibookguy** [comment] 2020-02-29 21:27
Is there an easy way to share my settings, or do I have to type in everything?

**Comment by BreakBB** [comment] 2020-02-29 21:35
@Scifibookguy Simply take a screenshot e.g. by using Windows Snipping Tool

**Comment by Scifibookguy** [comment] 2020-03-01 02:13
These are the settings that seem relevant. I don't remember changing any settings from default, but it's possible.

![QuestieSettings](https://user-images.githubusercontent.com/59448593/75618174-545e8c00-5b38-11ea-875f-195878807f55.jpg)
![QuestieTracker](https://user-images.githubusercontent.com/59448593/75618175-5a546d00-5b38-11ea-8c2a-d32afe0d47ac.jpg)

**Comment by BreakBB** [comment] 2020-03-01 09:52
@Scifibookguy Could you try to disable the "Automatically track all quests" option of the Tracker, then manualy track some quests and check if that is working?

**Comment by Scifibookguy** [comment] 2020-03-01 23:11
Will do.

**Comment by Scifibookguy** [comment] 2020-03-04 21:55
Sorry for the delay, I didn't have time to get online and complete a quest in a questline for a couple of days. Anyway, here is my Mage who has just finished the Motes of Myzrael quest, and yet the Quest Log still shows it with 0/12 motes, and doesn't show the next quest in the questline.

![MotesQuest](https://user-images.githubusercontent.com/59448593/75926631-e0263000-5e38-11ea-8a02-f5554de0d1c4.jpg)

**Comment by BreakBB** [comment] 2020-03-04 22:19
@Scifibookguy I don't think that is related to Questie. You should disable all addons except Questie and try again. Questie doesn't really interfere with the Quest log and therefore shouldn't cause such problems.

**Comment by Scifibookguy** [comment] 2020-03-04 23:47
Alright, I'll give that a try.

**Comment by Scifibookguy** [comment] 2020-03-05 00:00
I disabled all add-ons except Questie, and it still happens:

![StonesOfBinding](https://user-images.githubusercontent.com/59448593/75934414-68f99780-5e4a-11ea-8d2d-52fd09ed4350.jpg)

**Comment by Scifibookguy** [comment] 2020-03-05 00:20
Some other things that happen:

1. Quest Log empties. I log in with a character and the Quest Log is empty and says "No Active Quests." I have to log in another character to get quests to show in the Log.

2. One I noticed tonight with my Mage, is some quests were no longer listed in the Quest Log. These were all from Southshore: Noble Deaths, Dark Council, In the Name of the Light. Questie showed them on my map as available with a !, but all the NPCs showed grey ? when I went to them. When I turned add-ons off and relogged, they showed up in my Quest Log. Then I turned add-ons on, and they were still showing in the Log.

I don't use any other Quest add-ons besides Questie.

**Comment by BreakBB** [comment] 2020-03-05 12:23
@Scifibookguy When you log into a character and the quest log is empty a simple `/reload` should help. If not you might want to delete your "WTF" and "cache" folder. **This will also delete all ingame and addon settings**!

Are you on v5.7.2 btw and does this issue also happen without Questie?

**Comment by Scifibookguy** [comment] 2020-03-05 15:37
The empty Quest Log has only happened twice in about a month. I'll try that /reload if it happens again. Yes, I'm on v5.7.2 and I'll have to check without Questie.

**Comment by Scifibookguy** [comment] 2020-03-05 20:58
I turned off all Add-ons before turning in the Ensorcelled Parchment quest. Everything worked like it should, with the Parchment quest closing out, and the Stormpike's Delivery quest showing in the Quest Log.

![ParchmentQuest](https://user-images.githubusercontent.com/59448593/76025041-22637600-5efa-11ea-870a-3a9f90f58a14.jpg)

**Comment by Scifibookguy** [comment] 2020-03-07 21:03
This is where I turned off _only_ Questie, and turned in the Special Forces quest to get the Colonel Kurzen quest. It worked correctly, with Questie turned off:

![SpecialForces](https://user-images.githubusercontent.com/59448593/76152387-1825b100-608d-11ea-8952-28031c997cf7.jpg)

**Comment by BreakBB** [comment] 2020-03-08 02:37
@Scifibookguy So even when you close and reopen the quest log the quests says in it?

**Comment by Scifibookguy** [comment] 2020-03-08 06:22
When the previous quest stays in my Quest Log, like in "The Princess Trapped" quest screenshot, it doesn't matter how often I open and close the Quest Log. I have to log out and back in for the new quest to show correctly.

**Comment by VacoTM** [comment] 2020-03-08 09:51
v5.7.2 and v5.7.1 doesn't update the quest log. I backtracked to v5.7.0 and it works again.

**Comment by BreakBB** [comment] 2020-03-08 11:40
@Scifibookguy and @VacoTM I guess your PC setup isn't totally outdated, is it?
It could be that Questie is taking too much time for processing a quest event which results in an issue on Blizzards side :thinking:

I will check the differences between v5.7.1 and v5.7.0. Maybe we missed something

**Comment by Scifibookguy** [comment] 2020-03-08 19:38
My PC specs are core i7-3770k @ 3.5GHz, 8GB RAM, GTX 1060 6GB, Windows 10 Pro.

**Comment by BreakBB** [comment] 2020-03-10 20:41
I just compared v5.7.0 and v5.7.1 and don't see anything which explains why v5.7.0 is working for you and v5.7.1 is not

**Comment by VacoTM** [comment] 2020-03-11 06:45
I stood by a questgiver and picked up & abandoned the quest until it worked. v5.7.0 did this at least.

**Comment by BreakBB** [comment] 2020-03-11 07:02
@Scifibookguy To be honest I think deleting the `WTF` and `cache` folder is one of the last ideas I have atm. The patch before the one today introduced some errors/problems (like the empty quest log) and users reported deleting the folders helped them.

**Comment by Scifibookguy** [comment] 2020-03-11 18:32
So delete the actual folders, or delete the contents inside the folders?

**Comment by BreakBB** [comment] 2020-03-12 09:12
@Scifibookguy You can delete the folders when you close WoW. They will be created again on the next startup.

**Comment by BreakBB** [comment] 2020-03-18 09:38
@Scifibookguy Any news on this?

**Comment by Scifibookguy** [comment] 2020-03-18 22:33
Things seem to be working as intended, thanks :) If anything happens again, I'll post again.

**Comment by BreakBB** [comment] 2020-03-19 13:18
@Scifibookguy Great, thanks for coming to this. Feel free to create another issue or open this up again if anythings comes up.

**Closed by BreakBB** 2020-03-19 13:18 UTC
Labels: bug, need more info
