### ISSUE TITLE
Alternative drop for quest Ruuzel (ID 1009) not listed

### ISSUE THREAD

**Issue by teelolws** [AeroScripts/QuestieDev#2325] opened 2020-08-28 22:37 UTC
## Description

The quest item Ring of Zoram can drop off Ruuzel and Lady Vespia. Lady Vespia does not list the drop on mouseover.

## Wowhead link

https://classic.wowhead.com/item=5445/ring-of-zoram

## Screenshots

![image](https://user-images.githubusercontent.com/49792789/91620219-6b950e00-e9e3-11ea-947a-bcc9e9cca89e.png)
![image](https://user-images.githubusercontent.com/49792789/91620292-a434e780-e9e3-11ea-984d-b77189751c33.png)

## Questie version

6.0.5

**Comment by Gogo1951** [comment] 2020-08-29 19:10
Hey @teelolws ,

Thanks for calling this out.

This issue is a dupe of:

* When in a group, shared objectives don't show up in tooltips until the first kill / gather occurs · Issue #2142 · AeroScripts/QuestieDev || https://github.com/AeroScripts/QuestieDev/issues/2142

**Comment by Gogo1951** [comment] 2020-08-29 19:13
Ignore my last comment, that's probably also going on here. 

But yeah, in our DB we only have this dropping off the one mob.

> [5445]={"Ring of Zoram",{1009},{3943},{}},

**Comment by drejjmit** [comment] 2020-08-29 19:19
Hello!
Thanks for the report.

I'm not sure adding a Rare mob as drop for this quest item is a good idea. In the past we even removed Rares as possible drops. Adding this Rare would put markers all over the Zoram Strand instead of only the island where the normal quest mob is.

![image](https://user-images.githubusercontent.com/15526476/91644517-0f5ed800-ea3d-11ea-926c-3269ffe175b6.png)

**Comment by teelolws** [comment] 2020-08-29 20:55
Can you not add it for mouseover only, not icons?

**Comment by Gogo1951** [comment] 2020-09-02 07:08
Hey @teelolws ,

Have to agree with @drejjmit here, adding this mob would cause more confusion and make completing the quest harder. Good catch, it does drop off the rare, just hard to tell people to look for a rare that patrols vs. a named NPC in a relatively stable location.

**Closed by Gogo1951** 2020-09-02 07:08 UTC
Labels: Questie - Quest Issue, Type - Defect
