### ISSUE TITLE
Bugged Quest: [1] Encrypted Letter

### ISSUE THREAD

**Issue by Aerifax** [AeroScripts/QuestieDev#826] opened 2019-09-05 19:15 UTC
## Description
The mini map is showing this quest as available but I can't pick it up and NPC doesn't or give me the quest. It is a warlock or rogue quest in Elwynn Forest. Probably only for humans, but my character is a gnome warlock. See attached picture.
I found on wowhead that it is a rogue quest. I recreated a character with same name.
/run Questie.db.char.complete = {}
  /reload
This doesn't remove it.

## Wowhead link
https://classic.wowhead.com/item=9555/encrypted-letter#provided-for
![WoWScrnShot_090519_205534](https://user-images.githubusercontent.com/32965954/64371965-27666c00-d022-11e9-9c8a-3a4fca5b019c.jpg)

## Questie version
4.0.16

**Comment by AeroScripts** [comment] 2019-09-06 08:59
Very strange, I can't seem to reproduce this issue in v4.0.17 (Which will be out in about an hour)

We recently added shift+click to hide quests, so you should be able to hide it for now. Thanks for reporting ill keep an eye on this (if its showing up, something went wrong with class detection)

Maybe its mis-detecting warlock, ill test that soon

**Comment by BreakBB** [comment] 2019-09-14 10:55
I can't reproduce this either. Closing it for now since our data looks alright. Maybe some rare hiccup. Thanks for the report!

**Closed by BreakBB** 2019-09-14 10:55 UTC
Labels: quest issue
