### ISSUE TITLE
Jonespyre's Request

### ISSUE THREAD

**Issue by Painstormx** [AeroScripts/QuestieDev#1829] opened 2020-03-18 10:41 UTC
Just stumbled across this quest in Feathermoon Stronghold as a lvl 51 mage.
https://classic.wowhead.com/quest=3788/jonespyres-request
It was not shown on the map/minimap.
Questie v5.9.0.

After handing it in, the next quest in the questline showed up fine.

**Comment by BreakBB** [comment] 2020-03-18 13:43
Duplicate of #1754

**Closed by BreakBB** 2020-03-18 13:43 UTC
Labels: quest issue

**Comment by StraussWylde** [comment] 2022-12-14 12:49
This quest shows up in Stormwind (level 50) on the map but NPC is not there, of course.

**Comment by drejjmit** [comment] 2022-12-14 13:25
This is probably due to the map change introduced in Wrath of the Lich king, when Stormwind Harbour got added.
