### ISSUE TITLE
Error populating Objectives

### ISSUE THREAD

**Issue by Ulidan** [AeroScripts/QuestieDev#1509] opened 2019-11-08 18:43 UTC
## Bug description
When I picked up the quest and since then every login I get an error from Questie:
"There was an error populating objectives for Imp Delivery 7629 1"
"Interface\Addons\Questie\Modules\QuestieQuest.lua:882: bad argument #1 to 'pairs' (table expected, got nil)"

## Screenshots
![WoWScrnShot_110819_202922](https://user-images.githubusercontent.com/24996389/68502060-45da2500-0268-11ea-8c9c-5303742d03f4.jpg)

**Comment by BreakBB** [comment] 2019-11-09 13:28
Duplicate of #1506 You can find a file in the linked issue which resolves your issue! Thanks for the report 👍

**Closed by BreakBB** 2019-11-09 13:28 UTC
Labels: bug
