### ISSUE TITLE
Hide objectives based on tracked quests

### ISSUE THREAD

**Issue by Zeliax** [AeroScripts/QuestieDev#1834] opened 2020-03-20 19:35 UTC
Hi. 

I've recently started leveling a horde alt, and in the Barrens the map is "all fucked up" and cluttered with quest objectives. I know it's possible to "unclutter" the map and I like having the quest objectives shown, but I was wondering if it was possible to hide quest objectives, and only show objectives for tracked quests?

**Comment by BreakBB** [comment] 2020-03-22 21:04
Duplicate of #1224

**Closed by BreakBB** 2020-03-22 21:04 UTC
Labels: feature request, tracker
