### ISSUE TITLE
Minimap Tooltips not showing on mouseover

### ISSUE THREAD

**Issue by Kiefy** [AeroScripts/QuestieDev#1521] opened 2019-11-10 15:33 UTC
## Bug description
After rezoning, or possibly other cause, mousing over quest markers on Minimap does not show the tooltip until you open/close main map. This only started being an issue after last update.

## Screenshots
![Minimap](https://i.imgur.com/MytxEIs.png)

## Questie version
v5.1.0 (Classic)

**Comment by BreakBB** [comment] 2019-11-10 15:46
Duplicate of #1494 and already fixed with c985f62a13972c27903ec7dbffa608d42b73b542 Will be in the next release 👍

**Closed by BreakBB** 2019-11-10 15:46 UTC
Labels: bug
