### ISSUE TITLE
Tracker growing direction not behaving as expected

### ISSUE THREAD

**Issue by BreakBB** [AeroScripts/QuestieDev#1019] opened 2019-09-17 07:34 UTC
## Bug description

Reported on [Curseforge](https://www.curseforge.com/wow/addons/questie?comment=554) and from different users on Discord.

The behavior of the tracker growing from the middle confuses people a lot. Moreover there is no hint about the feature that it will grow from top -> bottom or vice versa if you move the tracker to an appropriate position.

The gif below shows that even when positioned below the default minimap the tracker grows from the middle.

## Screenshots

![questie_tracker](https://user-images.githubusercontent.com/33514570/65020851-44f2da00-d92e-11e9-9d50-32b5abf8f869.gif)

## Questie version

4.1

**Comment by ShaunDreclin** [comment] 2019-09-17 17:24
#1003

**Comment by ShaunDreclin** [comment] 2019-09-17 17:25
The anchor should probably be changed to a manual setting, my tracker is in the middle of my screen but I still want it to grow downwards

**Comment by AeroScripts** [comment] 2019-09-17 20:31
Yeah, by default it anchors so that it expands down, but dragging it seems to sometimes change the anchor mode. We should be able to fix it by setting the anchor point back when dragging is finished & also make it a setting

**Comment by reaper666735** [comment] 2019-09-18 17:10
i can confirm this is till an issue with v4.1.1, i have to manually drag it back in place after a phew quests lol :p

**Comment by brndd** [comment] 2019-10-05 00:48
This is happening because https://wowwiki.fandom.com/wiki/API_Frame_StartMoving (and consequently `StopMovingOrSizing()`) tries to be smart and automatically choose appropriate anchor points for the frame, losing the original anchor points. There's a helpful description on that wiki page for how to get around the issue.

In my case, after dragging the frame its anchor changes from being `TOPLEFT` anchored on the vanilla quest tracker's `TOPLEFT` to being `RIGHT` anchored to `RIGHT` (ie. the right side of the screen). This leads to the behaviour OP is describing.

Fixing it turned to be more of a pain than I'm willing to go through at 3 AM, so I'm hoping that this comment here will help you lads get it fixed in my stead. In the mean time I will just resort to moving the vanilla quest frame to where I want Questie to be anchored.

**Comment by AeroScripts** [comment] 2019-10-07 08:28
@brndd this should be fixed as of 6548d085dcb15a5124fd7934dd7cd947ca2751a0#diff-281037938e5a72f835059e27d662277f you're right that was the issue

Thanks for posting :D

**Closed** 2019-10-12 16:43 UTC
Labels: bug, tracker
