### ISSUE TITLE
PLEASE PLEASE PLEASE fix ASAP - map icons cannot be enabled???

### ISSUE THREAD

**Issue by modsforall** [AeroScripts/QuestieDev#1721] opened 2020-01-18 15:09 UTC
I clicked the "hide Questie" button on the map.  All the quest icons disappeared.  I then tried to click "show Questie", and I got some error message popup, and no icons showed up!!!?  Clicking the button again now does nothing.

I then tried to go into the /questie options and checked the "enable" checkbox to make them show on the map, but the box just remains clear and cannot be checked.

Please help!  My dreams of power leveling this weekend are broken.  I need this addon back!  Please fix it!!!  Thanks.

**Comment by Gogo1951** [comment] 2020-01-18 15:12
Hey @modsforall ,

Are you on the latest version of Questie? I am not able to reproduce this issue on the latest version.

**Comment by modsforall** [comment] 2020-01-18 15:14
I've updated to the latest one using the Twitch app yes.  Any ideas?

**Comment by Gogo1951** [comment] 2020-01-18 15:15
Sure, just delete the local saved variables that pertain to Questie and it'll work again.

**Comment by Gogo1951** [comment] 2020-01-18 15:18
Dupe of https://github.com/AeroScripts/QuestieDev/issues/1701 

This can be closed.

**Comment by modsforall** [comment] 2020-01-18 15:23
I just checked.  Im using v5.5.1 and updated via the Twitch app.

**Here is the error message:**

Date: 2020-01-18 10:18:52
ID: 1
Error occured in: Global
Count: 1
Message: ...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua line 77:
   attempt to index field 'TrackerHiddenObjectives' (a nil value)
Debug:
   [C]: ?
   ...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:77: ToggleNotes()
   [string "*:OnClick"]:1:
      [string "*:OnClick"]:1
Locals:

**Comment by modsforall** [comment] 2020-01-18 15:29
> 
> 
> Sure, just delete the local saved variables that pertain to Questie and it'll work again.

I just deleted the saved variables using the Twitch App.  I think uninstalled Questie and reinstalled it.  NO DICE.  Getting the same error message.  

Please fix this!!!

**Comment by Gogo1951** [comment] 2020-01-18 15:56
Hey @modsforall,

Delete the file manually.

> C:\Program Files (x86)\World of Warcraft\_classic_\WTF\Account\372809#3\SavedVariables\Questie.lua

Also, man... understand that everyone who works on this is a volunteer. You've reported a duplicate issue. The time it takes to deal with this is time we aren't spending fixing the issue.

**Comment by BreakBB** [comment] 2020-01-18 20:33
@modsforall Just enable the Questie Tracker (once) and you'll be fine. This will be fixed (even more) in the next release

**Closed** 2020-01-18 20:34 UTC
Labels: bug
