### ISSUE TITLE
Quest #786 - Thwarting Kolkar Aggression

### ISSUE THREAD

**Issue by wow-classic** [AeroScripts/QuestieDev#1524] opened 2019-11-11 17:47 UTC
## Description
The target "Attack Plan: Orgrimmar destroyed" is incorrectly marked on the map.
(In the Russian version WoW)

## Wowhead link
https://classic.wowhead.com/quest=786/thwarting-kolkar-aggression

## Screenshots
![Questie - 7](https://user-images.githubusercontent.com/55049724/68608593-5f77a880-04c4-11ea-8d2b-81b7e8e7aceb.png)

## Questie version
Version: 5.1.0

**Comment by BreakBB** [comment] 2019-11-12 10:11
It is correctly marked in our database and in v5.2.0 on the English client:

![image](https://user-images.githubusercontent.com/33514570/68661756-c1272980-053b-11ea-9397-8f56b855413e.png)

Same for v5.1.0:

![image](https://user-images.githubusercontent.com/33514570/68662341-ec5e4880-053c-11ea-8fec-75e74fdff207.png)

The translations are also included for the Russian client:

```lua
[3189] = "План нападения на долину Испытаний",
[3190] = "План нападения на деревню Сен'джин",
[3192] = "План нападения на Оргриммар",
```

Just curious what value has the cluster slider for you?

![image](https://user-images.githubusercontent.com/33514570/68662443-1adc2380-053d-11ea-89d2-4a5ae7dd6d25.png)

**Comment by wow-classic** [comment] 2019-11-13 17:32
![WoWScrnShot_111319_202915](https://user-images.githubusercontent.com/55049724/68788527-a5fc0d00-0654-11ea-9e78-2a5c83da90ef.jpg)

**Comment by BreakBB** [comment] 2020-01-07 16:48
Closing because this couldn't be reproduced. Feel free to respond if this is still an issue.

**Closed by BreakBB** 2020-01-07 16:48 UTC
Labels: need more info, non-reproducable, quest issue
