### ISSUE TITLE
[11] Crown Of The Earth Quest ID 934 Doesn't Show As Completed on My Journey

### ISSUE THREAD

**Issue by SonicMcCall** [AeroScripts/QuestieDev#2386] opened 2020-10-08 07:43 UTC
## Description
In the "My Journey" tab when using Questie, and going onto "Quests by Zone" and setting the region to Teldrassil, there is an incompletable quest. It uses Quest ID 934 and is [11] Crown of the Earth; Fill the amethyst phial and bring it back to Corithras Moonrage in Dolanaar. Please fix it so that it completes when the task objectives are met as it hinders the ability to show that you have completed all quests in Teldrassil. This would just be a quality of life update as it does not change the core functions of the mod.

## Wowhead link
https://classic.wowhead.com/quest=934/crown-of-the-earth

## Screenshots
![WoWScrnShot_100820_152232](https://user-images.githubusercontent.com/72543176/95429159-911b1d00-097c-11eb-953e-6f57009e6864.jpg)

## Questie version
Questie v6.0.5

**Comment by BreakBB** [comment] 2020-10-08 09:54
@SonicMcCall Please run the following command and report the output? I think you didn't complete the quest yet.

`/dump IsQuestFlaggedCompleted(934)`

**Comment by drejjmit** [comment] 2020-10-08 13:17
Will be fixed for next release. Thanks for the report.

I did the chain on a Night Elf and a Human and both goes from [933](https://classic.wowhead.com/quest=933/) -> [7383](https://classic.wowhead.com/quest=7383/) skipping [934](https://classic.wowhead.com/quest=934/).
Both [934](https://classic.wowhead.com/quest=934/) and [7383](https://classic.wowhead.com/quest=7383/) has the 'Oracle Glade moonwell' objective.
I'm guessing [934](https://classic.wowhead.com/quest=934/) got replaced by [7383](https://classic.wowhead.com/quest=7383/) at some point.
[934](https://classic.wowhead.com/quest=934/) doesn't even have a starter NPC in our DB or on Wowhead.
I'm adding it as a duplicate of [7383](https://classic.wowhead.com/quest=7383/).

**Closed by drejjmit** 2020-10-08 13:17 UTC
Labels: Questie - Journey, Questie - Quest Issue
