### ISSUE TITLE
Savage Guard Enchantment Zul'Gurub not available yet

### ISSUE THREAD

**Issue by Djfe** [AeroScripts/QuestieDev#1909] opened 2020-04-28 21:58 UTC
## Description
This will be available in P6, not in P4.
I've had a friend try this at revered and the quest wasn't available, yet. (he'll try again at exalted)

## Wowhead link
https://classic.wowhead.com/item=22635/savage-guard

## Questie version

5.10.2

**Comment by BreakBB** [comment] 2020-05-10 10:20
Duplicate of #1904

**Closed by BreakBB** 2020-05-10 10:20 UTC
Labels: quest issue
