### ISSUE TITLE
[Horde] Alliance Relations Start Not on Map

### ISSUE THREAD

**Issue by pbjtime** [AeroScripts/QuestieDev#726] opened 2019-09-01 15:57 UTC
This quest:
https://classic.wowhead.com/quest=1431/alliance-relations

is not on the world map when it becomes available.

**Comment by BreakBB** [comment] 2019-09-01 20:46
You should try `/reload`. That should fix this issue.

**Comment by BreakBB** [comment] 2019-09-13 15:56
This was probably caused by #860 Closing for now

**Closed by BreakBB** 2019-09-13 15:56 UTC
Labels: quest issue, test again
