### ISSUE TITLE
Different map marks for Seasonal Quests and Repeatable Quests

### ISSUE THREAD

**Issue by DoctorBak** [AeroScripts/QuestieDev#401] opened 2017-02-10 04:21 UTC
I happened to waste a lot of time heading to a marked place and then finding out the quest is only available on weekly or seasonal events, or is some kind of special quest like the cloth donation thing.
I don't think these quests should be indicated in the same way, maybe with a different color.

**Comment by Muehe** [comment] 2017-02-10 14:25
This is a know issue and will be fixed in version 4.0. For the current 3.x DB a fix is unlikely though, as we do not currently have the needed data in the DB. Closing this for now, as duplicate of #350 and #232

**Closed by Muehe** 2017-02-10 14:25 UTC
