### ISSUE TITLE
Item Tooltip quest info is displayed twice

### ISSUE THREAD

**Issue by CodeSpartan** [AeroScripts/QuestieDev#795] opened 2019-09-04 04:43 UTC
When "Enable Tooltips" option is enabled, the tooltip quest info is displayed twice: 
![tooltip displayed twice](https://i.gyazo.com/cd4e98cb19dd432e4b0db281d4362c37.png)

When the option is disabled, the tooltip info gets displayed anyway, but only once.

Addon version: 4.0.16
Game version: 1.13.2.31727

**Comment by AeroScripts** [comment] 2019-09-04 04:53
Hmm, just tested this myself. It's possible you have 2 copies of questie loading

Can you try disabling all other addons and see if that helps? If it fixes it, let me know your addon list, it could be a conflict

**Comment by CodeSpartan** [comment] 2019-09-04 04:58
I've just disabled all addons except Questie, and reproduced the problem successfully.
However, I also noticed that the problem only occurs for this quest. I have another quest with items in my bag, and the problem is not reproducible on that other quest.

No idea why the behavior different, other than Blueleaf Tubers is a dungeon quest, that's the only thing that sets it apart from others that I can think of.

**Comment by AeroScripts** [comment] 2019-09-04 05:07
Oh interesting, ill check the DB, maybe the item ID is added twice or something strange like that


It's probably also a good idea for us to add some code to prevent double-adding, if there is something wrong in the db like that

**Comment by BreakBB** [comment] 2019-09-11 16:50
@CodeSpartan Could you grab the latest release of Questie and test again? We can't reproduce this issue and the data looks alright

**Comment by BreakBB** [comment] 2019-09-19 11:14
So it has only been this particular quests and every other quests looks alright? @CodeSpartan

**Comment by CodeSpartan** [comment] 2019-09-19 14:32
Yep.

**Comment by BreakBB** [comment] 2019-09-19 17:01
Hmmm... So it was some kind of hickup I guess :sweat_smile: Closing this for now, but please report back if you encounter this issue again!

**Closed by BreakBB** 2019-09-19 17:01 UTC
Labels: bug, need more info
