### ISSUE TITLE
The Real Threat showing up as available

### ISSUE THREAD

**Issue by Cerby3BR** [AeroScripts/QuestieDev#1204] opened 2019-10-01 22:55 UTC
The quest the real threat is showing up as available, even though it isn't actually. According to the comments on wowhead it first requires completion of the non-elite Call to Arms quests.

https://classic.wowhead.com/quest=680/the-real-threat#comments

Version 4.1.1

**Comment by BreakBB** [comment] 2019-10-09 19:43
Duplicate of #1062

**Closed by BreakBB** 2019-10-09 19:43 UTC
Labels: quest issue
