### ISSUE TITLE
A Lesson To Learn is shown as available to Warrior

### ISSUE THREAD

**Issue by dsumaneev** [AeroScripts/QuestieDev#1035] opened 2019-09-18 04:33 UTC
## Description
The quest "A Lesson To Learn" (a Druid class quest) is shown as available for Warrior on map and minimap in Darnassus.

## Wowhead link
https://classic.wowhead.com/quest=26/a-lesson-to-learn

## Questie version
4.1.1

**Comment by msayle81** [comment] 2019-09-18 12:19
This is also occurring for Horde Warriors, and showing as available in Thunder Bluff

**Comment by BreakBB** [comment] 2019-09-21 21:47
I can't reproduce this issue with a level 16 warrior 🤔

**Comment by msayle81** [comment] 2019-09-22 10:18
I am a level 30+ warrior...perhaps it incorrectly shows up after hitting a certain level?

**Comment by Zardilann** [comment] 2019-09-24 10:36
Shows up for a level 16 Night Elf Priest in Darnassus.

**Comment by Ben1220** [comment] 2019-09-25 06:23
I also had this issue on a night elf hunter lvl 40+

Interestingly, it only appeared within the last week.  I don't recall if this was immediately after I updated to a new release or not, so it is possible that the error only shows up after hitting a certain level as msayle81 suggested.

**Comment by lifeingote** [comment] 2019-09-30 21:05
35 Night Elf Hunter. also showing up as available (low level) on map.

**Comment by BreakBB** [comment] 2019-09-30 21:13
This should be fixed with v4.1.2 https://github.com/AeroScripts/QuestieDev/releases/tag/v4.1.2 Please notify us if it's not

**Closed by BreakBB** 2019-09-30 21:13 UTC
Labels: quest issue
