### ISSUE TITLE
Reputation level increased - Error (BugSack)

### ISSUE THREAD

**Issue by Djfe** [AeroScripts/QuestieDev#2099] opened 2020-06-28 20:31 UTC
## Bug description
I just got friendly reputation with cenarion hold by turning in the quest Into the Maw of Madness
https://classic.wowhead.com/quest=8306/into-the-maw-of-madness
And BugSack reported an error in the update function of questie.
```
1x Questie\Modules\QuestieReputation.lua:26: attempt to perform arithmetic on a string value
Questie\Modules\QuestieReputation.lua:26: in function `Update'
...rfaceQuestie\Modules\QuestieEventHandler.lua:310: in function <...rfaceQuestie\Modules\QuestieEventHandler.lua:308>
[C]: ?
...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:29: in function <...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:64: in function `Fire'
...\common\Wildpants\libs\AceEvent-3.0\AceEvent-3.0-4.lua:120: in function <...\common\Wildpants\libs\AceEvent-3.0\AceEvent-3.0.lua:119>
```

## Screenshots

![WoWScrnShot_062820_204357](https://user-images.githubusercontent.com/5685512/85957545-8a006e00-b98e-11ea-9370-89cafeb5f7fe.jpg)

## Questie version

5.10.3

**Comment by BreakBB** [comment] 2020-07-01 19:00
Duplicate of #1965 and already fixed :) Will be included in the v6.0.0 update

**Closed by BreakBB** 2020-07-01 19:00 UTC
Labels: bug
