### ISSUE TITLE
Questie for german client/version

### ISSUE THREAD

**Issue by InV111** [AeroScripts/QuestieDev#643] opened 2019-08-14 14:49 UTC
Hello there,

i couldn´t find any other way to contact you so i do it right here. I hope it´s okay.
I´m from Germany and i´m currently running a german client/version for WoW Classic and i need a working version for the official release. Will the latest version work on release or will i get errors,bugs and DC´s ingame?

Thank you.

**Comment by AeroScripts** [comment] 2019-08-14 20:40
The current version shouldn't cause errors or DCs, what errors have you been getting?

In order to properly support german, and other languages, we need to pull in translated NPC names from something like wowhead, without it mob tooltips won't work, but it should function other than that


I'm not sure if we will be able to pull in language data before launch, but if not, it will be shortly after


Also see #633 I'm gonna close this one since it's a duplicate of that

**Closed by AeroScripts** 2019-08-14 20:40 UTC
