### ISSUE TITLE
Break up long lines in quest descriptions

### ISSUE THREAD

**Issue by wodim** [AeroScripts/QuestieDev#1680] opened 2020-01-02 22:39 UTC
![image](https://user-images.githubusercontent.com/1001553/71697649-f7a15800-2db8-11ea-9bb2-e43d93dd85b0.png)

**Comment by Gogo1951** [comment] 2020-01-03 16:38
Seems like a dupe of #1612.

**Comment by BreakBB** [comment] 2020-01-04 14:48
Duplicate of #1093

**Closed by BreakBB** 2020-01-04 14:48 UTC
Labels: feature request
