### ISSUE TITLE
Bug with showing Questie. Now displaying.

### ISSUE THREAD

**Issue by optamystic** [AeroScripts/QuestieDev#1703] opened 2020-01-14 03:20 UTC
## Bug description

Message: ...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:77: attempt to index field 'TrackerHiddenObjectives' (a nil value)
Time: Mon Jan 13 21:19:29 2020
Count: 14
Stack: ...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:77: attempt to index field 'TrackerHiddenObjectives' (a nil value)
...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:77: in function `ToggleNotes'
...Modules\Options\GeneralTab\QuestieOptionsGeneral.lua:42: in function <...Modules\Options\GeneralTab\QuestieOptionsGeneral.lua:41>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[2]"]:9: in function <[string "safecall Dispatcher[2]"]:5>
(tail call): ?
...stie-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:818: in function <...stie-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:639>
[C]: ?
...nterface\AddOns\Atlas\Libs\AceGUI-3.0\AceGUI-3.0.lua:72: in function <...nterface\AddOns\Atlas\Libs\AceGUI-3.0\AceGUI-3.0.lua:70>
...nterface\AddOns\Atlas\Libs\AceGUI-3.0\AceGUI-3.0.lua:290: in function `Fire'
...ic\Libs\AceGUI-3.0\widgets\AceGUIWidget-CheckBox.lua:68: in function <...ic\Libs\AceGUI-3.0\widgets\AceGUIWidget-CheckBox.lua:57>

Locals: <none>

**Comment by optamystic** [comment] 2020-01-14 03:22
Questie is not displaying for me and when I try to display it I get this issue. Twitch app is not working when I right click and select to delete the character variables (yes I logged out) 

Please help! Love this addon

**Comment by BreakBB** [comment] 2020-01-14 08:28
Duplicate of #1701

**Closed by BreakBB** 2020-01-14 08:28 UTC
Labels: bug
