### ISSUE TITLE
A Lesson to Learn (Druid class quest)

### ISSUE THREAD

**Issue by Vindic8ed** [AeroScripts/QuestieDev#1132] opened 2019-09-24 18:36 UTC
## Bug description
I'm was trying to pick up this quest but couldn't find it anywhere.  Looked it up on wowhead and it says it's a druid specific quest (to learn swimming form or something).  I don' think this should pop up as an available quest for a warrior.

## Questie version
4.1.1

**Comment by BreakBB** [comment] 2019-09-24 18:40
Duplicate of #1035 This is already fixed but not released yet. The fix will be included in the next release.

**Closed by BreakBB** 2019-09-24 18:40 UTC
Labels: bug
