### ISSUE TITLE
(Beta) Sometimes (some/all) quests appear as untracked/untrackable

### ISSUE THREAD

**Issue by AriinPHD** [AeroScripts/QuestieDev#460] opened 2017-10-21 19:47 UTC
Version 3.7.0 (Beta) (upgraded from v3.69)
Sometimes, despite eagerly tracking quests from the Quest Log, !Questie refuses to include that quest in its' tracker. I don't see a pattern in type of quest. Just a random quest here and there. Happened more frequently right after update - then zero quests were tracked for a while. The tracker will suddenly start working after a really long time, though.

When the untrackable quest isn't on the main screen tracker (the one floating on-screen) items aren't shown on either of the maps.

**Comment by Muehe** [comment] 2017-11-24 20:31
The untracked quests not showing on the map is actually intended behaviour. If you want to see quest notes regardless of their tracking status use the `/questie showobjectives` command, or the settings UI in 3.7 (the option is called "Always Show Quests" there).

For the quests not tracking when manually `Shift+Click`-ing them I will have to look into that when I have more time. It would be very useful to know some quests this is happening with, so if you ever see that again, please leave the quest name here so I can investigate.

**Comment by Dyaxler** [comment] 2017-11-28 18:43
Could be a "parsing" issue. I recently hit a problem with not being able to track some of the steps in the Shaman Water Totem quest line. Each step had the exact same name followed by (Part 3) and (Part 4) etc.

**Comment by Muehe** [comment] 2017-11-28 18:52
If you are talking about the quest name, it's actually a server side issue. A lot of old databases have these kinds of "Quest x (Part n)" names, and Zoey removed them from our DB some time ago. @AriinPHD Do you remember if this was the case for you?

**Comment by Dyaxler** [comment] 2017-11-28 18:55
...another reason I'm hesitant to put anymore work in Questie. We need a new DB to solve a lot of problems and to implement some decent features that we can't currently. I just wish Blizzard would provide some info to developers as to what is in-store for us in Classic.

**Comment by Muehe** [comment] 2017-12-12 01:01
@AriinPHD I think @ZoeyZolotova found the problem. It appears Questie was suppressing the display of quests in the tracker when they had previously been marked as finished (by `Shift+Click`-ing their starting point on the map). Should be fixed in the latest commit (https://github.com/AeroScripts/QuestieDev/commit/f3edb51f4edf6431ef7b5eefc1a2be4c41220ba5), please retest.

I am leaving this issue open for now due to the bug with quest names which Dyaxler mentioned.

**Comment by Muehe** [comment] 2017-12-12 03:26
Fixed in f3edb51f4edf6431ef7b5eefc1a2be4c41220ba5 and 92b83be148b3ac565945f21fdecf5a5117b85adc. 
The quest name issue has also been fixed in d49438d9546e5d6716ad31ac114447c0e1e99259.

If you continue having problems, please re-open the issue or create a new one.

**Closed by Muehe** 2017-12-12 03:26 UTC
Labels: bug, test again
