### ISSUE TITLE
tag icons in minimap of questie are always in the middle of minimap

### ISSUE THREAD

**Issue by ayrb13** [AeroScripts/QuestieDev#99] opened 2015-05-17 04:05 UTC
While i was doing quests in Tanaris, i find that all minimap icons of questie are always in the middle of minimap. When I click Toggle Questie, they disappeared and they can not show themself when i click Toggle again.

**Comment by AeroScripts** [comment] 2015-05-17 04:26
I had this happen once at random. I'm not sure what causes it, but when it happens again I'll be sure to try to track down the cause.

What makes it hard is last time it happened, it went away with /reload (You might try that until it is fixed)

**Comment by Schaka** [comment] 2015-05-17 19:15
They also tend to disappear sometimes. It's really weird, I think it happens when you die. I'm not sure how long this has been going on, but it needs more testing.

**Comment by nycter79** [comment] 2015-05-18 22:01
OT: when i downloaded questie version 2.x notes aren't showing on minimap anymore. I also download metamap instead of cartographer. Dont you guys know what should be cause of this? or did u turned off minimap notes in 2.x ?

**Comment by nathanpaulyoung** [comment] 2015-05-20 02:34
@nycter79, @AeroScripts offers a solution above. Simply /reload whenever you log in or whenever the icons fail to display correctly. This is a known bug.

**Comment by AeroScripts** [comment] 2015-05-25 07:11
Fixed as of v2.0.10

**Closed by AeroScripts** 2015-05-25 07:11 UTC
Labels: bug, test again
