### ISSUE TITLE
{Classic} Repeat quests not tracking

### ISSUE THREAD

**Issue by OrnoCav** [AeroScripts/QuestieDev#1557] opened 2019-11-18 02:51 UTC
Repeatable quests (such as [60] Winterfall Intrusion) are not updating in the tracker unless the UI is reloaded

**Comment by BreakBB** [comment] 2019-11-18 07:21
Duplicate of #1433 There is already a PR for this which we're eager to test. It will be fixed in the next release! You can also watch the linked issue for a patched version.

**Closed by BreakBB** 2019-11-18 07:21 UTC
