### ISSUE TITLE
v4.1.2 - Available Quests in Quest By Zone missing

### ISSUE THREAD

**Issue by Chrisisar** [AeroScripts/QuestieDev#1282] opened 2019-10-12 08:57 UTC
## Bug description
After updating Questie to v4.1.2 Available Quests in Quest by Zone tab stopped working and displays 0 for all zones. Completed quests list is fine.
Downgrading to v4.1.1 fixes the issue.

## Screenshots
v4.1.2
![obraz](https://user-images.githubusercontent.com/8448803/66698478-c6941880-ecde-11e9-81a7-87f6178f8590.png)

v4.1.1
![obraz](https://user-images.githubusercontent.com/8448803/66698456-8df43f00-ecde-11e9-8144-9579302f6da5.png)

## Questie version
4.1.2 BETA 121 dff5a12

**Comment by BreakBB** [comment] 2019-10-12 16:27
Duplicate of #1239 and already fixed. Will be included in the upcoming version

**Closed by BreakBB** 2019-10-12 16:27 UTC
Labels: bug
