### ISSUE TITLE
Tooltip errors

### ISSUE THREAD

**Issue by Nillx** [AeroScripts/QuestieDev#1266] opened 2019-10-09 16:11 UTC
```
2x Questie\Modules\QuestieTooltips.lua:80: Usage: UnitGUID("unit")
[C]: in function `UnitGUID'
Questie\Modules\QuestieTooltips.lua:80: in function <Questie\Modules\QuestieTooltips.lua:75>
[C]: ?
[C]: ?
[C]: ?
[C]: in function `SetUnit'
FrameXML\UnitFrame.lua:291: in function `UnitFrame_UpdateTooltip'
FrameXML\UnitFrame.lua:277: in function `UnitFrame_OnEnter'
ShadowedUnitFrames\modules\units.lua:530: in function `OnEnter'
ShadowedUnitFrames\modules\units.lua:517: in function <ShadowedUnitFrames\modules\units.lua:515>

Locals:
(*temporary) = nil
```

**Comment by BreakBB** [comment] 2019-10-09 17:15
Please use the issue template next time!

Also duplicate of #1259

**Closed by BreakBB** 2019-10-09 17:15 UTC
Labels: bug
