### ISSUE TITLE
Questie randomly expanding after being collapsed

### ISSUE THREAD

**Issue by jacobwlaird** [AeroScripts/QuestieDev#2007] opened 2020-06-12 01:50 UTC
## Bug description

Questie is collapsed out of combat and most of the time it will not expand but sometimes after entering and exiting combat it will expand and stay expanded. Recently noticed in BWL. 

Settings:
![Annotation 2020-06-11 204643](https://user-images.githubusercontent.com/28605946/84456064-b1cca380-ac24-11ea-9489-e268a6798a34.png)
![Annotation 2020-06-11 204622](https://user-images.githubusercontent.com/28605946/84456065-b2fdd080-ac24-11ea-8863-e8c1305fb6cc.png)

## Questie version
5.10.3

**Comment by Dyaxler** [comment] 2020-06-12 14:13
This is not a bug... this is a feature of Deadly Boss Mods.

![image](https://user-images.githubusercontent.com/17400948/84511958-2848c000-ac7c-11ea-9357-53eab86a7505.png)

**Comment by Dyaxler** [comment] 2020-06-12 14:13
The Blizzard QuestWatch frame is tied to the Questie Tracker.

**Comment by Dyaxler** [comment] 2020-06-12 14:46
Actually we just checked the code. It's not working as "intended". DBM is pushing a patch today that will address it until a new public function on our end is available.

**Comment by Dyaxler** [comment] 2020-06-12 15:04
Fixed in 1ada99972c0cb18b0261add0181b30e8ea925236

**Closed** 2020-07-01 18:59 UTC
Labels: bug
