### ISSUE TITLE
Quest Root Samples too many objectives on map causing freeze

### ISSUE THREAD

**Issue by sipertruk** [AeroScripts/QuestieDev#518] opened 2018-10-01 10:07 UTC
Root Samples is an herbalist lvl 16 quest, the objectives are in herb nodes.
The problem is that sprocket type nodes are shown all over the continent resulting in a 10s freeze at every refresh. 
It's too many to be shown. Beside herb node locations are different across different server database so it's pointless to show any.

**Comment by Xaero252** [comment] 2019-01-16 01:57
This issue also affects the Mage class quest "Items of Power" which requires Jade. It populates the map with *THOUSANDS* of nodes. This actually results in the client becoming unresponsive for several seconds on login, and then for several seconds every couple of ticks.

**Comment by AeroScripts** [comment] 2019-01-16 03:58
I'm going to do a few things, first off there is some code in the main branch to handle this situation that hasn't been ported into the TBC branch, and also im going to put a limit on the max number of points shown per objective, no quest objective needs that many points for it's self

**Comment by BreakBB** [comment] 2019-09-04 15:59
Duplicate of #504

**Closed by BreakBB** 2019-09-04 15:59 UTC
