### ISSUE TITLE
Quest# 992 

### ISSUE THREAD

**Issue by Nimbix-wow** [AeroScripts/QuestieDev#956] opened 2019-09-13 09:28 UTC
## Description

There is no marker showing where to get the questitem needed (Sandsorrow Watch).

## Wowhead link

https://classicdb.ch/?quest=992

## Questie version

v4.0.18

**Comment by BreakBB** [comment] 2019-09-15 16:16
Duplicate of #873

**Closed by BreakBB** 2019-09-15 16:16 UTC
Labels: duplicate, quest issue
