### ISSUE TITLE
"quests by zone" broken 4.1.0

### ISSUE THREAD

**Issue by ssateneth** [AeroScripts/QuestieDev#1007] opened 2019-09-16 19:11 UTC
## Bug description

The player journey window is broken. . None of the dropboxes in quests by zone or advanced zone work the advanced search works, but thats it. if you click the empty area, it gives a dropdown, weird behavior

## Screenshots

https://i.imgur.com/Jk8xVk5.gifv

## Questie version

4.1.0

**Comment by AeroScripts** [comment] 2019-09-16 19:58
Really strange, can you post your mod list and test if this happens with just questie? Will do some testing tonight

**Comment by ssateneth** [comment] 2019-09-16 20:00
This has some bad interaction with AuctionMaster addon, maybe something to do with the libuidropdown library, because I always get these errors when i relodui with aucitonmaster running.

Message: Deferred XML Node object named Lib_UIDropDownMenuButtonTemplate already exists
Time: Mon Sep 16 15:00:03 2019
Count: 5

**Comment by AeroScripts** [comment] 2019-09-16 20:01
Oh jeez that makes sense, ill push a fix shortly

**Comment by Muehe** [comment] 2019-10-06 21:25
@AeroScripts This is fixed?

**Comment by BreakBB** [comment] 2019-10-29 16:42
This can't be reproduced and since there hasn't been any response I will close this.

**Closed by BreakBB** 2019-10-29 16:42 UTC
Labels: bug, journey, non-reproducable, test again
