### ISSUE TITLE
IronForge Quests

### ISSUE THREAD

**Issue by TheZikk** [AeroScripts/QuestieDev#687] opened 2019-08-29 18:41 UTC
Hi,

I have quests visible on the map in all capitals except IF. Any fix?

**Comment by Booom3** [comment] 2019-09-01 08:13
I can confirm. Also here's an example of a quest that does not work:
![image](https://user-images.githubusercontent.com/270995/64073640-1d9adc80-cca1-11e9-965c-401b4173d5cb.png)

**Comment by AeroScripts** [comment] 2019-09-01 08:24
Are you on the latest build, and can you try with only questie enabled? IF icons seem to be working for me, it could be an addon conflict. If it is, should be simple to fix just need to figure out what addon and do some testing

**Comment by TheZikk** [comment] 2019-09-01 08:56
Thank you for the replies.
1. I will try to install the latest build.  I am new here and will all my completed quests will wipe off if I delete old addon and install a new one. 
2. I have disabled all addons and still no changes.

**Comment by TheZikk** [comment] 2019-09-01 09:16
On the latest build and still does not work

**Comment by AeroScripts** [comment] 2019-09-01 09:37
I will test myself and see what's up, it's probably something simple like an ID mismatch, though what's weird is some users aren't having the problem

**Comment by AeroScripts** [comment] 2019-09-01 10:06
We've talked on discord but it should be posted here too

it's not a problem with ironforge in general but these quests specifically, seems to be bad db data

**Comment by BreakBB** [comment] 2019-09-09 18:04
[Save Techbot's Brain!](https://classic.wowhead.com/quest=2922/save-techbots-brain) looks good in out data and so does the prequest for this.

What else quests are/were bugged? We need more information to check our data!

**Comment by iBaldv5** [comment] 2019-09-14 11:52
I ran into this issue as well and I've confirmed the breadcrumb quest [Tinkmaster Overspark](https://classic.wowhead.com/quest=2923/tinkmaster-overspark) is not required for [Save Techbot's Brain](https://classic.wowhead.com/quest=2922/save-techbots-brain). There is also a comment on [Tinkmaster Overspark](https://classic.wowhead.com/quest=2923/tinkmaster-overspark) mentioning that they believe this quest is no longer needed for [Save Techbot's Brain](https://classic.wowhead.com/quest=2922/save-techbots-brain).

I tested your command on another same issue [thread](https://github.com/AeroScripts/QuestieDev/issues/825) and confirmed it comes back false as I have not completed [Tinkmaster Overspark](https://classic.wowhead.com/quest=2923/tinkmaster-overspark). Both [Tinkmaster Overspark](https://classic.wowhead.com/quest=2923/tinkmaster-overspark) and [Save Techbot's Brain](https://classic.wowhead.com/quest=2922/save-techbots-brain) are available for me to pick up on my Level 24 character.

**Comment by BreakBB** [comment] 2019-09-14 11:58
@iBaldv5 Thank you very much for your report! As expected the prequest is not required and has just been fixed in our data. The fix will be included in the next release.

**Closed** 2019-09-14 11:57 UTC
Labels: database, need more info
