### ISSUE TITLE
The Tome of Divinity SW

### ISSUE THREAD

**Issue by Terridol** [AeroScripts/QuestieDev#720] opened 2019-09-01 03:00 UTC
Tome of Divinity paladin quest in Stormwind still shows on map as a ! after completing it.

![Capture](https://user-images.githubusercontent.com/17102611/64071219-b5b1ab00-cc3a-11e9-876e-48dfc5ff5c24.PNG)

**Comment by BreakBB** [comment] 2019-09-01 17:24
Duplicate of #703

**Closed** 2019-09-05 20:18 UTC
Labels: duplicate
