### ISSUE TITLE
Quest Icons weirdly displayed on screen at random spots v4.2.1

### ISSUE THREAD

**Issue by EvilTuinhekjeNL** [AeroScripts/QuestieDev#1303] opened 2019-10-13 09:09 UTC
## Bug description
With the newest Questie version 4.2.1, it display the nearby Quest icons on your screen in a very weird way, and they also stick to the camera position and move around a lot

## Screenshots
![questie](https://user-images.githubusercontent.com/3717099/66713327-bb59ef00-eda9-11e9-8847-44417cd2c9b7.png)

## Questie version
Questie-v4.2.1.zip

**Comment by BreakBB** [comment] 2019-10-13 09:16
Duplicate of #1296 and not a bug, but a new feature!

**Closed by BreakBB** 2019-10-13 09:16 UTC
Labels: bug
