### ISSUE TITLE
Broken quests

### ISSUE THREAD

**Issue by Sparh4wk** [AeroScripts/QuestieDev#85] opened 2015-05-10 06:42 UTC
Some quests are broken.
Example The Guns of Northwatch

if you hover mouse over Theramore Marine for first time it gives you this error:
![1](https://cloud.githubusercontent.com/assets/7014826/7553298/6277f670-f6f0-11e4-8802-953ce51c39e6.png)

and there is nothing on tooltip about quest

![2](https://cloud.githubusercontent.com/assets/7014826/7553300/7dc741ba-f6f0-11e4-82b9-07282e80b046.png)

**Comment by Sparh4wk** [comment] 2015-05-11 15:55
Today after returning a quest.. it gives me this error
![1](https://cloud.githubusercontent.com/assets/7014826/7569073/bae1791e-f806-11e4-82bd-eb8ba78f53ae.png)

And the quest question mark was still on minimap and map as well :(
/questie q remove that mark, but still..

**Comment by AeroScripts** [comment] 2015-05-11 19:28
That's the craziest error report I've ever seen.. It shouldn't be possible for QuestieTracker to ever be nil... Unless the file QuestieTracker.lua is missing or something

Thanks for reporting all these, ill look into it shortly, but man that's strange.

**Comment by AeroScripts** [comment] 2015-05-13 15:46
Yeah this was caused by a broken commit to master. Should be fixed in v2.0.7

**Closed by AeroScripts** 2015-05-13 15:46 UTC

**Comment by Sparh4wk** [comment] 2015-05-13 15:56
ok.. btw today in the morning the checked state was working somehow with tracker.. after these 3 last commits, it seems broken again :(
