### ISSUE TITLE
Available quests: still completely broken

### ISSUE THREAD

**Issue by AeroScripts** [AeroScripts/QuestieDev#60] opened 2015-04-21 10:04 UTC
Apparently, lots is wrong with them. Wrong level range, appearing again every quest update (even if they've already been completed OR are currently in the log)

**Comment by malloot** [comment] 2015-04-22 12:45
Also shows all quests in horde faction quest hubs as alliance all the time

**Comment by Schaka** [comment] 2015-04-26 17:15
Duplicate of #66

**Closed by Schaka** 2015-04-26 17:15 UTC
Labels: bug
