### ISSUE TITLE
Reputation error gaining friendly with Booty Bay after quest turn-in

### ISSUE THREAD

**Issue by rbpaiett** [AeroScripts/QuestieDev#2039] opened 2020-06-18 04:15 UTC
## Bug description

I turned in the quest Venture Company Mining, changed from neutral to friendly with Booty Bay and got this error:

1x Questie\Modules\QuestieReputation.lua:26: attempt to perform arithmetic on a string value
Questie\Modules\QuestieReputation.lua:26: in function `Update'
...rfaceQuestie\Modules\QuestieEventHandler.lua:310: in function <...rfaceQuestie\Modules\QuestieEventHandler.lua:308>
[C]: ?
...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:29: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:64: in function `Fire'
DataStore\libs\AceEvent-3.0\AceEvent-3.0-4.lua:120: in function <DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

**Comment by BreakBB** [comment] 2020-06-18 10:59
Duplicate of #1965 and already fixed. Will be included in the upcoming v6.0.0 release :+1:

**Closed by BreakBB** 2020-06-18 10:59 UTC
Labels: bug
