### ISSUE TITLE
QuestieAstro.lua:563 indx (a nil value)

### ISSUE THREAD

**Issue by Pr1mu5** [AeroScripts/QuestieDev#158] opened 2015-10-23 13:39 UTC
https://i.gyazo.com/984bd60d9841e9a984761011a0b2acd3.png

happend after i killed Arikara twice ( a second time after the quest was complete)
http://db.vanillagaming.org/?quest=5088

**Comment by forsethc** [comment] 2015-11-19 05:54
I "fixed" this by adding:

    if indx == nil then
        break;
    end

at line 564 in QuestieAstro.lua

I was getting this same error when mousing over the bear/druid while escorting during this quest: http://db.vanillagaming.org/?quest=5321

I say "fixed" in quotes because I only added this check to silence the really annoying error.  This "fix" just skips the rest of the inner-most for-loop... I don't know what sort of side effects that will have

The real fix should be something like: (this is psudo-code... I don't know lua)

    if indx == nil then
        local countstr = nil;
        local namestr = desc;
    else
        -- original code
        local countstr = string.sub(desc, indx+2);
        local namestr = string.sub(desc, 1, indx-1);
    end

then, around line 575, replace:

    GameTooltip:AddLine("   " .. namestr .. ": " .. countstr, 1, 1, 0.2)

with something like:

    if countstr == nil then
        GameTooltip:AddLine("   " .. namestr, 1, 1, 0.2)
    else
        -- original code
        GameTooltip:AddLine("   " .. namestr .. ": " .. countstr, 1, 1, 0.2)
    end

that way the rest of the code gets executed.

**Comment by forsethc** [comment] 2015-11-19 06:00
Also, this appears to be a duplicate of https://github.com/AeroScripts/QuestieDev/issues/116

**Comment by Logonz** [comment] 2015-11-19 09:44
Problem we have atm is that i go to school full speed and work full time i haven't got time to work on questie at all! Im trying every now and then to but if i do i work on 3.0

**Comment by Pr1mu5** [comment] 2016-01-20 13:20
happend again while mouseover a mob
http://i.imgur.com/pEm8yNg.png

seems to be a compatibility problem with tinytip

**Closed** 2016-03-31 06:08 UTC
