### ISSUE TITLE
quest linking in chat broke in newest update

### ISSUE THREAD

**Issue by x003** [AeroScripts/QuestieDev#385] opened 2017-01-28 08:39 UTC
When you shift click a quest to chat from your log or ctrl click to paste current quest status it only links the quest name now and in bracket [ ]  instead of the level of the quest, quest name, and quest status

**Comment by Dyaxler** [comment] 2017-01-28 19:14
You'll have to be more specific? What broke exactly? Is it throwing an error? Does it cause other AddOns to fail?

Reason I'm asking is that technically Quest Linking was introduced in BC. It wasn't available in Vanilla because we can't query Server Side data like we can with Items. However, using a clever method of spoofing the item Hyperlink Reference API we can inject Quest data in chat but the mod you're using has to be able to handle the custom Hyperlink reference that gets passed under the hood. ShaguQuest is the only mod that I know of off the top of my head that does it but their method only shows you details of the quest if you're actually on said quest. If not then it simply displays the fact that you're not on it.

Its still in my local Dev build and I haven't submitted it yet but I have Quest Linking working in Questie and it will be compatible with ShaguQuest. Their mod will continue to work the way it was designed by clicking on links submitted by Questie users in chat. On the flip side if you're using Questie to click the link, we pull the quest description directly from Questies database; it doesn't matter if you're on the quest or not. This is more Blizzard like that some players are familiar with.

So I need to know which version you're using. The actual release package or did you sync your Questie install with the latest commit from GitHub?

Or you can wait until I release v3.70 and retest.

**Comment by x003** [comment] 2017-01-29 00:00
before Questie v3.69 on the release page

this is what you see when you shift click a quest from your quest log with the chat open
![1](https://cloud.githubusercontent.com/assets/12950645/22400752/d63e481c-e58b-11e6-99f0-325b765c9a01.PNG)

this is what you see when you ctrl click
![2](https://cloud.githubusercontent.com/assets/12950645/22400765/f8c22cf0-e58b-11e6-8dc9-9cb385f11405.PNG)

with Questie v3.69 on the release page

this is what happens when you shift click and ctrl click
![3](https://cloud.githubusercontent.com/assets/12950645/22400766/0b6659a8-e58c-11e6-9fe8-db2bcde4b09b.PNG)

**Comment by Dyaxler** [comment] 2017-01-29 00:34
Oh snap!

My bad! I'll double check that.

**Comment by Dyaxler** [comment] 2017-01-29 07:03
Yep. Found the bug. Fixed in next release.

**Comment by Muehe** [comment] 2017-09-27 21:59
New beta release is out. It can be downloaded [here](https://github.com/AeroScripts/QuestieDev/releases/tag/v3.7.0-beta).

**Closed by Muehe** 2017-09-27 21:59 UTC
Labels: fix will be in next release, resolved
