### ISSUE TITLE
Add The Weathered Grave starter quest

### ISSUE THREAD

**Issue by beren12** [AeroScripts/QuestieDev#264] opened 2016-07-15 18:01 UTC
The grave isn't on quest for some reason:

http://db.vanillagaming.org/?object=61#starts

**Comment by Muehe** [comment] 2016-07-25 03:08
Duplicate of #251

**Comment by ZoeyZolotova** [comment] 2016-11-20 09:30
It's not a duplicate issue, but it is related. Many of the "object" type quest starters (such as the Wanted Poster for Hogger) don't appear in Questie's data at all. A Weathered Grave does appear, but for some reason despite that, none of the available quests with an "object" startedType seem to work.

This issue can be bandaid-fixed by changing `['startedType']="object",` to `['startedType']="monster",` on line 18146 of addendum.lua

**Comment by AeroScripts** [comment] 2016-11-20 19:22
As stated in the other issue, we're currently in the process of overhauling the whole DB for 4.0. This is one of the many things that will be fixed once that reaches the master branch.

**Closed** 2017-01-15 19:12 UTC
