### ISSUE TITLE
Not showing quests above char level

### ISSUE THREAD

**Issue by mpGomes** [AeroScripts/QuestieDev#278] opened 2016-10-21 20:58 UTC
I've messed around with the filters and tried to default and re-install but can't get the addon to show quests above the char level.

**Comment by Muehe** [comment] 2016-10-27 18:28
Use `/questie maxlevel` until the chat message says it has been turned off.

>Questie Slash Commands - use "/questie" to show the help menu in game.
> - maxlevel: Toggles the maxlevel filter on or off - please use setmaxlevel to adjust settings.
> - minlevel: Toggles the minlevel filter on or off - please use setminlevel to adjust settings.
> - setmaxlevel: Hides quests until <X> levels above players level (default=3).
> - setminlevel: Hides quests <X> levels below players level (default=5).

[FAQ](https://github.com/AeroScripts/QuestieDev/blob/master/Readme%20%26%20FAQ.txt)

**Comment by HanFox** [comment] 2016-11-14 04:55
I'm not entirely sure if this is the same issue as @mpGomes, but it sounds similar.

When /questie maxlevel is enabled I can't see any quests to pickup on the map at all (doesn't matter what the /questie setmaxlevel is).

I'm using the latest 3.2 release (even though in game it shows as 3.1).

**Comment by AeroScripts** [comment] 2016-11-14 14:52
I will see if I can reproduce it

**Comment by HanFox** [comment] 2016-11-15 01:34
I upgraded to 3.3 (not that you appeared to do any work in regards to this issue there) and I've been fiddling around a bit (with a clean Addons folder and WTF folder) and have discovered:

With my current level as 17:-
setmaxlevel = 1 -- quests appear up to 21;
setmaxlevel = 2 -- quests appear up to 20;
setmaxlevel = 3 -- quests appear up to 20;
setmaxlevel = 4 -- quests appear up to 20;
setmaxlevel = 5+ -- all available quests disappear.

As a tiny aside I think you're missing updating https://github.com/AeroScripts/QuestieDev/blob/4abac2138af64534916bd26983bbb83ef968cf11/!Questie/Questie.lua#L19 when you update? It still reports 3.1 ingame due to it.

**Comment by AeroScripts** [comment] 2016-11-15 18:35
Thanks for that, we really need to make an update script. I'll edit the release real quick to fix that.

That's really strange, ill look into this shortly.

**Comment by AeroScripts** [comment] 2016-12-14 07:00
Should be fixed now, closing this

**Closed by AeroScripts** 2016-12-14 07:00 UTC
