### ISSUE TITLE
Crashes the game often.

### ISSUE THREAD

**Issue by RobGFour** [AeroScripts/QuestieDev#429] opened 2017-05-02 10:44 UTC
Love the Addon!

However, it does cause the game to crash quite often for me...1-2 times an hour. Opening the Log will sometimes trigger a crash.

Sometimes a yellow ? will remain on the minimap after a quest has been completed, hovering the cursor over it will cause an in-game red error message. I have to log out to clear the ?.

I tried renaming WTF folder, as well as deleting WDB & Cache. Ran it without other Addons enabled.

I would really like to find a solution. Is there anything I can provide to help?

**Comment by Muehe** [comment] 2017-05-02 11:38
Which version of Questie are you using, and, if you can reproduce it, what exactly does the red error message say?

**Comment by RobGFour** [comment] 2017-05-02 15:59
v3.69

![questie error](https://cloud.githubusercontent.com/assets/28295995/25626859/d2d32066-2f2e-11e7-91dd-1788ae153546.jpg)

**Comment by Bifidus** [comment] 2017-05-02 22:29
I also have a ton of crashs with that addon - it took me a long time to realize questie was the culprit (once i desativated it, no more crash).
Crashes appear in places with a lot of quests (eg : the nesingwary expedition in STV, the refuge in Un'Goro - for that one, i can't even log in the game, it's instant crash).

**Comment by Muehe** [comment] 2017-05-02 22:41
The crashes with the Nesingwary quests (Stranglethorn Pages) and similar quests, which are drawing high amounts of notes, should be gone in the next release. Anyway, it might help if you set the addon memory to 0 (unlimited) in the login screen. As for the error message I'd ask @Dyaxler if it is one he knows about?

If you want to see if the problem is still present in our current build, you can download it from [here](https://github.com/Dyaxler/QuestieDev/tree/Version3.70) (Click "Clone or Download", then "Download ZIP").

**Comment by skink-in-trees-shade** [comment] 2017-05-07 14:39
@RobGFour, the issue has been fixed in #422.

**Comment by Muehe** [comment] 2017-05-07 17:18
@skink-in-trees-shade Thanks for letting me know! We should really push that 3.7 release...

**Comment by Muehe** [comment] 2017-09-27 21:55
New beta release is out. It can be downloaded [here](https://github.com/AeroScripts/QuestieDev/releases/tag/v3.7.0-beta).

**Closed by Muehe** 2017-09-27 21:55 UTC
Labels: bug, fix will be in next release, resolved
