### ISSUE TITLE
Quest "The Algaz Gauntlet" is not shown on map and minimap

### ISSUE THREAD

**Issue by Amazonka** [AeroScripts/QuestieDev#1265] opened 2019-10-09 15:18 UTC
## Description

Quest "The Algaz Gauntlet" doesn't appear on map and minimap. Alliance, Night Elf Hunter.

## Wowhead link

https://classic.wowhead.com/quest=455/the-algaz-gauntlet

## Questie version

4.1.2

**Comment by BreakBB** [comment] 2019-10-16 08:13
@Amazonka Could you run `/dump IsQuestFlaggedCompleted(468)` and report the result?

**Comment by fireboy92k** [comment] 2019-10-19 14:04
running that script now that I'm done shows true, but I also noted the same thing last night for this quest line.  It did not show on my map or minimap, nor did the follow on quest.

**Comment by BreakBB** [comment] 2019-10-29 22:46
@fireboy92k Do you remember which version of Questie you where using?

I still can't find a reason why the quest shouldn't show up. Our data looks fine.

**Comment by fireboy92k** [comment] 2019-10-30 19:16
No, I should have written that down.   Apologies.  It was pre-V5 though.  May just have to mark it as un-reproducable since no way to give the quest back now!

**Comment by BreakBB** [comment] 2019-10-30 19:26
@fireboy92k Thanks for coming back to this. Yes, I will simply close the issue for now. I might be able to test it at a later point.

**Closed by BreakBB** 2019-10-30 19:26 UTC
Labels: non-reproducable, quest issue
