### ISSUE TITLE
Invalid Quest Marker: The Mystery of Morrowgrain

### ISSUE THREAD

**Issue by proksch** [AeroScripts/QuestieDev#1178] opened 2019-09-29 20:05 UTC
## Description

The world map is showing an available quest for [The Mystery of Morrowgrain](https://classic.wowhead.com/quest=3791/the-mystery-of-morrowgrain), but the quest giver does not provide any... it seems that this is a chain, I am not sure whether I did the pre-quest.

## Wowhead link

[The Mystery of Morrowgrain](https://classic.wowhead.com/quest=3791/the-mystery-of-morrowgrain)

## Questie version

4.1.1

**Comment by BreakBB** [comment] 2019-09-30 19:54
This is a duplicate of #885 and in part fixed with v.4.1.2 https://github.com/AeroScripts/QuestieDev/releases/tag/v4.1.2

**Closed by BreakBB** 2019-09-30 19:54 UTC
Labels: quest issue
