### ISSUE TITLE
Breadcrumb quests still show even if unavailable

### ISSUE THREAD

**Issue by jmell** [AeroScripts/QuestieDev#1217] opened 2019-10-03 08:20 UTC
## Description

E.g., quests like "The Hermit" (Duskwood) still show as available even if they are not (like if you talked to the Hermit before getting the quest).

## Wowhead link

https://classic.wowhead.com/quest=165/the-hermit

## Questie version

Version 
4.1.1 BETA

**Comment by BreakBB** [comment] 2019-10-13 18:02
Duplicate of #1173

**Closed by BreakBB** 2019-10-13 18:02 UTC
Labels: quest issue
