### ISSUE TITLE
LUA error from tracker when logging on

### ISSUE THREAD

**Issue by Painstormx** [AeroScripts/QuestieDev#1952] opened 2020-05-17 11:57 UTC
Questie v5.10.3

I've had this for a while.
Sometimes when logging on, I get the error below.
I can't find any pattern in it. It's happening on different chars and not every time I log on.

Date: 2020-05-17 13:44:35
ID: 1
Error occured in: Global
Count: 1
Message: ...ce\AddOns\Questie\Modules\Tracker\QuestieTracker.lua line 791:
   'for' limit must be a number
Debug:
   [C]: ?
   ...ce\AddOns\Questie\Modules\Tracker\QuestieTracker.lua:791:
      ...ce\AddOns\Questie\Modules\Tracker\QuestieTracker.lua:783
   ..\SharedXML\C_TimerAugment.lua:16:
      ..\SharedXML\C_TimerAugment.lua:14
Locals:

**Comment by Gogo1951** [comment] 2020-05-17 14:56
Hey @Painstormx ,

Can you include the entire error message next time it comes up? This will help us troubleshoot the issue. Thanks!

**Comment by Painstormx** [comment] 2020-05-18 16:30
There aren't really anything else in the message other than a list of addons, but here we go:
Date: 2020-05-17 18:19:28
ID: -2
Error occured in: Global
Count: 1
Message: ...ce\AddOns\Questie\Modules\Tracker\QuestieTracker.lua line 791:
   'for' limit must be a number
Debug:
   [C]: ?
   ...ce\AddOns\Questie\Modules\Tracker\QuestieTracker.lua:791:
      ...ce\AddOns\Questie\Modules\Tracker\QuestieTracker.lua:783
   ..\SharedXML\C_TimerAugment.lua:16:
      ..\SharedXML\C_TimerAugment.lua:14
Locals:

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AdvancedInterfaceOptions, v1.3.4
  Altoholic, vClassic v1.13.4-014
  Armory, vv1.7.0
  Atlas, vv1.47.00.11303.00
  AtlasClassicWoW, vv1.47.00.11303.00
  AtlasLootClassic, vv1.5.1
  AtlasLootClassicData, vv1.5.1
  AtlasLootClassicDungeonsAndRaids, vv1.5.1
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BadBoy, vv1-classic
  Bazooka, vv2.9.3
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  BrokerBagInfo, vv1.20
  ClassicAuraDurations, v1.13.55
  ClassicCastbars, vv1.3.6
  ClassicCastbarsOptions, v
  DataStore, vv1.13.013
  DataStoreAuctions, vv1.13-013
  DataStoreCharacters, vv1.13-013
  DataStoreContainers, vv1.13-013
  DataStoreCrafts, vv1.13-013
  DataStoreInventory, vv1.13-013
  DataStoreMails, vv1.13-013
  DataStoreQuests, vv1.13-013
  DataStoreReputations, vv1.13-013
  DataStoreStats, vr32
  DBMCore, v1.13.45
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Decursive, v2.7.7
  DejaClassicStats, v1304b003
  Details, v
  DetailsTinyThreat, v
  Dominos, v8.3.1
  DominosCast, v
  DominosProgress, v
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  GatherMate2, v1.45.4
  GroupCalendar, v
  GuildRosterManager, v1.88
  HealBot, v1.13.2.10
  HealBotTips, v1.13.2.10
  iFriends, v1.13.1
  iGuild, v1.13.0
  iMoney, v1.13.0
  InFlightLoad, v1.13.001
  Informant, v8.2.6374 (SwimmingSeadragon)
  ItemTooltipProfessionIcons, v1.1.6
  KuiMedia, v
  KuiNameplates, v
  KuiNameplatesCore, v
  LeatrixMaps, v1.13.59
  LetMeCast, v1.3
  MissingTradeSkillsList, v1.13.43
  MobInfo2Classic, v11302.04
  ModernTargetFrame, v1.4
  NefHunterHelper, v1.0
  NovaWorldBuffs, v1.55
  NugRunning, v1.13.36
  OmniCC, v8.3.1
  OneBag3, vv3.3.13
  Pawn, v2.3.25
  Postal, vv3.6.0
  Questie, v5.10.3
  RollTrackerClassic, v1.92
  Scrap, v8.3.2
  SexyReputation, v1.0.99d861c298fd6d311edd609164198a3d2f83b056
  SkilletClassic, v1.06
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TellMeWhen, v8.7.4
  TipTop, v3.0.1
  TomTom, vv11303-1.0.9
  tullaRange, v8.3.1
  VendorPrice, v1.3.0
  WeakAuras, v2.17.4
  WeaponSwingTimer, v4.0.2
  WhatsTraining, v1.8.4
  BlizRuntimeLib_enUS v1.13.4.11304 <none>
  (ck=993)

**Comment by drejjmit** [comment] 2020-05-18 18:02
Duplicate of #1868

**Closed** 2020-05-19 09:30 UTC
Labels: bug
