### ISSUE TITLE
The Captain's Chest

### ISSUE THREAD

**Issue by AlistairJM** [AeroScripts/QuestieDev#1234] opened 2019-10-06 11:54 UTC
The Captain's Chest (https://classic.wowhead.com/quest=614/the-captains-chest) in Booty Bay was not displaying on the map for me, even though I could pick it up at level 35 in-game.

**Comment by BreakBB** [comment] 2019-10-09 19:54
Please use the issue template next time!

This is a duplicate of #887 the quest is not showing because by default Questie only shows quests 7 level above your own. "The Captain's Quest" is a level 43 quest though.

**Closed by BreakBB** 2019-10-09 19:54 UTC
Labels: quest issue

**Comment by AlistairJM** [comment] 2019-10-09 19:58
Sorry, dunno how i missed the template. However, I am confident that I changed the sliders to max, but you could be right. If i find otherwise I will let you know.

**Comment by BreakBB** [comment] 2019-10-09 20:04
@AlistairJM I had another look. Even though you linked a different quest ID it this is "the same quest". And moreover I had to correct myself because the quest is for level 47 instead of 43. So even with the current max (10 levels) you can't see it.

#694 tracks to increase the range of those sliders

**Comment by AlistairJM** [comment] 2019-10-09 20:30
Excellent, agree it would be great to increase the range of those to allow visibility of any available quest that can be picked up, even if 10+ above you.

Thanks
