### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by cowhunter101** [AeroScripts/QuestieDev#1948] opened 2020-05-15 15:56 UTC
Date: 2020-05-15 10:52:13
ID: 1
Error occured in: Global
Count: 1
Message: ...ce\AddOns\Questie\Modules\Tracker\QuestieTracker.lua line 791:
   'for' limit must be a number
Debug:
   ...ce\AddOns\Questie\Modules\Tracker\QuestieTracker.lua:791:
      ...ce\AddOns\Questie\Modules\Tracker\QuestieTracker.lua:783
   ..\SharedXML\C_TimerAugment.lua:16:
      ..\SharedXML\C_TimerAugment.lua:14
Locals:
(for index) = 1
(for limit) = nil
(for step) = 1
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "'for' limit must be a number"
_QuestieTracker = <table> {
 ItemButtons = <table> {
 }
 StartFadeTicker = <function> defined @Interface\AddOns\Questie\Modules\Tracker\QuestieTracker.lua:781
 baseFrame = <unnamed> {
 }
 CreateActiveQuestsFrame = <function> defined @Interface\AddOns\Questie\Modules\Tracker\QuestieTracker.lua:416
 expandButton = <unnamed> {
 }
 GetNextItemButton = <function> defined @Interface\AddOns\Questie\Modules\Tracker\QuestieTracker.lua:776
 PrintProgressColor = <function> defined @Interface\AddOns\Questie\Modules\Tracker\QuestieTracker.lua:1040
 GetNextLine = <function> defined @Interface\AddOns\Questie\Modules\Tracker\QuestieTracker.lua:769
 FadeTickerDirection = true
 menuFrame = QuestieTrackerMenuFrame {
 }
 OnDragStop = <function> defined @Interface\AddOns\Questie\Modules\Tracker\QuestieTrackerPrivates.lua:38
 LineFrames = <table> {
 }
 FadeTicker = <table> {
 }
 SetSafePoint = <function> defined @Interface\AddOns\Questie\Modules\Tracker\QuestieTracker.lua:308
 activeQuestsFrame = <unnamed> {
 }
 IsFirstRun = true
 OnDragStart = <function> defined @Interface\AddOns\Questie\Modules\Tracker\QuestieTrackerPrivates.lua:14
 FadeTickerValue = 0.060000
}

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AdiBags, vv1.9.17-classic
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucScanData, v8.2.6365 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  Auctionator, v100.0.6
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  Clique, vv1.0.3-classic
  DBMCore, v1.13.43
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  honorspy, v1.7.3
  Informant, v8.2.6374 (SwimmingSeadragon)
  PerlArcaneBar, v
  PerlCombatDisplay, v
  PerlConfig, v
  PerlFocus, v
  PerlParty, v
  PerlPartyPet, v
  PerlPartyTarget, v
  PerlPlayer, v
  PerlPlayerPet, v
  PerlTarget, v
  PerlTargetTarget, v
  Questie, v5.10.2
  RCLootCouncilClassic, v0.8.0
  Recount, vv1.13.4b
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Spy, v1.0.25
  Stubby, v8.2.6376 (SwimmingSeadragon)
  WeakAuras, v2.17.4
  BlizRuntimeLib_enUS v1.13.4.11304 <none>
  (ck=4d9)

**Comment by BreakBB** [comment] 2020-05-15 23:23
Duplicate of #1868

**Closed by BreakBB** 2020-05-15 23:23 UTC
