### ISSUE TITLE
Quests don't show correctly (but /reload helps) - Desync bug

### ISSUE THREAD

**Issue by BreakBB** [AeroScripts/QuestieDev#860] opened 2019-09-07 09:12 UTC
## Bug description

Sometimes a quest start, quest end or an objective doesn't show correctly. This is because there is a desync bug in our code which we're heavily investigating.

This issue will stay as master issue for issues opened/fixed this way

## Questie version

Even with v4.017 this bug exists, but it should be much less likely than in previous versions.

**Comment by AeroScripts** [comment] 2019-09-07 09:25
I think the main remaining issue is still related to QLU firing too early. Available quest desync (player_levelup) seems good now, as does objectives on quest_accepted 

QLU misfiring could cause it to not add the quest turn-in point

**Comment by MysticalOS** [comment] 2019-09-07 15:55
It's also worth noting that looting from mailbox (such as getting cooking items off AH) or buying from vendor are a sure desync 100% of time.

Key example, southshore and  theramore both have a quest to literlaly just walk up to vendor and buy spices, but when you do so, it doesn't update quest progress even though quest tracker does update. For both of these quests I had to use the handy new control click feature to reload questie POI for turnin/progress to update.

**Comment by schmoopiepoopie** [comment] 2019-09-11 19:15
Lvl 10 (Horde) Druid quest chain "Heeding the Call" shows up as available when already completed. /reload did not resolve issue.

Large map shows "Notooltip/Notooltip" at quest location in Red Cloud Mesa. 
Attached screencap shows the UI. 
![questiebug](https://user-images.githubusercontent.com/55208875/64727467-86066c80-d49e-11e9-9c20-e3d3a70b2f46.png)

**Comment by BreakBB** [comment] 2019-09-11 20:19
@schmoopiepoopie Are you using the latest Questie version v4.0.18? And is your WoW client English?

**Comment by schmoopiepoopie** [comment] 2019-09-11 20:25
Yes to both. I update through twitch.

**Comment by schmoopiepoopie** [comment] 2019-09-11 20:27
Sorry, this is Schmoopiepoopie. Email gets forwarded to this address

**Comment by AeroScripts** [comment] 2019-09-11 20:29
@schmoopiepoopie don't worry it shows as Schmoopiepoopie on github

This looks like it could be AAP actually, and "Notooltip" exists nowhere in questie's code

**Comment by Muehe** [comment] 2019-09-11 20:32
@schmoopiepoopie The text below the minimap is definitly AAP, the map note probably too. Try entering `/aap skip` in the chat.

**Comment by schmoopiepoopie** [comment] 2019-09-11 20:32
Ok I’ll play around and disable add-ons one at a time, trying to find the
offender.

**Comment by Muehe** [comment] 2019-09-11 21:02
@schmoopiepoopie The line still mentions "Heeding the Call", so maybe just `/aap skip` again? :smile: 

Anyway, good luck with the AAP guys.

**Comment by Gogo1951** [comment] 2019-12-11 14:45
Had this issues, really hurts when there's RP for a quest and you leave the zone not realizing... then a day or two later you see the ! on the map and have to run back.

**Comment by AeroScripts** [comment] 2020-08-19 23:05
As this can be caused by many different things and can pop up from time to time, it makes more sense to have specific issues for those cases, so I'm closing this.

**Closed by AeroScripts** 2020-08-19 23:05 UTC
Labels: bug, quest issue
