### ISSUE TITLE
The Restless Souls & Imp Delivery quest errors

### ISSUE THREAD

**Issue by higewolf** [AeroScripts/QuestieDev#1401] opened 2019-10-23 00:57 UTC
## Bug description
See errors below

## Screenshots
![image](https://user-images.githubusercontent.com/42793065/67346955-5e6edf00-f4f5-11e9-9c5b-6c5ef2da9073.png)

## Questie version
5.0.0

**Comment by SpareSimian** [comment] 2019-10-23 03:42
Duplicate of issue #1399

**Closed** 2019-10-23 06:19 UTC
Labels: bug
