### ISSUE TITLE
The missing diplomat

### ISSUE THREAD

**Issue by Djfe** [AeroScripts/QuestieDev#1929] opened 2020-05-07 03:31 UTC
## Description

This part of the quest keeps on showing up, even after you talked to the archmage (at the end of the quest).
When they teleport back the question mark (?) on the map changes position. It's at two places then, the sentry point where he was earlier and jaina's tower in theramore.
/reload (reloading the ui) makes the ? disappear. (since the quest has been completed correctly)

## Wowhead link

https://classic.wowhead.com/quest=1324/the-missing-diplomat

## Questie version

5.4.2

**Comment by BreakBB** [comment] 2020-05-10 12:20
@Djfe Could you update your Questie version and check again if the quest still shows up? Sounds like a weird issue.

**Comment by Djfe** [comment] 2020-05-10 20:20
I would need to do the quest again then on another account since the issue only happened to me upon quest completion

**Comment by BreakBB** [comment] 2020-05-10 21:31
I think someone else also reported something similar exactly on this quest : thinking:

**Comment by Painstormx** [comment] 2020-05-16 20:57
Just adding that I've done this quest on 4 chars now, and Questie doesn't recognize when the final quest completes (talking to Jaina I think).
A /reload always helps.

**Comment by Djfe** [comment] 2020-05-17 02:23
thank you for confirming my observation

**Comment by wodim** [comment] 2020-06-01 16:47
Keeps happening. I finished the questline and still...

![image](https://user-images.githubusercontent.com/1001553/83431802-31de5680-a438-11ea-9cda-80cfc0fada35.png)

**Comment by Gogo1951** [comment] 2020-08-19 23:28
Dupe of https://github.com/AeroScripts/QuestieDev/issues/1632

**Closed by Gogo1951** 2020-08-19 23:28 UTC
Labels: need more info, quest issue
