### ISSUE TITLE
Tooltip Enhancement: Show Related Quest

### ISSUE THREAD

**Issue by pquerner** [AeroScripts/QuestieDev#1759] opened 2020-02-08 23:18 UTC
If its possible, can you show the related quest on a items tooltip ?

I ask this because sometimes my inventory is quite full and I have no idea if its okay to delete that item yet or if it belongs to some (finished or unfinished) quest.

I've seen https://github.com/wow-vanilla-addons/QuestItem but this was for the original 1.12 client, so I am not sure how much of that salvageable.

**Comment by Gogo1951** [comment] 2020-02-10 14:06
Dupe of https://github.com/AeroScripts/QuestieDev/issues/1586

**Closed** 2020-02-10 14:11 UTC
Labels: feature request
