### ISSUE TITLE
Collapsible Quest Tracker

### ISSUE THREAD

**Issue by SpockAce** [AeroScripts/QuestieDev#1719] opened 2020-01-17 16:18 UTC
Hello I've been using Questie since I came back to WoW Classic and I would like to suggest 2 improvements

1 - the option via button in the quest tracker to minimize and colapse the tracked quests as sometimes the quest trackers gets in the way of a fight or battleground. Something similar to what Monkey Quest does.

2 - Add a lineBreak function to the tracker so that very long quest description lines can fit within a stablished quest tracker window size. Currently if the line is to big it can throw the Quest tracker all the way to the middle of the screen.

**Comment by Gogo1951** [comment] 2020-01-18 01:30
2 is a dupe of https://github.com/AeroScripts/QuestieDev/issues/1612

**Comment by BreakBB** [comment] 2020-01-18 01:40
@SpockAce Not sure if you mean #1545 with your 1. point (where you commented as well). I am the only active developer atm and I am also very limited on time. But I will try to implemented some new things in really near future.

**Comment by BreakBB** [comment] 2020-02-10 22:25
Closing this since it is A) a dupe and B) covered in another issue.

**Closed by BreakBB** 2020-02-10 22:25 UTC
Labels: feature request
