### ISSUE TITLE
Adjust quest tracker position

### ISSUE THREAD

**Issue by xEgdodx** [AeroScripts/QuestieDev#1153] opened 2019-09-27 17:16 UTC
Currently the quest tracker covers the lower portion of the mini map (depending on UI scale).  Could we please get an option to mover the tracker window, or at least have the default moved down a few lines?  Thanks, great mod!

Edit:  Never mind, just found the move tracker option. Thanks!

**Comment by carsono311** [comment] 2019-10-05 03:01
I am fairly sure you can close this ticket item yourself if you feel the issue is resolved.

**Comment by xEgdodx** [comment] 2019-10-05 17:05
Ok

**Closed** 2019-10-06 20:59 UTC
Labels: feature request
