### ISSUE TITLE
Quest Tracker Not Appearing - Quest Objectives Not Showing on Map

### ISSUE THREAD

**Issue by LamerGamer** [AeroScripts/QuestieDev#430] opened 2017-05-13 02:29 UTC
Questie gives the error as follows when logging in:

`Count: Infinite
Error
Interface\AddOns\!Questie\Modules\QuestieTracker.lua:48: attempt to perform arithmetic on field 'lastUpdate1' (a nil value)`

My Quest Tracker does not appear on the side of my screen, and collectable quest objectives are not appearing on my map, however available and completable quests still appear. I've included a picture as example.

![picture](http://i.imgur.com/r4xV1TT.jpg)

The issue began after installing another AddOn (ShaguDB), however after removal, clearing cache, etc. it has been unable to recover. I am using Questie 3.69, and have tried updating to 3.70 to no avail. I have attempted to use QuestieCompatability as well, with no results.

> Edit by Muehe: embed picture.

**Comment by Muehe** [comment] 2017-05-13 02:35
Which version of ShaguQuest are you using? As far as I know [the latest stable release, 7.2,](https://github.com/shagu/ShaguQuest/releases) should work fine with Questie. By the way, I'm working on an updated version of ShaguQuest, you can get a beta version [here](https://github.com/Muehe/classicdb/releases).

**Comment by LamerGamer** [comment] 2017-05-13 02:38
It was Shagu 7.2, latest stable. I'm unsure if it was the cause of Questie breaking, but it was unporn restarting after installing it that I noticed the problem.

**Comment by Muehe** [comment] 2017-05-13 02:53
I tried to reproduce this with just Questie 3.7 and ShaguQuest 7.2 (/ShaguDB/Cartographer), but nothing so far. Everything seems to be working fine, tracker as well as the arrow. Maybe some other addon is interfering?

**Comment by LamerGamer** [comment] 2017-05-13 02:57
The only other possibility I could imagine would be Cartographer, since it comes with Shagu, however I have reinstalled my old Cartographer version as well.

I've noticed that logging on to another character, I managed to get the objectives to show on his map after switching a few versions around, however the character in the screenshot is still effected.

Is there any way I could submit further information?

**Comment by Muehe** [comment] 2017-05-13 03:02
Yes, go to `<WOW_FOLDER>\WTF\Account\<YOUR_ACCOUNT_NAME>\<SERVER_NAME>\<BUGGED_CHARACTER_NAME>\SavedVariables`. There you open the `!Questie.lua` with a text editor and upload the content on https://gist.github.com/, then link the gist here. The problem being specific to one character sounds like some specific quest might be causing this issue and with the information from that file I should be able to replicate your situation.

**Comment by LamerGamer** [comment] 2017-05-13 03:04
[https://gist.github.com/LamerGamer/a0cb9abc12e0b6b4c006ba722c449a49](url)

**Comment by Muehe** [comment] 2017-05-13 03:50
I tried accepting the two quests you have marked as tracked, but to no avail. Still no errors with both 3.69 and 3.7.

Judging from your QuestieConfig table being awfully short compared to mine, It is most likely some sort of corruption in the SavedVariables, and deleting them should fix it. Note that this will delete all finished quests (if you choose to just delete the whole WTF folder, all settings for the client and other addons as well), and therefore display of available quests might be wrong sometimes. So before trying this approach, make a backup of the WTF folder in case it doesn't fix the problem. 

If you want to manually port the finished quest from your backup you have to log in and out with each character at least once, so there are new, proper SavedVariables for them, then copy the content of their respective QuestieSeenQuests table in the backed up files, to the one in the new file.

**Comment by LamerGamer** [comment] 2017-05-13 03:56
Thank you, it seems clearing the SavedVariables folder fixed the issue. I tried deleting the !Questie.lua file prior, and nothing happened, so I did not think tinkering around with the files in my WTF folder would fix anything. Perhaps it was another addon that caused the issue after all.

I'm unsure if the problem is solved, but at the very least it is fixed.

**Comment by Muehe** [comment] 2017-05-13 04:07
Well as long as it works again. If you have anymore problems, just reopen the issue or hit us up on our Discord channel: https://discord.gg/phKnHVu

About ShaguQuest's Cartographer, I added some fixes (e.g. notes displaying above note tooltips) and features to it, so if you want to use ShaguQuest, I suggest using the Cartographer provided with it. The Cartographer in my ShaguQuest fork has even more fixes (mainly map size scroll sticking to cursor), but they are not in the current release yet, so you would have to grab Cartographer from the repository instead of the release.

**Closed by Muehe** 2017-05-13 04:07 UTC
Labels: investigating
