### ISSUE TITLE
Errors after update!!!

### ISSUE THREAD

**Issue by reportingperson** [AeroScripts/QuestieDev#1400] opened 2019-10-22 21:58 UTC
Here is the errors I receive when I log into my character .. after updating...

17:47:20] Questie: [ERROR] [QuestieQuest]: There was an error populating objectives for Liquid Stone 715 1 Interface\AddOns\Questie\Modules\QuestieQuest.lua:931: attempt to index field '?' (a nil value)
[17:47:20] Questie: [ERROR] [QuestieQuest]: There was an error populating objectives for Liquid Stone 715 2 Interface\AddOns\Questie\Modules\QuestieQuest.lua:931: attempt to index field '?' (a nil value)
[17:47:20] Questie: [ERROR] [QuestieQuest]: There was an error populating objectives for Clamlette Surprise 6610 1 Interface\AddOns\Questie\Modules\QuestieQuest.lua:931: attempt to index field '?' (a nil value)

**Comment by SpareSimian** [comment] 2019-10-23 03:42
Duplicate of issue #1399

**Closed** 2019-10-23 06:19 UTC
Labels: bug
