### ISSUE TITLE
Not tracking...

### ISSUE THREAD

**Issue by statiqshock** [AeroScripts/QuestieDev#303] opened 2016-12-22 07:54 UTC
I went from having icons on the map tracking many of my quests, to not having anything (save two quests that could be tracked but not untracked). it began when I toggled a quest off of my map since I had completed it

I completed those two quests and now I have NO tracking at all.
I've unistalled, tried different versions. Tried UI scale changes, tried disabling other mods. I can't get it to work

My questie will not track anything new

**Comment by AeroScripts** [comment] 2016-12-23 10:51
That is very strange. Have you tried running /questie showquests command?

**Comment by AeroScripts** [comment] 2016-12-25 01:12
assuming this is a duplicate of #307 so closing for now

**Closed by AeroScripts** 2016-12-25 01:12 UTC
